# LASSER on Kaggle

GEARS with an optional GSR-style learned co-expression graph. Needs **Internet on** (GEARS downloads Norman and the GO graph from Harvard Dataverse) and a **GPU (T4)**.

Cells: install, get the code, run the tests (before any real training), baseline run, graph-learning run, results.

In [1]:
# 1. Dependencies. GEARS is vendored inside lasser/ (lasser/gears), so no cell-gears install.
#    Kaggle already has torch, numpy, pandas, scipy, scikit-learn, networkx, tqdm, requests.
!pip install -q torch_geometric scanpy pytest

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 56.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 78.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.2/190.2 kB 10.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 376.9/376.9 kB 15.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 230.5/230.5 kB 8.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 54.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 3.9 MB/s eta 0:00:00

In [2]:
# 2. Get the code: clone, then move the self-contained package next to the notebook.
REPO_URL = "https://github.com/LegendaryDarkKnight/LASSER"   # <- set this
REPO_DIR = "/kaggle/working/lasser-repo"
!rm -rf {REPO_DIR} /kaggle/working/lasser
!git clone -q {REPO_URL} {REPO_DIR}
!mv {REPO_DIR}/lasser /kaggle/working/lasser
!git -C {REPO_DIR} log -1 --oneline

02a13c9 (HEAD -> main, origin/main, origin/HEAD) fix: format issue fixing

In [3]:
# 3. Tests 1-8 (tiny subsets; first run also downloads Norman, ~10-20 min in total).
%env LASSER_DATA_DIR=/kaggle/working/data
%env LASSER_TEST_DIR=/kaggle/working/lasser_tests
!cd /kaggle/working && python -m pytest {REPO_DIR}/tests -m "not smoke" -p no:cacheprovider -rA -s --tb=short 2>&1 | tee /kaggle/working/test_output.txt | grep -vE "it/s\]|s/it\]"

env: LASSER_DATA_DIR=/kaggle/working/data
env: LASSER_TEST_DIR=/kaggle/working/lasser_tests
============================= test session starts ==============================
platform linux -- Python 3.13.15, pytest-8.4.2, pluggy-1.6.0
rootdir: /kaggle/working
plugins: fast-array-utils-1.5.1, zarr-3.4.0, typeguard-4.6.0, anyio-4.14.2, langsmith-0.12.1
collected 16 items

lasser-repo/tests/test_00_packaging.py ..lasser modules loaded: ['lasser', 'lasser._eval', 'lasser.config', 'lasser.evaluation', 'lasser.gears', 'lasser.gears.data_utils', 'lasser.gears.gears', 'lasser.gears.inference', 'lasser.gears.model', 'lasser.gears.pertdata', 'lasser.gears.utils', 'lasser.gears.version', 'lasser.run', 'lasser.tracking', 'lasser.utils']
.
lasser-repo/tests/test_01_parity.py Found local copy...
Found local copy...
Found local copy...
These perturbations are not in the GO graph and their perturbation can thus not be predicted
['RHOXF2BB+ctrl' 'LYL1+IER5L' 'ctrl+IER5L' 'KIAA1804+ctrl' 'IER5L+ctrl'
 'RHOXF2BB+ZBTB25' 'RHOXF2BB+SET']
Local copy of pyg dataset is detected. Loading...
Done!
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
Found local copy...
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
Found local copy...
here1
here1
co-expression graph: 6364 edges
.Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
Found local copy...
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
Found local copy...
here1
here1
losses lasser: [0.5793300271034241, 0.47770318388938904, 0.4540538489818573, 0.5027831792831421, 0.5451818108558655]
losses GEARS:  [0.5793300271034241, 0.47770318388938904, 0.4540538489818573, 0.5027831792831421, 0.5451818108558655]
.2026-10-06 14:06:20,219 INFO lasser.tracking: run c0d4d623 -> /kaggle/working/lasser_tests/runs/norman_seed1_base_20261006-140620_parity
2026-10-06 14:06:20,226 INFO lasser.run: device: cpu (GEARS training)
2026-10-06 14:06:20,226 WARNING lasser.run: running on CPU although CUDA is available (cfg.device='cpu')
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
here1
2026-10-06 14:06:20,231 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75.pkl', 'norman_simulation_1_0.75_subgroup.pkl'])
2026-10-06 14:06:20,233 INFO lasser.utils: [gears_init] start
Found local copy...
2026-10-06 14:06:38,749 INFO lasser.utils: [gears_init] done in 18.5s, peak CUDA memory 0.00 GB
2026-10-06 14:06:38,756 INFO lasser.run: co-expression graph used (gears_static): {'num_nodes': 5045, 'num_edges': 6364, 'num_self_loops': 4699, 'degree_min': 0, 'degree_median': 0.0, 'degree_mean': 0.33002973240832506, 'degree_max': 20, 'degree_gini': 0.9324442777762897, 'isolated_genes': 4419}
2026-10-06 14:06:38,756 INFO lasser.run: training GEARS on cpu for 1 epochs
2026-10-06 14:06:38,756 INFO lasser.utils: [gears_train] start
Start Training...
Epoch 1 Step 1 Train Loss: 0.5596
Epoch 1: Train Overall MSE: 0.0229 Validation Overall MSE: 0.0230.
Train Top 20 DE MSE: 0.4800 Validation Top 20 DE MSE: 0.5874.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.5992
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.02995357538263003
test_combo_seen0_pearson: 0.9144783
test_combo_seen0_mse_de: 0.4623212884180248
test_combo_seen0_pearson_de: 0.6718298064337836
test_combo_seen1_mse: 0.030566621398509936
test_combo_seen1_pearson: 0.9133015
test_combo_seen1_mse_de: 0.6131469777942267
test_combo_seen1_pearson_de: 0.6955304116357205
test_combo_seen2_mse: 0.027026572215713952
test_combo_seen2_pearson: 0.92176104
test_combo_seen2_mse_de: 0.8015641824979531
test_combo_seen2_pearson_de: 0.7347194
test_unseen_single_mse: 0.02360451454296708
test_unseen_single_pearson: 0.9316064
test_unseen_single_mse_de: 0.5100661712090692
test_unseen_single_pearson_de: 0.7765138890180323
test_combo_seen0_pearson_delta: 0.025264971
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.4888888888888888
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.3528265107212476
test_combo_seen0_mse_top20_de_non_dropout: 0.8610302640332116
test_combo_seen1_pearson_delta: -0.014741777
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.5127906976744186
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.391738390268702
test_combo_seen1_mse_top20_de_non_dropout: 0.8670923175333545
test_combo_seen2_pearson_delta: -0.017429557
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.5078947368421052
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.4152202965140883
test_combo_seen2_mse_top20_de_non_dropout: 0.8496585033441845
test_unseen_single_pearson_delta: -0.035758734
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.5430555555555556
test_unseen_single_frac_sigma_below_1_non_dropout: 0.47431203963066715
test_unseen_single_mse_top20_de_non_dropout: 0.5942009387330877
Done!
2026-10-06 14:08:38,945 INFO lasser.utils: [gears_train] done in 120.2s, peak CUDA memory 0.00 GB
2026-10-06 14:08:38,967 INFO lasser.utils: [evaluate] start
2026-10-06 14:08:57,512 INFO lasser.evaluation: test (eval.py): pearson_delta=-0.0189 mse_top20_de=0.5992 nmse_top20_de=1.7795 over 107 perts
2026-10-06 14:08:57,512 INFO lasser.evaluation:   combo_seen0    pearson_delta=0.0253 mse_top20_de=0.4623 (9 perts)
2026-10-06 14:08:57,513 INFO lasser.evaluation:   combo_seen1    pearson_delta=-0.0147 mse_top20_de=0.6131 (43 perts)
2026-10-06 14:08:57,513 INFO lasser.evaluation:   combo_seen2    pearson_delta=-0.0174 mse_top20_de=0.8016 (19 perts)
2026-10-06 14:08:57,513 INFO lasser.evaluation:   unseen_single  pearson_delta=-0.0358 mse_top20_de=0.5101 (36 perts)
2026-10-06 14:08:57,513 INFO lasser.utils: [evaluate] done in 18.5s, peak CUDA memory 0.00 GB
2026-10-06 14:08:57,529 INFO lasser.tracking: appended run c0d4d623 to /kaggle/working/lasser_tests/runs/runs.csv
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
Found local copy...
Start Training...
Epoch 1 Step 1 Train Loss: 0.5596
Epoch 1: Train Overall MSE: 0.0229 Validation Overall MSE: 0.0230.
Train Top 20 DE MSE: 0.4800 Validation Top 20 DE MSE: 0.5874.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.5992
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.02995357538263003
test_combo_seen0_pearson: 0.9144783
test_combo_seen0_mse_de: 0.4623212884180248
test_combo_seen0_pearson_de: 0.6718298064337836
test_combo_seen1_mse: 0.030566621398509936
test_combo_seen1_pearson: 0.9133015
test_combo_seen1_mse_de: 0.6131469777942267
test_combo_seen1_pearson_de: 0.6955304116357205
test_combo_seen2_mse: 0.027026572215713952
test_combo_seen2_pearson: 0.92176104
test_combo_seen2_mse_de: 0.8015641824979531
test_combo_seen2_pearson_de: 0.7347194
test_unseen_single_mse: 0.02360451454296708
test_unseen_single_pearson: 0.9316064
test_unseen_single_mse_de: 0.5100661712090692
test_unseen_single_pearson_de: 0.7765138890180323
test_combo_seen0_pearson_delta: 0.025264971
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.4888888888888888
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.3528265107212476
test_combo_seen0_mse_top20_de_non_dropout: 0.8610302640332116
test_combo_seen1_pearson_delta: -0.014741777
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.5127906976744186
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.391738390268702
test_combo_seen1_mse_top20_de_non_dropout: 0.8670923175333545
test_combo_seen2_pearson_delta: -0.017429557
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.5078947368421052
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.4152202965140883
test_combo_seen2_mse_top20_de_non_dropout: 0.8496585033441845
test_unseen_single_pearson_delta: -0.035758734
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.5430555555555556
test_unseen_single_frac_sigma_below_1_non_dropout: 0.47431203963066715
test_unseen_single_mse_top20_de_non_dropout: 0.5942009387330877
Done!
here1
.
lasser-repo/tests/test_02_graphs.py 2026-10-06 14:11:25,860 INFO lasser.tracking: run 71f2a6f5 -> /kaggle/working/lasser_tests/runs/norman_seed1_base_20261006-141125_test
2026-10-06 14:11:25,866 INFO lasser.run: device: cuda:0 (Tesla T4, 14.6 GB) (GEARS training)
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
here1
2026-10-06 14:11:25,870 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75.pkl', 'norman_simulation_1_0.75_subgroup.pkl'])
2026-10-06 14:11:25,872 INFO lasser.utils: [gears_init] start
Found local copy...
2026-10-06 14:11:45,044 INFO lasser.utils: [gears_init] done in 19.2s, peak CUDA memory 0.03 GB
2026-10-06 14:11:45,046 INFO lasser.run: co-expression graph used (gears_static): {'num_nodes': 5045, 'num_edges': 6364, 'num_self_loops': 4699, 'degree_min': 0, 'degree_median': 0.0, 'degree_mean': 0.33002973240832506, 'degree_max': 20, 'degree_gini': 0.9324442777762897, 'isolated_genes': 4419}
2026-10-06 14:11:45,047 INFO lasser.run: training GEARS on cuda:0 (Tesla T4, 14.6 GB) for 1 epochs
2026-10-06 14:11:45,047 INFO lasser.utils: [gears_train] start
Start Training...
Epoch 1 Step 1 Train Loss: 0.5596
Epoch 1: Train Overall MSE: 0.0230 Validation Overall MSE: 0.0230.
Train Top 20 DE MSE: 0.4801 Validation Top 20 DE MSE: 0.5878.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.5993
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.02996632643043995
test_combo_seen0_pearson: 0.9144322
test_combo_seen0_mse_de: 0.4625143796309001
test_combo_seen0_pearson_de: 0.6717264917161729
test_combo_seen1_mse: 0.03057389294858589
test_combo_seen1_pearson: 0.91327226
test_combo_seen1_mse_de: 0.6132611111618665
test_combo_seen1_pearson_de: 0.6956092126147692
test_combo_seen2_mse: 0.027035597515733617
test_combo_seen2_pearson: 0.92172825
test_combo_seen2_mse_de: 0.8016995595473992
test_combo_seen2_pearson_de: 0.7346539
test_unseen_single_mse: 0.0236158084589988
test_unseen_single_pearson: 0.9315668
test_unseen_single_mse_de: 0.5099501771878244
test_unseen_single_pearson_de: 0.7764867506921291
test_combo_seen0_pearson_delta: 0.025164753
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.4888888888888888
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.3528265107212476
test_combo_seen0_mse_top20_de_non_dropout: 0.8612517697943581
test_combo_seen1_pearson_delta: -0.01461498
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.5139534883720931
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.39310637932478953
test_combo_seen1_mse_top20_de_non_dropout: 0.8670332329564316
test_combo_seen2_pearson_delta: -0.017309885
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.5078947368421052
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.4152202965140883
test_combo_seen2_mse_top20_de_non_dropout: 0.8497666089158309
test_unseen_single_pearson_delta: -0.035721947
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.5416666666666665
test_unseen_single_frac_sigma_below_1_non_dropout: 0.47431203963066715
test_unseen_single_mse_top20_de_non_dropout: 0.594056456660231
Done!
2026-10-06 14:12:49,859 INFO lasser.utils: [gears_train] done in 64.8s, peak CUDA memory 0.92 GB
2026-10-06 14:12:49,880 INFO lasser.utils: [evaluate] start
2026-10-06 14:12:52,940 INFO lasser.evaluation: test (eval.py): pearson_delta=-0.0188 mse_top20_de=0.5993 nmse_top20_de=1.7827 over 107 perts
2026-10-06 14:12:52,940 INFO lasser.evaluation:   combo_seen0    pearson_delta=0.0252 mse_top20_de=0.4625 (9 perts)
2026-10-06 14:12:52,941 INFO lasser.evaluation:   combo_seen1    pearson_delta=-0.0146 mse_top20_de=0.6133 (43 perts)
2026-10-06 14:12:52,941 INFO lasser.evaluation:   combo_seen2    pearson_delta=-0.0173 mse_top20_de=0.8017 (19 perts)
2026-10-06 14:12:52,941 INFO lasser.evaluation:   unseen_single  pearson_delta=-0.0357 mse_top20_de=0.5100 (36 perts)
2026-10-06 14:12:52,942 INFO lasser.utils: [evaluate] done in 3.1s, peak CUDA memory 1.19 GB
2026-10-06 14:12:52,960 INFO lasser.tracking: appended run 71f2a6f5 to /kaggle/working/lasser_tests/runs/runs.csv
2026-10-06 14:12:52,962 INFO lasser.tracking: run 7b7d6a61 -> /kaggle/working/lasser_tests/runs/norman_seed1_gl_20261006-141252_test
2026-10-06 14:12:52,967 INFO lasser.run: device: cuda:0 (Tesla T4, 14.6 GB) (GEARS training and GSR graph learning)
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
here1
2026-10-06 14:12:52,971 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75.pkl', 'norman_simulation_1_0.75_subgroup.pkl'])
2026-10-06 14:12:52,971 INFO lasser.utils: [gsr_graph] start
2026-10-06 14:12:53,038 INFO lasser.graph: GSR graph learning on cuda:0 (Tesla T4, 14.6 GB)
2026-10-06 14:12:53,038 INFO lasser.utils: [gsr/data] start
2026-10-06 14:12:53,575 INFO lasser.data: training cells: 49849 (A0 subset 38824, H1 24957, H2 24892) over 138 training perturbations
2026-10-06 14:12:53,576 INFO lasser.utils: [gsr/data] done in 0.5s, peak CUDA memory 0.10 GB
2026-10-06 14:12:53,577 INFO lasser.utils: [gsr/views] start
2026-10-06 14:13:00,973 INFO lasser.data: metacells: 49849 cells -> 200 metacells
2026-10-06 14:13:01,024 INFO lasser.views: view E: dim 64, missing genes 234
2026-10-06 14:13:01,470 INFO lasser.views: view R: dim 32, missing genes 271
2026-10-06 14:13:01,746 INFO lasser.views: deepwalk epoch 1: loss 3.3745 over 425680 pairs
2026-10-06 14:13:01,748 INFO lasser.views: view S: dim 64, missing genes 4419
2026-10-06 14:13:01,748 INFO lasser.utils: [gsr/views] done in 8.2s, peak CUDA memory 0.16 GB
2026-10-06 14:13:01,748 INFO lasser.utils: [gsr/positives] start
2026-10-06 14:13:02,227 INFO lasser.pretrain: positives: {'h1_cells_used': 3000, 'candidate_pairs': 2920, 'bootstrap_kept_pairs': 781, 'positive_pairs': 781}
2026-10-06 14:13:02,228 INFO lasser.utils: [gsr/positives] done in 0.5s, peak CUDA memory 0.55 GB
2026-10-06 14:13:02,228 INFO lasser.utils: [gsr/pretrain] start
2026-10-06 14:13:02,295 INFO lasser.pretrain: link AUC of raw view features (baseline): {'E': 0.872, 'R': 0.7326, 'S': 0.3077, 'combined': 0.8342}
2026-10-06 14:13:02,861 INFO lasser.pretrain: pretrain step 5 (epoch 5): loss 5.1660 intra 5.0155 inter 5.4209 var 0.4919 | AUC {'E': 0.9602, 'R': 0.9303, 'S': 0.273, 'combined': 0.9555} | cos_std {'E': 0.254, 'R': 0.211, 'S': 0.151}
2026-10-06 14:13:03,166 INFO lasser.pretrain: pretrain step 10 (epoch 10): loss 5.0392 intra 4.9192 inter 5.2740 var 0.3122 | AUC {'E': 0.9372, 'R': 0.9412, 'S': 0.3072, 'combined': 0.9482} | cos_std {'E': 0.289, 'R': 0.312, 'S': 0.479}
2026-10-06 14:13:03,433 INFO lasser.pretrain: pretrain step 15 (epoch 15): loss 4.7241 intra 4.5879 inter 5.0259 var 0.2668 | AUC {'E': 0.9568, 'R': 0.9472, 'S': 0.2755, 'combined': 0.961} | cos_std {'E': 0.289, 'R': 0.32, 'S': 0.567}
2026-10-06 14:13:03,737 INFO lasser.pretrain: pretrain step 20 (epoch 20): loss 4.6737 intra 4.5636 inter 4.9065 var 0.2432 | AUC {'E': 0.9518, 'R': 0.9415, 'S': 0.2914, 'combined': 0.9578} | cos_std {'E': 0.322, 'R': 0.349, 'S': 0.559}
2026-10-06 14:13:03,759 INFO lasser.pretrain: pretraining done: best step 15, held-out link AUC 0.9610 (raw features 0.8342)
2026-10-06 14:13:03,766 INFO lasser.utils: [gsr/pretrain] done in 1.5s, peak CUDA memory 0.35 GB
2026-10-06 14:13:03,766 INFO lasser.utils: [gsr/refine] start
2026-10-06 14:13:03,874 INFO lasser.refine: refinement: {'a0_edges': 6364, 'removed': 20, 'added_directed': 38035, 'topup_directed': 0, 'refined_edges': 44379, 'new_weight_mean': 0.2686493694782257, 'a0_weight_mean': 0.5615240931510925}
2026-10-06 14:13:03,875 INFO lasser.utils: [gsr/refine] done in 0.1s, peak CUDA memory 0.15 GB
2026-10-06 14:13:03,875 INFO lasser.utils: [gsr/checks] start
2026-10-06 14:13:04,257 INFO lasser.checks: graph checks: H2 {'threshold': 0.2, 'hit_rate_added': 0.034, 'hit_rate_added_only': 0.034, 'hit_rate_topup': nan, 'hit_rate_degree_matched_random': 0.002, 'hit_rate_a0': 0.387, 'hit_rate_removed': 0.75, 'passes': True} | coverage {'low_degree_genes': 4935, 'low_degree_mean_degree_a0': 0.16757852077001012, 'low_degree_mean_degree_refined': 7.931509625126647, 'undirected_isolated_a0': 4419, 'undirected_isolated_refined': 0} | jaccard 0.030 | collapse ok True
2026-10-06 14:13:04,260 INFO lasser.utils: [gsr/checks] done in 0.4s, peak CUDA memory 0.40 GB
2026-10-06 14:13:04,353 INFO lasser.graph: GSR graph cached at /kaggle/working/lasser_tests/cache/gsr/norman_simulation_seed1_0.75_1729bcfa8982
2026-10-06 14:13:04,354 INFO lasser.utils: [gsr_graph] done in 11.4s, peak CUDA memory 0.40 GB
2026-10-06 14:13:04,356 INFO lasser.utils: [gears_init] start
Found local copy...
2026-10-06 14:13:23,121 INFO lasser.utils: [gears_init] done in 18.8s, peak CUDA memory 0.13 GB
2026-10-06 14:13:23,125 INFO lasser.run: co-expression graph used (gsr_refined): {'num_nodes': 5045, 'num_edges': 44379, 'num_self_loops': 4699, 'degree_min': 5, 'degree_median': 7.0, 'degree_mean': 7.865213082259663, 'degree_max': 25, 'degree_gini': 0.20170333930112855, 'isolated_genes': 0}
2026-10-06 14:13:23,210 INFO lasser.run: training GEARS on cuda:0 (Tesla T4, 14.6 GB) for 1 epochs
2026-10-06 14:13:23,210 INFO lasser.utils: [gears_train] start
Start Training...
Epoch 1 Step 1 Train Loss: 0.5596
Epoch 1: Train Overall MSE: 0.0229 Validation Overall MSE: 0.0230.
Train Top 20 DE MSE: 0.4785 Validation Top 20 DE MSE: 0.5859.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.5968
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.02988782214621703
test_combo_seen0_pearson: 0.91463375
test_combo_seen0_mse_de: 0.46051357293294537
test_combo_seen0_pearson_de: 0.6720408134990268
test_combo_seen1_mse: 0.030510763269524243
test_combo_seen1_pearson: 0.91343874
test_combo_seen1_mse_de: 0.6108034900633271
test_combo_seen1_pearson_de: 0.696712123273417
test_combo_seen2_mse: 0.026986997574567795
test_combo_seen2_pearson: 0.92186767
test_combo_seen2_mse_de: 0.7986275675265413
test_combo_seen2_pearson_de: 0.7354578
test_unseen_single_mse: 0.023585067053015035
test_unseen_single_pearson: 0.93165714
test_unseen_single_mse_de: 0.5077298168907873
test_unseen_single_pearson_de: 0.7771336622536182
test_combo_seen0_pearson_delta: 0.027333865
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.5
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.3528265107212476
test_combo_seen0_mse_top20_de_non_dropout: 0.8576094640625848
test_combo_seen1_pearson_delta: -0.012564907
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.5139534883720931
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.3904901002550222
test_combo_seen1_mse_top20_de_non_dropout: 0.863247967650031
test_combo_seen2_pearson_delta: -0.015206016
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.5052631578947367
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.41831627174628644
test_combo_seen2_mse_top20_de_non_dropout: 0.8465563090224015
test_unseen_single_pearson_delta: -0.034414716
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.538888888888889

In [4]:
# 3b. Optional test 9: full Norman, 1 epoch, flag off and on, checks the T4 memory budget.
%env LASSER_SMOKE=1
!cd /kaggle/working && python -m pytest {REPO_DIR}/tests/test_09_smoke.py -p no:cacheprovider -rA -s --tb=short 2>&1 | tee /kaggle/working/smoke_output.txt | grep -vE "it/s\]|s/it\]"
%env LASSER_SMOKE=0

env: LASSER_SMOKE=1
============================= test session starts ==============================
platform linux -- Python 3.13.15, pytest-8.4.2, pluggy-1.6.0
rootdir: /kaggle/working
plugins: fast-array-utils-1.5.1, zarr-3.4.0, typeguard-4.6.0, anyio-4.14.2, langsmith-0.12.1
collected 2 items

lasser-repo/tests/test_09_smoke.py Found local copy...
Found local copy...
Found local copy...
These perturbations are not in the GO graph and their perturbation can thus not be predicted
['RHOXF2BB+ctrl' 'LYL1+IER5L' 'ctrl+IER5L' 'KIAA1804+ctrl' 'IER5L+ctrl'
 'RHOXF2BB+ZBTB25' 'RHOXF2BB+SET']
Local copy of pyg dataset is detected. Loading...
Done!
2026-10-06 14:16:26,460 INFO lasser.tracking: run f3006654 -> /kaggle/working/lasser_tests/runs/norman_seed1_base_20261006-141626_smoke
2026-10-06 14:16:26,528 INFO lasser.run: device: cuda:0 (Tesla T4, 14.6 GB) (GEARS training)
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
here1
2026-10-06 14:16:26,535 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75.pkl', 'norman_simulation_1_0.75_subgroup.pkl'])
2026-10-06 14:16:26,536 INFO lasser.utils: [gears_init] start
Found local copy...
2026-10-06 14:16:45,579 INFO lasser.utils: [gears_init] done in 19.0s, peak CUDA memory 0.03 GB
2026-10-06 14:16:45,583 INFO lasser.run: co-expression graph used (gears_static): {'num_nodes': 5045, 'num_edges': 6364, 'num_self_loops': 4699, 'degree_min': 0, 'degree_median': 0.0, 'degree_mean': 0.33002973240832506, 'degree_max': 20, 'degree_gini': 0.9324442777762897, 'isolated_genes': 4419}
2026-10-06 14:16:45,583 INFO lasser.run: training GEARS on cuda:0 (Tesla T4, 14.6 GB) for 1 epochs
2026-10-06 14:16:45,583 INFO lasser.utils: [gears_train] start
Start Training...
Epoch 1 Step 1 Train Loss: 0.5244
Epoch 1 Step 51 Train Loss: 0.6199
Epoch 1 Step 101 Train Loss: 0.5159
Epoch 1 Step 151 Train Loss: 0.5197
Epoch 1 Step 201 Train Loss: 0.4527
Epoch 1 Step 251 Train Loss: 0.5968
Epoch 1 Step 301 Train Loss: 0.4058
Epoch 1 Step 351 Train Loss: 0.5522
Epoch 1 Step 401 Train Loss: 0.5115
Epoch 1 Step 451 Train Loss: 0.5265
Epoch 1 Step 501 Train Loss: 0.4455
Epoch 1 Step 551 Train Loss: 0.5932
Epoch 1 Step 601 Train Loss: 0.4601
Epoch 1 Step 651 Train Loss: 0.5048
Epoch 1 Step 701 Train Loss: 0.4585
Epoch 1 Step 751 Train Loss: 0.4512
Epoch 1 Step 801 Train Loss: 0.4588
Epoch 1 Step 851 Train Loss: 0.4291
Epoch 1 Step 901 Train Loss: 0.5480
Epoch 1 Step 951 Train Loss: 0.4267
Epoch 1 Step 1001 Train Loss: 0.4284
Epoch 1 Step 1051 Train Loss: 0.4873
Epoch 1 Step 1101 Train Loss: 0.4998
Epoch 1 Step 1151 Train Loss: 0.4291
Epoch 1 Step 1201 Train Loss: 0.4385
Epoch 1 Step 1251 Train Loss: 0.4400
Epoch 1 Step 1301 Train Loss: 0.4816
Epoch 1 Step 1351 Train Loss: 0.4483
Epoch 1 Step 1401 Train Loss: 0.4211
Epoch 1 Step 1451 Train Loss: 0.4389
Epoch 1 Step 1501 Train Loss: 0.4399
Epoch 1 Step 1551 Train Loss: 0.4756
Epoch 1: Train Overall MSE: 0.0078 Validation Overall MSE: 0.0093.
Train Top 20 DE MSE: 0.1503 Validation Top 20 DE MSE: 0.3272.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.2385
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.013799711337520016
test_combo_seen0_pearson: 0.96235114
test_combo_seen0_mse_de: 0.254809497959084
test_combo_seen0_pearson_de: 0.7288709746466743
test_combo_seen1_mse: 0.014516345127810573
test_combo_seen1_pearson: 0.96180165
test_combo_seen1_mse_de: 0.26490491210634626
test_combo_seen1_pearson_de: 0.8384964715602786
test_combo_seen2_mse: 0.013895998782429256
test_combo_seen2_pearson: 0.9625741
test_combo_seen2_mse_de: 0.2580707120267968
test_combo_seen2_pearson_de: 0.9060397
test_unseen_single_mse: 0.006774615936188234
test_unseen_single_pearson: 0.9812138
test_unseen_single_mse_de: 0.19250603964448804
test_unseen_single_pearson_de: 0.8773316111829546
test_combo_seen0_pearson_delta: 0.4683599
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.2111111111111111
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.75
test_combo_seen0_mse_top20_de_non_dropout: 0.3240592231353124
test_combo_seen1_pearson_delta: 0.44305494
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.23488372093023255
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.713953488372093
test_combo_seen1_mse_top20_de_non_dropout: 0.32561300348403843
test_combo_seen2_pearson_delta: 0.46356606
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.15263157894736842
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.7947368421052632
test_combo_seen2_mse_top20_de_non_dropout: 0.2638856309809183
test_unseen_single_pearson_delta: 0.38717586
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.2333333333333334
test_unseen_single_frac_sigma_below_1_non_dropout: 0.8263888888888888
test_unseen_single_mse_top20_de_non_dropout: 0.20697481909559834
Done!
2026-10-06 14:22:23,054 INFO lasser.utils: [gears_train] done in 337.5s, peak CUDA memory 0.87 GB
2026-10-06 14:22:23,076 INFO lasser.utils: [evaluate] start
2026-10-06 14:25:22,709 INFO lasser.evaluation: test (eval.py): pearson_delta=0.4300 mse_top20_de=0.2385 nmse_top20_de=2.5812 over 107 perts
2026-10-06 14:25:22,709 INFO lasser.evaluation:   combo_seen0    pearson_delta=0.4684 mse_top20_de=0.2548 (9 perts)
2026-10-06 14:25:22,709 INFO lasser.evaluation:   combo_seen1    pearson_delta=0.4431 mse_top20_de=0.2649 (43 perts)
2026-10-06 14:25:22,709 INFO lasser.evaluation:   combo_seen2    pearson_delta=0.4636 mse_top20_de=0.2581 (19 perts)
2026-10-06 14:25:22,709 INFO lasser.evaluation:   unseen_single  pearson_delta=0.3872 mse_top20_de=0.1925 (36 perts)
2026-10-06 14:25:22,711 INFO lasser.utils: [evaluate] done in 179.6s, peak CUDA memory 1.15 GB
2026-10-06 14:25:22,732 INFO lasser.tracking: appended run f3006654 to /kaggle/working/lasser_tests/runs/runs.csv
{'gears_init': {'seconds': 19.04, 'peak_cuda_gb': 0.026}, 'gears_train': {'seconds': 337.47, 'peak_cuda_gb': 0.87}, 'evaluate': {'seconds': 179.63, 'peak_cuda_gb': 1.154}}
{'graph_learning': False, 'graph_source': 'gears_static', 'graph_num_nodes': 5045, 'graph_num_edges': 6364, 'graph_num_self_loops': 4699, 'graph_degree_min': 0, 'graph_degree_median': 0.0, 'graph_degree_mean': 0.33002973240832506, 'graph_degree_max': 20, 'graph_degree_gini': 0.9324442777762897, 'graph_isolated_genes': 4419, 'test_pearson_delta': 0.43002511775565344, 'test_pearson_delta_top20_de': 0.5275256815157979, 'test_mse_top20_de': 0.23848376062777, 'test_nmse_top20_de': 2.5812456082305983, 'test_nmse_top20_de_ratio_of_means': 0.5459237192050614, 'test_frac_opposite_top20_de': 0.39299065420560747, 'test_mse': 0.011741218988339757, 'test_pearson': 0.9685162606833044, 'test_combo_seen0_pearson_delta': 0.46835990338895833, 'test_combo_seen0_mse_top20_de': 0.25480956956744194, 'test_combo_seen0_nmse_top20_de': 6.317881203107329, 'test_combo_seen1_pearson_delta': 0.4430549727996178, 'test_combo_seen1_mse_top20_de': 0.2649049523698036, 'test_combo_seen1_nmse_top20_de': 3.106495407473712, 'test_combo_seen2_pearson_delta': 0.46356606055991645, 'test_combo_seen2_mse_top20_de': 0.25807079829667745, 'test_combo_seen2_nmse_top20_de': 0.49756399667728396, 'test_unseen_single_pearson_delta': 0.3871758191203424, 'test_unseen_single_mse_top20_de': 0.1925060594868329, 'test_unseen_single_nmse_top20_de': 2.1194258554019454}
.2026-10-06 14:25:22,739 INFO lasser.tracking: run aec4ebb6 -> /kaggle/working/lasser_tests/runs/norman_seed1_gl_20261006-142522_smoke
2026-10-06 14:25:22,744 INFO lasser.run: device: cuda:0 (Tesla T4, 14.6 GB) (GEARS training and GSR graph learning)
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
here1
2026-10-06 14:25:22,753 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75.pkl', 'norman_simulation_1_0.75_subgroup.pkl'])
2026-10-06 14:25:22,755 INFO lasser.utils: [gsr_graph] start
2026-10-06 14:25:22,806 INFO lasser.graph: GSR graph learning on cuda:0 (Tesla T4, 14.6 GB)
2026-10-06 14:25:22,806 INFO lasser.utils: [gsr/data] start
2026-10-06 14:25:23,347 INFO lasser.data: training cells: 49849 (A0 subset 38824, H1 24957, H2 24892) over 138 training perturbations
2026-10-06 14:25:23,348 INFO lasser.utils: [gsr/data] done in 0.5s, peak CUDA memory 0.02 GB
2026-10-06 14:25:23,348 INFO lasser.utils: [gsr/views] start
2026-10-06 14:25:33,331 INFO lasser.data: metacells: 49849 cells -> 500 metacells
2026-10-06 14:25:34,096 INFO lasser.views: view E: dim 64, missing genes 234
2026-10-06 14:25:34,546 INFO lasser.views: view R: dim 32, missing genes 271
2026-10-06 14:25:34,940 INFO lasser.views: deepwalk epoch 1: loss 1.6828 over 1064200 pairs
2026-10-06 14:25:35,259 INFO lasser.views: deepwalk epoch 2: loss 0.0779 over 1064200 pairs
2026-10-06 14:25:35,542 INFO lasser.views: deepwalk epoch 3: loss 0.0568 over 1064200 pairs
2026-10-06 14:25:35,544 INFO lasser.views: view S: dim 64, missing genes 4419
2026-10-06 14:25:35,544 INFO lasser.utils: [gsr/views] done in 12.2s, peak CUDA memory 0.08 GB
2026-10-06 14:25:35,544 INFO lasser.utils: [gsr/positives] start
2026-10-06 14:25:41,248 INFO lasser.pretrain: positives: {'h1_cells_used': 19434, 'candidate_pairs': 1070, 'bootstrap_kept_pairs': 564, 'positive_pairs': 564}
2026-10-06 14:25:41,249 INFO lasser.utils: [gsr/positives] done in 5.7s, peak CUDA memory 1.57 GB
2026-10-06 14:25:41,249 INFO lasser.utils: [gsr/pretrain] start
2026-10-06 14:25:41,271 INFO lasser.pretrain: link AUC of raw view features (baseline): {'E': 0.9703, 'R': 0.8699, 'S': 0.7321, 'combined': 0.9697}
2026-10-06 14:25:41,702 INFO lasser.pretrain: pretrain step 10 (epoch 10): loss 4.6834 intra 4.4926 inter 5.1170 var 0.3473 | AUC {'E': 0.9684, 'R': 0.9665, 'S': 0.2286, 'combined': 0.9879} | cos_std {'E': 0.28, 'R': 0.35, 'S': 0.196}
2026-10-06 14:25:42,033 INFO lasser.pretrain: pretrain step 20 (epoch 20): loss 4.0445 intra 3.8817 inter 4.4139 var 0.2973 | AUC {'E': 0.9672, 'R': 0.9703, 'S': 0.2283, 'combined': 0.9872} | cos_std {'E': 0.313, 'R': 0.319, 'S': 0.296}
2026-10-06 14:25:42,357 INFO lasser.pretrain: pretrain step 30 (epoch 30): loss 3.7153 intra 3.5704 inter 4.0439 var 0.2649 | AUC {'E': 0.9595, 'R': 0.9592, 'S': 0.2299, 'combined': 0.9761} | cos_std {'E': 0.354, 'R': 0.354, 'S': 0.431}
2026-10-06 14:25:42,681 INFO lasser.pretrain: pretrain step 40 (epoch 40): loss 3.3568 intra 3.2224 inter 3.6611 var 0.2475 | AUC {'E': 0.9646, 'R': 0.9617, 'S': 0.2309, 'combined': 0.9799} | cos_std {'E': 0.328, 'R': 0.354, 'S': 0.416}
2026-10-06 14:25:43,028 INFO lasser.pretrain: pretrain step 50 (epoch 50): loss 3.2379 intra 3.1357 inter 3.4527 var 0.2292 | AUC {'E': 0.9707, 'R': 0.9601, 'S': 0.2443, 'combined': 0.9812} | cos_std {'E': 0.304, 'R': 0.343, 'S': 0.461}
2026-10-06 14:25:43,354 INFO lasser.pretrain: pretrain step 60 (epoch 60): loss 3.0068 intra 2.8903 inter 3.2716 var 0.2111 | AUC {'E': 0.9691, 'R': 0.9636, 'S': 0.2305, 'combined': 0.9786} | cos_std {'E': 0.301, 'R': 0.323, 'S': 0.459}
2026-10-06 14:25:43,354 INFO lasser.pretrain: early stop at step 60 (best step 10, AUC 0.9879)
2026-10-06 14:25:43,371 INFO lasser.pretrain: pretraining done: best step 10, held-out link AUC 0.9879 (raw features 0.9697)
2026-10-06 14:25:43,376 INFO lasser.utils: [gsr/pretrain] done in 2.1s, peak CUDA memory 0.25 GB
2026-10-06 14:25:43,376 INFO lasser.utils: [gsr/refine] start
2026-10-06 14:25:43,444 INFO lasser.refine: refinement: {'a0_edges': 6364, 'removed': 20, 'added_directed': 38848, 'topup_directed': 0, 'refined_edges': 45192, 'new_weight_mean': 0.24385404586791992, 'a0_weight_mean': 0.5615240931510925}
2026-10-06 14:25:43,445 INFO lasser.utils: [gsr/refine] done in 0.1s, peak CUDA memory 0.07 GB
2026-10-06 14:25:43,446 INFO lasser.utils: [gsr/checks] start
2026-10-06 14:25:44,595 INFO lasser.checks: graph checks: H2 {'threshold': 0.2, 'hit_rate_added': 0.036, 'hit_rate_added_only': 0.036, 'hit_rate_topup': nan, 'hit_rate_degree_matched_random': 0.002, 'hit_rate_a0': 0.581, 'hit_rate_removed': 0.75, 'passes': True} | coverage {'low_degree_genes': 4935, 'low_degree_mean_degree_a0': 0.16757852077001012, 'low_degree_mean_degree_refined': 8.11631205673759, 'undirected_isolated_a0': 4419, 'undirected_isolated_refined': 0} | jaccard 0.032 | collapse ok True
2026-10-06 14:25:44,599 INFO lasser.utils: [gsr/checks] done in 1.2s, peak CUDA memory 1.14 GB
2026-10-06 14:25:44,696 INFO lasser.graph: GSR graph cached at /kaggle/working/lasser_tests/cache/gsr/norman_simulation_seed1_0.75_acff059d6c09
2026-10-06 14:25:44,697 INFO lasser.utils: [gsr_graph] done in 21.9s, peak CUDA memory 1.14 GB
2026-10-06 14:25:44,699 INFO lasser.utils: [gears_init] start
Found local copy...
2026-10-06 14:26:04,558 INFO lasser.utils: [gears_init] done in 19.9s, peak CUDA memory 0.04 GB
2026-10-06 14:26:04,562 INFO lasser.run: co-expression graph used (gsr_refined): {'num_nodes': 5045, 'num_edges': 45192, 'num_self_loops': 4699, 'degree_min': 5, 'degree_median': 7.0, 'degree_mean': 8.026362735381566, 'degree_max': 25, 'degree_gini': 0.20115357700973754, 'isolated_genes': 0}
2026-10-06 14:26:04,651 INFO lasser.run: training GEARS on cuda:0 (Tesla T4, 14.6 GB) for 1 epochs
2026-10-06 14:26:04,652 INFO lasser.utils: [gears_train] start
Start Training...
Epoch 1 Step 1 Train Loss: 0.5244
Epoch 1 Step 51 Train Loss: 0.6134
Epoch 1 Step 101 Train Loss: 0.5160
Epoch 1 Step 151 Train Loss: 0.5160
Epoch 1 Step 201 Train Loss: 0.4541
Epoch 1 Step 251 Train Loss: 0.6010
Epoch 1 Step 301 Train Loss: 0.4167
Epoch 1 Step 351 Train Loss: 0.5521
Epoch 1 Step 401 Train Loss: 0.5113
Epoch 1 Step 451 Train Loss: 0.5355
Epoch 1 Step 501 Train Loss: 0.4461
Epoch 1 Step 551 Train Loss: 0.6088
Epoch 1 Step 601 Train Loss: 0.4579
Epoch 1 Step 651 Train Loss: 0.5062
Epoch 1 Step 701 Train Loss: 0.4569
Epoch 1 Step 751 Train Loss: 0.4507
Epoch 1 Step 801 Train Loss: 0.4732
Epoch 1 Step 851 Train Loss: 0.4274
Epoch 1 Step 901 Train Loss: 0.5411
Epoch 1 Step 951 Train Loss: 0.4257
Epoch 1 Step 1001 Train Loss: 0.4181
Epoch 1 Step 1051 Train Loss: 0.4818
Epoch 1 Step 1101 Train Loss: 0.5099
Epoch 1 Step 1151 Train Loss: 0.4341
Epoch 1 Step 1201 Train Loss: 0.4367
Epoch 1 Step 1251 Train Loss: 0.4410
Epoch 1 Step 1301 Train Loss: 0.4857
Epoch 1 Step 1351 Train Loss: 0.4495
Epoch 1 Step 1401 Train Loss: 0.4156
Epoch 1 Step 1451 Train Loss: 0.4456
Epoch 1 Step 1501 Train Loss: 0.4420
Epoch 1 Step 1551 Train Loss: 0.4702
Epoch 1: Train Overall MSE: 0.0158 Validation Overall MSE: 0.0187.
Train Top 20 DE MSE: 0.1814 Validation Top 20 DE MSE: 0.3623.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.2644
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.022680882985393207
test_combo_seen0_pearson: 0.94026005
test_combo_seen0_mse_de: 0.2808515052828524
test_combo_seen0_pearson_de: 0.7194697393311394
test_combo_seen1_mse: 0.022799574661740037
test_combo_seen1_pearson: 0.94089705
test_combo_seen1_mse_de: 0.2920649235331735
test_combo_seen1_pearson_de: 0.8012223896072355
test_combo_seen2_mse: 0.025444417456655127
test_combo_seen2_pearson: 0.9342314
test_combo_seen2_mse_de: 0.303746816751204
test_combo_seen2_pearson_de: 0.88581216
test_unseen_single_mse: 0.013440936105325818
test_unseen_single_pearson: 0.9637361
test_unseen_single_mse_de: 0.20636433709619773
test_unseen_single_pearson_de: 0.8718197113937802
test_combo_seen0_pearson_delta: 0.4772653
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.2
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.7333333333333334
test_combo_seen0_mse_top20_de_non_dropout: 0.3369813660780589
test_combo_seen1_pearson_delta: 0.43700573
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.2430232558139535
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.6976744186046512
test_combo_seen1_mse_top20_de_non_dropout: 0.3435234125963477
test_combo_seen2_pearson_delta: 0.4407293
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.18421052631578946
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.7578947368421053
test_combo_seen2_mse_top20_de_non_dropout: 0.308471769486603
test_unseen_single_pearson_delta: 0.3778522
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.24444444444444446
test_unseen_single_frac_sigma_below_1_non_dropout: 0.7930555555555555
test_unseen_single_mse_top20_de_non_dropout: 0.22365701809111568
Done!
2026-10-06 14:31:42,093 INFO lasser.utils: [gears_train] done in 337.4s, peak CUDA memory 0.87 GB
2026-10-06 14:31:42,114 INFO lasser.utils: [evaluate] start
2026-10-06 14:34:43,026 INFO lasser.evaluation: test (eval.py): pearson_delta=0.4212 mse_top20_de=0.2644 nmse_top20_de=4.5249 over 107 perts
2026-10-06 14:34:43,026 INFO lasser.evaluation:   combo_seen0    pearson_delta=0.4773 mse_top20_de=0.2809 (9 perts)
2026-10-06 14:34:43,026 INFO lasser.evaluation:   combo_seen1    pearson_delta=0.4370 mse_top20_de=0.2921 (43 perts)
2026-10-06 14:34:43,027 INFO lasser.evaluation:   combo_seen2    pearson_delta=0.4407 mse_top20_de=0.3037 (19 perts)
2026-10-06 14:34:43,027 INFO lasser.evaluation:   unseen_single  pearson_delta=0.3779 mse_top20_de=0.2064 (36 perts)
2026-10-06 14:34:43,028 INFO lasser.utils: [evaluate] done in 180.9s, peak CUDA memory 1.15 GB
2026-10-06 14:34:43,049 INFO lasser.tracking: appended run aec4ebb6 to /kaggle/working/lasser_tests/runs/runs.csv
{'gsr/data': {'seconds': 0.54, 'peak_cuda_gb': 0.017}, 'gsr/views': {'seconds': 12.2, 'peak_cuda_gb': 0.077}, 'gsr/positives': {'seconds': 5.7, 'peak_cuda_gb': 1.573}, 'gsr/pretrain': {'seconds': 2.13, 'peak_cuda_gb': 0.249}, 'gsr/refine': {'seconds': 0.07, 'peak_cuda_gb': 0.074}, 'gsr/checks': {'seconds': 1.15, 'peak_cuda_gb': 1.145}, 'gsr_graph_from_cache': False, 'gsr_graph': {'seconds': 21.94, 'peak_cuda_gb': 1.145}, 'gears_init': {'seconds': 19.86, 'peak_cuda_gb': 0.044}, 'gears_train': {'seconds': 337.44, 'peak_cuda_gb': 0.872}, 'evaluate': {'seconds': 180.91, 'peak_cuda_gb': 1.154}}
{'graph_learning': True, 'graph_source': 'gsr_refined', 'graph_num_nodes': 5045, 'graph_num_edges': 45192, 'graph_num_self_loops': 4699, 'graph_degree_min': 5, 'graph_degree_median': 7.0, 'graph_degree_mean': 8.026362735381566, 'graph_degree_max': 25, 'graph_degree_gini': 0.20115357700973754, 'graph_isolated_genes': 0, 'test_pearson_delta': 0.42115114319527097, 'test_pearson_delta_top20_de': 0.4993276301824916, 'test_mse_top20_de': 0.26436229187681853, 'test_nmse_top20_de': 4.524884428048819, 'test_nmse_top20_de_ratio_of_means': 0.605163409110387, 'test_frac_opposite_top20_de': 0.41028037383177574, 'test_mse': 0.020110535896687865, 'test_pearson': 0.9473439878948362, 'test_combo_seen0_pearson_delta': 0.4772653344028922, 'test_combo_seen0_mse_top20_de': 0.2808515537116263, 'test_combo_seen0_nmse_top20_de': 10.219844538232133, 'test_combo_seen1_pearson_delta': 0.4370057296296051, 'test_combo_seen1_mse_top20_de': 0.2920649671104065, 'test_combo_seen1_nmse_top20_de': 4.23842911629231, 'test_combo_seen2_pearson_delta': 0.4407293578950115, 'test_combo_seen2_mse_top20_de': 0.30374689400196075, 'test_combo_seen2_nmse_top20_de': 0.5911186982184163, 'test_unseen_single_pearson_delta': 0.3778522260608259, 'test_unseen_single_mse_top20_de': 0.20636435210083923, 'test_unseen_single_nmse_top20_de': 5.51945349140042}
.

=============================== warnings summary ===============================
lasser-repo/tests/test_09_smoke.py::test_smoke_full_norman[False]
lasser-repo/tests/test_09_smoke.py::test_smoke_full_norman[False]
  /usr/local/lib/python3.13/dist-packages/torch/jit/_script.py:1488: DeprecationWarning: `torch.jit.script` is deprecated. Please switch to `torch.compile` or `torch.export`.
    warnings.warn(

lasser-repo/tests/test_09_smoke.py::test_smoke_full_norman[False]

In [5]:
# 4. Load the data once and reuse it for both runs.
from lasser import GSRConfig, LasserConfig, load_pert_data, load_run, run_experiment

common = dict(dataset="norman", seed=1, epochs=1,
              data_dir="/kaggle/working/data", out_dir="/kaggle/working/runs",
              cache_dir="/kaggle/working/cache", repo_dir=REPO_DIR)
pert_data = load_pert_data(LasserConfig(**common))

Found local copy...
Found local copy...
Found local copy...
These perturbations are not in the GO graph and their perturbation can thus not be predicted
['RHOXF2BB+ctrl' 'LYL1+IER5L' 'ctrl+IER5L' 'KIAA1804+ctrl' 'IER5L+ctrl'
 'RHOXF2BB+ZBTB25' 'RHOXF2BB+SET']
Local copy of pyg dataset is detected. Loading...
Done!

In [6]:
# 5. Baseline: graph_learning=False is plain GEARS (plus logging and saving).
base = run_experiment(LasserConfig(**common, graph_learning=False), pert_data)
base["run_dir"]

2026-10-06 14:35:27,974 INFO lasser.tracking: run 87d0540f -> /kaggle/working/runs/norman_seed1_base_20261006-143527
2026-10-06 14:35:28,033 INFO lasser.run: device: cuda:0 (Tesla T4, 14.6 GB) (GEARS training)

Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!

here1
2026-10-06 14:35:28,049 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75.pkl', 'norman_simulation_1_0.75_subgroup.pkl'])
2026-10-06 14:35:28,052 INFO lasser.utils: [gears_init] start

Found local copy...

2026-10-06 14:35:47,451 INFO lasser.utils: [gears_init] done in 19.4s, peak CUDA memory 0.03 GB
2026-10-06 14:35:47,456 INFO lasser.run: co-expression graph used (gears_static): {'num_nodes': 5045, 'num_edges': 6364, 'num_self_loops': 4699, 'degree_min': 0, 'degree_median': 0.0, 'degree_mean': 0.33002973240832506, 'degree_max': 20, 'degree_gini': 0.9324442777762897, 'isolated_genes': 4419}
2026-10-06 14:35:47,457 INFO lasser.run: training GEARS on cuda:0 (Tesla T4, 14.6 GB) for 1 epochs
2026-10-06 14:35:47,458 INFO lasser.utils: [gears_train] start

Start Training...
Epoch 1 Step 1 Train Loss: 0.5244
Epoch 1 Step 51 Train Loss: 0.6099
Epoch 1 Step 101 Train Loss: 0.5167
Epoch 1 Step 151 Train Loss: 0.5267
Epoch 1 Step 201 Train Loss: 0.4575
Epoch 1 Step 251 Train Loss: 0.5969
Epoch 1 Step 301 Train Loss: 0.4178
Epoch 1 Step 351 Train Loss: 0.5540
Epoch 1 Step 401 Train Loss: 0.5095
Epoch 1 Step 451 Train Loss: 0.5325
Epoch 1 Step 501 Train Loss: 0.4450
Epoch 1 Step 551 Train Loss: 0.6025
Epoch 1 Step 601 Train Loss: 0.4668
Epoch 1 Step 651 Train Loss: 0.5007
Epoch 1 Step 701 Train Loss: 0.4617
Epoch 1 Step 751 Train Loss: 0.4461
Epoch 1 Step 801 Train Loss: 0.4754
Epoch 1 Step 851 Train Loss: 0.4256
Epoch 1 Step 901 Train Loss: 0.5404
Epoch 1 Step 951 Train Loss: 0.4250
Epoch 1 Step 1001 Train Loss: 0.4224
Epoch 1 Step 1051 Train Loss: 0.4816
Epoch 1 Step 1101 Train Loss: 0.5083
Epoch 1 Step 1151 Train Loss: 0.4291
Epoch 1 Step 1201 Train Loss: 0.4356
Epoch 1 Step 1251 Train Loss: 0.4418
Epoch 1 Step 1301 Train Loss: 0.4841
Epoch 1 Step 1351 Train Loss: 0.4441
Epoch 1 Step 1401 Train Loss: 0.4192
Epoch 1 Step 1451 Train Loss: 0.4413
Epoch 1 Step 1501 Train Loss: 0.4365
Epoch 1 Step 1551 Train Loss: 0.4760
Epoch 1: Train Overall MSE: 0.0141 Validation Overall MSE: 0.0161.
Train Top 20 DE MSE: 0.2391 Validation Top 20 DE MSE: 0.5049.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.3465
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.022439055144786835
test_combo_seen0_pearson: 0.9400816
test_combo_seen0_mse_de: 0.39577025092310375
test_combo_seen0_pearson_de: 0.6895462407006158
test_combo_seen1_mse: 0.022319436744721824
test_combo_seen1_pearson: 0.9427016
test_combo_seen1_mse_de: 0.3799163730338562
test_combo_seen1_pearson_de: 0.7915426555067994
test_combo_seen2_mse: 0.02322941839596943
test_combo_seen2_pearson: 0.938663
test_combo_seen2_mse_de: 0.4009628425303258
test_combo_seen2_pearson_de: 0.8634963
test_unseen_single_mse: 0.012954659727660732
test_unseen_single_pearson: 0.9644225
test_unseen_single_mse_de: 0.2655936379192604
test_unseen_single_pearson_de: 0.859812812672721
test_combo_seen0_pearson_delta: 0.39248005
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.31666666666666665
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.6777777777777777
test_combo_seen0_mse_top20_de_non_dropout: 0.4796351003977988
test_combo_seen1_pearson_delta: 0.38449132
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.2825581395348838
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.6465116279069767
test_combo_seen1_mse_top20_de_non_dropout: 0.44849494047636207
test_combo_seen2_pearson_delta: 0.40384892
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.23157894736842102
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.7342105263157894
test_combo_seen2_mse_top20_de_non_dropout: 0.40385744171707255
test_unseen_single_pearson_delta: 0.3007774
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.3138888888888889
test_unseen_single_frac_sigma_below_1_non_dropout: 0.7736111111111111
test_unseen_single_mse_top20_de_non_dropout: 0.28669581272535855
Done!

2026-10-06 14:41:28,266 INFO lasser.utils: [gears_train] done in 340.8s, peak CUDA memory 0.87 GB
2026-10-06 14:41:28,290 INFO lasser.utils: [evaluate] start
2026-10-06 14:44:30,497 INFO lasser.evaluation: test (eval.py): pearson_delta=0.3604 mse_top20_de=0.3465 nmse_top20_de=3.9660 over 107 perts
2026-10-06 14:44:30,498 INFO lasser.evaluation:   combo_seen0    pearson_delta=0.3925 mse_top20_de=0.3958 (9 perts)
2026-10-06 14:44:30,499 INFO lasser.evaluation:   combo_seen1    pearson_delta=0.3845 mse_top20_de=0.3799 (43 perts)
2026-10-06 14:44:30,499 INFO lasser.evaluation:   combo_seen2    pearson_delta=0.4038 mse_top20_de=0.4010 (19 perts)
2026-10-06 14:44:30,501 INFO lasser.evaluation:   unseen_single  pearson_delta=0.3008 mse_top20_de=0.2656 (36 perts)
2026-10-06 14:44:30,503 INFO lasser.utils: [evaluate] done in 182.2s, peak CUDA memory 1.15 GB
2026-10-06 14:44:30,529 INFO lasser.tracking: appended run 87d0540f to /kaggle/working/runs/runs.csv

'/kaggle/working/runs/norman_seed1_base_20261006-143527'

In [7]:
# 6. Graph learning: GSR-refined co-expression graph (defaults from the plan, section 11).
gl = run_experiment(LasserConfig(**common, graph_learning=True, gsr=GSRConfig()), pert_data)
gl["run_dir"], gl["checks"]["h2"], gl["checks"]["refine"]

2026-10-06 14:44:30,564 INFO lasser.tracking: run 348393ed -> /kaggle/working/runs/norman_seed1_gl_20261006-144430
2026-10-06 14:44:30,573 INFO lasser.run: device: cuda:0 (Tesla T4, 14.6 GB) (GEARS training and GSR graph learning)

Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!

here1
2026-10-06 14:44:30,589 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75.pkl', 'norman_simulation_1_0.75_subgroup.pkl'])
2026-10-06 14:44:30,591 INFO lasser.utils: [gsr_graph] start
2026-10-06 14:44:30,644 INFO lasser.graph: GSR graph learning on cuda:0 (Tesla T4, 14.6 GB)
2026-10-06 14:44:30,644 INFO lasser.utils: [gsr/data] start
2026-10-06 14:44:31,202 INFO lasser.data: training cells: 49849 (A0 subset 38824, H1 24957, H2 24892) over 138 training perturbations
2026-10-06 14:44:31,203 INFO lasser.utils: [gsr/data] done in 0.6s, peak CUDA memory 0.05 GB
2026-10-06 14:44:31,204 INFO lasser.utils: [gsr/views] start
2026-10-06 14:44:41,634 INFO lasser.data: metacells: 49849 cells -> 500 metacells
2026-10-06 14:44:42,540 INFO lasser.views: view E: dim 64, missing genes 234
2026-10-06 14:44:43,043 INFO lasser.views: view R: dim 32, missing genes 271
2026-10-06 14:44:43,540 INFO lasser.views: deepwalk epoch 1: loss 1.6828 over 1064200 pairs
2026-10-06 14:44:43,848 INFO lasser.views: deepwalk epoch 2: loss 0.0779 over 1064200 pairs
2026-10-06 14:44:44,138 INFO lasser.views: deepwalk epoch 3: loss 0.0568 over 1064200 pairs
2026-10-06 14:44:44,141 INFO lasser.views: view S: dim 64, missing genes 4419
2026-10-06 14:44:44,142 INFO lasser.utils: [gsr/views] done in 12.9s, peak CUDA memory 0.11 GB
2026-10-06 14:44:44,142 INFO lasser.utils: [gsr/positives] start
2026-10-06 14:44:50,138 INFO lasser.pretrain: positives: {'h1_cells_used': 19434, 'candidate_pairs': 1070, 'bootstrap_kept_pairs': 564, 'positive_pairs': 564}
2026-10-06 14:44:50,139 INFO lasser.utils: [gsr/positives] done in 6.0s, peak CUDA memory 1.61 GB
2026-10-06 14:44:50,140 INFO lasser.utils: [gsr/pretrain] start
2026-10-06 14:44:50,164 INFO lasser.pretrain: link AUC of raw view features (baseline): {'E': 0.9703, 'R': 0.8699, 'S': 0.7321, 'combined': 0.9697}
2026-10-06 14:44:50,617 INFO lasser.pretrain: pretrain step 10 (epoch 10): loss 4.6834 intra 4.4926 inter 5.1170 var 0.3473 | AUC {'E': 0.9684, 'R': 0.9665, 'S': 0.2286, 'combined': 0.9879} | cos_std {'E': 0.28, 'R': 0.35, 'S': 0.196}
2026-10-06 14:44:50,974 INFO lasser.pretrain: pretrain step 20 (epoch 20): loss 4.0445 intra 3.8817 inter 4.4139 var 0.2973 | AUC {'E': 0.9672, 'R': 0.9703, 'S': 0.2283, 'combined': 0.9872} | cos_std {'E': 0.313, 'R': 0.319, 'S': 0.296}
2026-10-06 14:44:51,325 INFO lasser.pretrain: pretrain step 30 (epoch 30): loss 3.7153 intra 3.5704 inter 4.0439 var 0.2649 | AUC {'E': 0.9595, 'R': 0.9592, 'S': 0.2436, 'combined': 0.9761} | cos_std {'E': 0.354, 'R': 0.354, 'S': 0.431}
2026-10-06 14:44:51,670 INFO lasser.pretrain: pretrain step 40 (epoch 40): loss 3.3569 intra 3.2225 inter 3.6610 var 0.2474 | AUC {'E': 0.9646, 'R': 0.9617, 'S': 0.2309, 'combined': 0.9799} | cos_std {'E': 0.328, 'R': 0.354, 'S': 0.416}
2026-10-06 14:44:52,054 INFO lasser.pretrain: pretrain step 50 (epoch 50): loss 3.2379 intra 3.1357 inter 3.4527 var 0.2291 | AUC {'E': 0.9707, 'R': 0.9601, 'S': 0.2305, 'combined': 0.9812} | cos_std {'E': 0.304, 'R': 0.343, 'S': 0.461}
2026-10-06 14:44:52,403 INFO lasser.pretrain: pretrain step 60 (epoch 60): loss 3.0071 intra 2.8907 inter 3.2720 var 0.2111 | AUC {'E': 0.9691, 'R': 0.9636, 'S': 0.2443, 'combined': 0.9786} | cos_std {'E': 0.301, 'R': 0.323, 'S': 0.46}
2026-10-06 14:44:52,404 INFO lasser.pretrain: early stop at step 60 (best step 10, AUC 0.9879)
2026-10-06 14:44:52,422 INFO lasser.pretrain: pretraining done: best step 10, held-out link AUC 0.9879 (raw features 0.9697)
2026-10-06 14:44:52,428 INFO lasser.utils: [gsr/pretrain] done in 2.3s, peak CUDA memory 0.28 GB
2026-10-06 14:44:52,429 INFO lasser.utils: [gsr/refine] start
2026-10-06 14:44:52,515 INFO lasser.refine: refinement: {'a0_edges': 6364, 'removed': 20, 'added_directed': 38848, 'topup_directed': 0, 'refined_edges': 45192, 'new_weight_mean': 0.24376694858074188, 'a0_weight_mean': 0.5615240931510925}
2026-10-06 14:44:52,516 INFO lasser.utils: [gsr/refine] done in 0.1s, peak CUDA memory 0.11 GB
2026-10-06 14:44:52,517 INFO lasser.utils: [gsr/checks] start
2026-10-06 14:44:53,753 INFO lasser.checks: graph checks: H2 {'threshold': 0.2, 'hit_rate_added': 0.036, 'hit_rate_added_only': 0.036, 'hit_rate_topup': nan, 'hit_rate_degree_matched_random': 0.002, 'hit_rate_a0': 0.581, 'hit_rate_removed': 0.75, 'passes': True} | coverage {'low_degree_genes': 4935, 'low_degree_mean_degree_a0': 0.16757852077001012, 'low_degree_mean_degree_refined': 8.11631205673759, 'undirected_isolated_a0': 4419, 'undirected_isolated_refined': 0} | jaccard 0.032 | collapse ok True
2026-10-06 14:44:53,757 INFO lasser.utils: [gsr/checks] done in 1.2s, peak CUDA memory 1.18 GB
2026-10-06 14:44:53,861 INFO lasser.graph: GSR graph cached at /kaggle/working/cache/gsr/norman_simulation_seed1_0.75_acff059d6c09
2026-10-06 14:44:53,863 INFO lasser.utils: [gsr_graph] done in 23.3s, peak CUDA memory 1.18 GB
2026-10-06 14:44:53,866 INFO lasser.utils: [gears_init] start

Found local copy...

2026-10-06 14:45:15,146 INFO lasser.utils: [gears_init] done in 21.3s, peak CUDA memory 0.08 GB
2026-10-06 14:45:15,150 INFO lasser.run: co-expression graph used (gsr_refined): {'num_nodes': 5045, 'num_edges': 45192, 'num_self_loops': 4699, 'degree_min': 5, 'degree_median': 7.0, 'degree_mean': 8.026362735381566, 'degree_max': 25, 'degree_gini': 0.20115421336879258, 'isolated_genes': 0}
2026-10-06 14:45:15,246 INFO lasser.run: training GEARS on cuda:0 (Tesla T4, 14.6 GB) for 1 epochs
2026-10-06 14:45:15,247 INFO lasser.utils: [gears_train] start

Start Training...
Epoch 1 Step 1 Train Loss: 0.5244
Epoch 1 Step 51 Train Loss: 0.6158
Epoch 1 Step 101 Train Loss: 0.5137
Epoch 1 Step 151 Train Loss: 0.5235
Epoch 1 Step 201 Train Loss: 0.4555
Epoch 1 Step 251 Train Loss: 0.5953
Epoch 1 Step 301 Train Loss: 0.4119
Epoch 1 Step 351 Train Loss: 0.5401
Epoch 1 Step 401 Train Loss: 0.5129
Epoch 1 Step 451 Train Loss: 0.5277
Epoch 1 Step 501 Train Loss: 0.4399
Epoch 1 Step 551 Train Loss: 0.5978
Epoch 1 Step 601 Train Loss: 0.4604
Epoch 1 Step 651 Train Loss: 0.4946
Epoch 1 Step 701 Train Loss: 0.4586
Epoch 1 Step 751 Train Loss: 0.4558
Epoch 1 Step 801 Train Loss: 0.4740
Epoch 1 Step 851 Train Loss: 0.4229
Epoch 1 Step 901 Train Loss: 0.5446
Epoch 1 Step 951 Train Loss: 0.4253
Epoch 1 Step 1001 Train Loss: 0.4243
Epoch 1 Step 1051 Train Loss: 0.4807
Epoch 1 Step 1101 Train Loss: 0.5051
Epoch 1 Step 1151 Train Loss: 0.4311
Epoch 1 Step 1201 Train Loss: 0.4374
Epoch 1 Step 1251 Train Loss: 0.4474
Epoch 1 Step 1301 Train Loss: 0.4794
Epoch 1 Step 1351 Train Loss: 0.4473
Epoch 1 Step 1401 Train Loss: 0.4183
Epoch 1 Step 1451 Train Loss: 0.4422
Epoch 1 Step 1501 Train Loss: 0.4362
Epoch 1 Step 1551 Train Loss: 0.4721
Epoch 1: Train Overall MSE: 0.0041 Validation Overall MSE: 0.0049.
Train Top 20 DE MSE: 0.1399 Validation Top 20 DE MSE: 0.3268.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.2530
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.006990588114907344
test_combo_seen0_pearson: 0.97976685
test_combo_seen0_mse_de: 0.2542625493887398
test_combo_seen0_pearson_de: 0.7282929950290256
test_combo_seen1_mse: 0.007933117557576922
test_combo_seen1_pearson: 0.97784156
test_combo_seen1_mse_de: 0.27911121350561463
test_combo_seen1_pearson_de: 0.8424886797749719
test_combo_seen2_mse: 0.0071020833167590594
test_combo_seen2_pearson: 0.980295
test_combo_seen2_mse_de: 0.2571525248257737
test_combo_seen2_pearson_de: 0.9015981
test_unseen_single_mse: 0.003698032468997149
test_unseen_single_pearson: 0.9890531
test_unseen_single_mse_de: 0.21930646920938873
test_unseen_single_pearson_de: 0.8703506539265314
test_combo_seen0_pearson_delta: 0.5221685
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.16666666666666666
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.7722222222222223
test_combo_seen0_mse_top20_de_non_dropout: 0.3452184804611736
test_combo_seen1_pearson_delta: 0.47696865
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.20813953488372094
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.7104651162790697
test_combo_seen1_mse_top20_de_non_dropout: 0.3494030802055847
test_combo_seen2_pearson_delta: 0.5230436
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.12631578947368421
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.7947368421052633
test_combo_seen2_mse_top20_de_non_dropout: 0.27056925037973806
test_unseen_single_pearson_delta: 0.37745485
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.24861111111111114
test_unseen_single_frac_sigma_below_1_non_dropout: 0.8444444444444446
test_unseen_single_mse_top20_de_non_dropout: 0.23809112453212342
Done!

2026-10-06 14:50:58,995 INFO lasser.utils: [gears_train] done in 343.7s, peak CUDA memory 0.91 GB
2026-10-06 14:50:59,020 INFO lasser.utils: [evaluate] start
2026-10-06 14:54:02,662 INFO lasser.evaluation: test (eval.py): pearson_delta=0.4555 mse_top20_de=0.2530 nmse_top20_de=1.4229 over 107 perts
2026-10-06 14:54:02,663 INFO lasser.evaluation:   combo_seen0    pearson_delta=0.5222 mse_top20_de=0.2543 (9 perts)
2026-10-06 14:54:02,664 INFO lasser.evaluation:   combo_seen1    pearson_delta=0.4770 mse_top20_de=0.2791 (43 perts)
2026-10-06 14:54:02,664 INFO lasser.evaluation:   combo_seen2    pearson_delta=0.5230 mse_top20_de=0.2572 (19 perts)
2026-10-06 14:54:02,665 INFO lasser.evaluation:   unseen_single  pearson_delta=0.3775 mse_top20_de=0.2193 (36 perts)
2026-10-06 14:54:02,667 INFO lasser.utils: [evaluate] done in 183.6s, peak CUDA memory 1.19 GB
2026-10-06 14:54:02,699 INFO lasser.tracking: appended run 348393ed to /kaggle/working/runs/runs.csv

('/kaggle/working/runs/norman_seed1_gl_20261006-144430',
 {'threshold': 0.2,
  'hit_rate_added': 0.03598640859127045,
  'hit_rate_added_only': 0.03598640859127045,
  'hit_rate_topup': nan,
  'hit_rate_degree_matched_random': 0.0016478706384077668,
  'hit_rate_a0': 0.5806451439857483,
  'hit_rate_removed': 0.75,
  'passes': True},
 {'a0_edges': 6364,
  'removed': 20,
  'added_directed': 38848,
  'topup_directed': 0,
  'refined_edges': 45192,
  'new_weight_mean': 0.24376694858074188,
  'a0_weight_mean': 0.5615240931510925})

In [8]:
# 7. Results: the global run table, and any past run loaded back.
import pandas as pd
pd.set_option("display.max_columns", 200)
runs = pd.read_csv("/kaggle/working/runs/runs.csv")
cols = ["run_id", "seed", "graph_learning", "gsr_init_gene_emb", "graph_num_edges", "graph_isolated_genes",
        "test_pearson_delta", "test_mse_top20_de", "test_nmse_top20_de",
        "test_unseen_single_pearson_delta", "test_combo_seen0_pearson_delta",
        "test_combo_seen1_pearson_delta", "test_combo_seen2_pearson_delta", "run_dir"]
display(runs[[c for c in cols if c in runs.columns]])

r = load_run(gl["run_dir"])
display(r["epoch_log"])
r["test_metrics"]["paper"]["subgroups"]

,run_id,seed,graph_learning,gsr_init_gene_emb,graph_num_edges,graph_isolated_genes,test_pearson_delta,test_mse_top20_de,test_nmse_top20_de,test_unseen_single_pearson_delta,test_combo_seen0_pearson_delta,test_combo_seen1_pearson_delta,test_combo_seen2_pearson_delta,run_dir
0,87d0540f,1,False,False,6364,4419,0.360435,0.346523,3.965999,0.300777,0.392480,0.384491,0.403849,/kaggle/working/runs/norman_seed1_base_2026100...
1,348393ed,1,True,False,45192,0,0.455471,0.253001,1.422869,0.377455,0.522169,0.476969,0.523044,/kaggle/working/runs/norman_seed1_gl_20261006-...

,epoch,train_mse,val_mse,train_mse_de,val_mse_de,train_loss_logged_mean,n_logged_steps,is_best
0,1,0.0041,0.0049,0.1399,0.3268,0.481756,32,True

{'combo_seen0': {'n_perts': 9,
  'mse': 0.00699058821838763,
  'pearson': 0.9797668706798578,
  'mse_top20_de': 0.2542625818815496,
  'mse_top20_de_noperturb': 0.3686102908104658,
  'nmse_top20_de': 3.2012983379161843,
  'pearson_top20_de': 0.7282930362177019,
  'pearson_delta': 0.5221685088247261,
  'pearson_delta_top20_de': 0.40766366227369755,
  'frac_opposite_top20_de': 0.5388888888888889,
  'frac_correct_direction_top20_de': 0.46111111111111114,
  'nmse_top20_de_ratio_of_means': 0.6897869870168324},
 'combo_seen1': {'n_perts': 43,
  'mse': 0.007933117530503592,
  'pearson': 0.9778415929983577,
  'mse_top20_de': 0.2791112255911494,
  'mse_top20_de_noperturb': 0.48487508398762275,
  'nmse_top20_de': 1.625126437932775,
  'pearson_top20_de': 0.8424886669466133,
  'pearson_delta': 0.47696869114012164,
  'pearson_delta_top20_de': 0.5781047782492842,
  'frac_opposite_top20_de': 0.4011627906976744,
  'frac_correct_direction_top20_de': 0.5988372093023255,
  'nmse_top20_de_ratio_of_means': 0.5756353230108937},
 'combo_seen2': {'n_perts': 19,
  'mse': 0.007102083745657613,
  'pearson': 0.980295025101257,
  'mse_top20_de': 0.25715234875679016,
  'mse_top20_de_noperturb': 0.6160734672295419,
  'nmse_top20_de': 0.49386232097882593,
  'pearson_top20_de': 0.9015981507832234,
  'pearson_delta': 0.5230435043990426,
  'pearson_delta_top20_de': 0.7439264355982271,
  'frac_opposite_top20_de': 0.18947368421052632,
  'frac_correct_direction_top20_de': 0.8105263157894737,
  'nmse_top20_de_ratio_of_means': 0.41740532977859623},
 'unseen_single': {'n_perts': 36,
  'mse': 0.0036980325530748814,
  'pearson': 0.9890530725010898,
  'mse_top20_de': 0.2193064794021969,
  'mse_top20_de_noperturb': 0.3019400484085458,
  'nmse_top20_de': 1.2269843309871733,
  'pearson_top20_de': 0.8703506231597731,
  'pearson_delta': 0.3774548408978671,
  'pearson_delta_top20_de': 0.4897242684607044,
  'frac_opposite_top20_de': 0.4138888888888888,
  'frac_correct_direction_top20_de': 0.586111111111111,
  'nmse_top20_de_ratio_of_means': 0.7263245818436779}}