# LASSER on Kaggle

GEARS with an optional GSR-style learned co-expression graph. Needs **Internet on** (GEARS downloads Norman and the GO graph from Harvard Dataverse) and a **GPU (T4)**.

Cells: install, get the code, run the tests (before any real training), baseline run, graph-learning run, results.

In [1]:
# 1. Dependencies. GEARS is vendored inside lasser/ (lasser/gears), so no cell-gears install.
#    Kaggle already has torch, numpy, pandas, scipy, scikit-learn, networkx, tqdm, requests.
!pip install -q torch_geometric scanpy pytest

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 25.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 61.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.2/190.2 kB 10.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.1/79.1 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 376.9/376.9 kB 19.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 230.5/230.5 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 59.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.4/69.4 kB 2.3 MB/s eta 0:00:00

In [2]:
# 2. Get the code: clone, then move the self-contained package next to the notebook.
REPO_URL = "https://github.com/LegendaryDarkKnight/LASSER"   # <- set this
REPO_DIR = "/kaggle/working/lasser-repo"
!rm -rf {REPO_DIR} /kaggle/working/lasser
!git clone -q {REPO_URL} {REPO_DIR}
!mv {REPO_DIR}/lasser /kaggle/working/lasser
!git -C {REPO_DIR} log -1 --oneline

02a13c9 (HEAD -> main, origin/main, origin/HEAD) fix: format issue fixing

In [3]:
# 3. Tests 1-8 (tiny subsets; first run also downloads Norman, ~10-20 min in total).
%env LASSER_DATA_DIR=/kaggle/working/data
%env LASSER_TEST_DIR=/kaggle/working/lasser_tests
!cd /kaggle/working && python -m pytest {REPO_DIR}/tests -m "not smoke" -p no:cacheprovider -rA -s --tb=short 2>&1 | tee /kaggle/working/test_output.txt | grep -vE "it/s\]|s/it\]"

env: LASSER_DATA_DIR=/kaggle/working/data
env: LASSER_TEST_DIR=/kaggle/working/lasser_tests
============================= test session starts ==============================
platform linux -- Python 3.13.15, pytest-8.4.2, pluggy-1.6.0
rootdir: /kaggle/working
plugins: fast-array-utils-1.5.1, zarr-3.4.0, typeguard-4.6.0, anyio-4.14.2, langsmith-0.12.1
collected 16 items

lasser-repo/tests/test_00_packaging.py ..lasser modules loaded: ['lasser', 'lasser._eval', 'lasser.config', 'lasser.evaluation', 'lasser.gears', 'lasser.gears.data_utils', 'lasser.gears.gears', 'lasser.gears.inference', 'lasser.gears.model', 'lasser.gears.pertdata', 'lasser.gears.utils', 'lasser.gears.version', 'lasser.run', 'lasser.tracking', 'lasser.utils']
.
lasser-repo/tests/test_01_parity.py Found local copy...
Found local copy...
Found local copy...
These perturbations are not in the GO graph and their perturbation can thus not be predicted
['RHOXF2BB+ctrl' 'LYL1+IER5L' 'ctrl+IER5L' 'KIAA1804+ctrl' 'IER5L+ctrl'
 'RHOXF2BB+ZBTB25' 'RHOXF2BB+SET']
Local copy of pyg dataset is detected. Loading...
Done!
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
Found local copy...
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
Found local copy...
here1
here1
co-expression graph: 6364 edges
.Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
Found local copy...
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
Found local copy...
here1
here1
losses lasser: [0.5793299674987793, 0.4777032434940338, 0.45405393838882446, 0.5027831196784973, 0.5451818108558655]
losses GEARS:  [0.5793299674987793, 0.4777032434940338, 0.45405393838882446, 0.5027831196784973, 0.5451818108558655]
.2026-10-06 15:13:09,606 INFO lasser.tracking: run 3cc11e87 -> /kaggle/working/lasser_tests/runs/norman_seed1_base_20261006-151309_parity
2026-10-06 15:13:09,613 INFO lasser.run: device: cpu (GEARS training)
2026-10-06 15:13:09,613 WARNING lasser.run: running on CPU although CUDA is available (cfg.device='cpu')
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
here1
2026-10-06 15:13:09,619 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75_subgroup.pkl', 'norman_simulation_1_0.75.pkl'])
2026-10-06 15:13:09,621 INFO lasser.utils: [gears_init] start
Found local copy...
2026-10-06 15:13:28,597 INFO lasser.utils: [gears_init] done in 19.0s, peak CUDA memory 0.00 GB
2026-10-06 15:13:28,605 INFO lasser.run: co-expression graph used (gears_static): {'num_nodes': 5045, 'num_edges': 6364, 'num_self_loops': 4699, 'degree_min': 0, 'degree_median': 0.0, 'degree_mean': 0.33002973240832506, 'degree_max': 20, 'degree_gini': 0.9324442777762897, 'isolated_genes': 4419}
2026-10-06 15:13:28,605 INFO lasser.run: training GEARS on cpu for 1 epochs
2026-10-06 15:13:28,605 INFO lasser.utils: [gears_train] start
Start Training...
Epoch 1 Step 1 Train Loss: 0.5596
Epoch 1: Train Overall MSE: 0.0229 Validation Overall MSE: 0.0230.
Train Top 20 DE MSE: 0.4800 Validation Top 20 DE MSE: 0.5874.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.5992
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.02995357538263003
test_combo_seen0_pearson: 0.9144783
test_combo_seen0_mse_de: 0.4623212884180248
test_combo_seen0_pearson_de: 0.6718298064337836
test_combo_seen1_mse: 0.030566621398509936
test_combo_seen1_pearson: 0.9133015
test_combo_seen1_mse_de: 0.6131469777942267
test_combo_seen1_pearson_de: 0.6955304116357205
test_combo_seen2_mse: 0.027026572215713952
test_combo_seen2_pearson: 0.92176104
test_combo_seen2_mse_de: 0.8015641824979531
test_combo_seen2_pearson_de: 0.7347194
test_unseen_single_mse: 0.02360451454296708
test_unseen_single_pearson: 0.9316064
test_unseen_single_mse_de: 0.5100661712090692
test_unseen_single_pearson_de: 0.7765138890180323
test_combo_seen0_pearson_delta: 0.025264971
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.4888888888888888
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.3528265107212476
test_combo_seen0_mse_top20_de_non_dropout: 0.8610302640332116
test_combo_seen1_pearson_delta: -0.014741777
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.5127906976744186
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.391738390268702
test_combo_seen1_mse_top20_de_non_dropout: 0.8670923175333545
test_combo_seen2_pearson_delta: -0.017429557
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.5078947368421052
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.4152202965140883
test_combo_seen2_mse_top20_de_non_dropout: 0.8496585033441845
test_unseen_single_pearson_delta: -0.035758734
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.5430555555555556
test_unseen_single_frac_sigma_below_1_non_dropout: 0.47431203963066715
test_unseen_single_mse_top20_de_non_dropout: 0.5942009387330877
Done!
2026-10-06 15:15:36,155 INFO lasser.utils: [gears_train] done in 127.5s, peak CUDA memory 0.00 GB
2026-10-06 15:15:36,176 INFO lasser.utils: [evaluate] start
2026-10-06 15:15:53,871 INFO lasser.evaluation: test (eval.py): pearson_delta=-0.0189 mse_top20_de=0.5992 nmse_top20_de=1.7795 over 107 perts
2026-10-06 15:15:53,872 INFO lasser.evaluation:   combo_seen0    pearson_delta=0.0253 mse_top20_de=0.4623 (9 perts)
2026-10-06 15:15:53,872 INFO lasser.evaluation:   combo_seen1    pearson_delta=-0.0147 mse_top20_de=0.6131 (43 perts)
2026-10-06 15:15:53,872 INFO lasser.evaluation:   combo_seen2    pearson_delta=-0.0174 mse_top20_de=0.8016 (19 perts)
2026-10-06 15:15:53,872 INFO lasser.evaluation:   unseen_single  pearson_delta=-0.0358 mse_top20_de=0.5101 (36 perts)
2026-10-06 15:15:53,873 INFO lasser.utils: [evaluate] done in 17.7s, peak CUDA memory 0.00 GB
2026-10-06 15:15:53,889 INFO lasser.tracking: appended run 3cc11e87 to /kaggle/working/lasser_tests/runs/runs.csv
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
Found local copy...
Start Training...
Epoch 1 Step 1 Train Loss: 0.5596
Epoch 1: Train Overall MSE: 0.0229 Validation Overall MSE: 0.0230.
Train Top 20 DE MSE: 0.4800 Validation Top 20 DE MSE: 0.5874.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.5992
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.02995357538263003
test_combo_seen0_pearson: 0.9144783
test_combo_seen0_mse_de: 0.4623212884180248
test_combo_seen0_pearson_de: 0.6718298064337836
test_combo_seen1_mse: 0.030566621398509936
test_combo_seen1_pearson: 0.9133015
test_combo_seen1_mse_de: 0.6131469777942267
test_combo_seen1_pearson_de: 0.6955304116357205
test_combo_seen2_mse: 0.027026572215713952
test_combo_seen2_pearson: 0.92176104
test_combo_seen2_mse_de: 0.8015641824979531
test_combo_seen2_pearson_de: 0.7347194
test_unseen_single_mse: 0.02360451454296708
test_unseen_single_pearson: 0.9316064
test_unseen_single_mse_de: 0.5100661712090692
test_unseen_single_pearson_de: 0.7765138890180323
test_combo_seen0_pearson_delta: 0.025264971
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.4888888888888888
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.3528265107212476
test_combo_seen0_mse_top20_de_non_dropout: 0.8610302640332116
test_combo_seen1_pearson_delta: -0.014741777
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.5127906976744186
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.391738390268702
test_combo_seen1_mse_top20_de_non_dropout: 0.8670923175333545
test_combo_seen2_pearson_delta: -0.017429557
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.5078947368421052
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.4152202965140883
test_combo_seen2_mse_top20_de_non_dropout: 0.8496585033441845
test_unseen_single_pearson_delta: -0.035758734
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.5430555555555556
test_unseen_single_frac_sigma_below_1_non_dropout: 0.47431203963066715
test_unseen_single_mse_top20_de_non_dropout: 0.5942009387330877
Done!
here1
.
lasser-repo/tests/test_02_graphs.py 2026-10-06 15:18:24,379 INFO lasser.tracking: run 5bb0cdf8 -> /kaggle/working/lasser_tests/runs/norman_seed1_base_20261006-151824_test
2026-10-06 15:18:24,386 INFO lasser.run: device: cuda:0 (Tesla T4, 14.6 GB) (GEARS training)
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
here1
2026-10-06 15:18:24,391 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75_subgroup.pkl', 'norman_simulation_1_0.75.pkl'])
2026-10-06 15:18:24,393 INFO lasser.utils: [gears_init] start
Found local copy...
2026-10-06 15:18:44,985 INFO lasser.utils: [gears_init] done in 20.6s, peak CUDA memory 0.03 GB
2026-10-06 15:18:44,988 INFO lasser.run: co-expression graph used (gears_static): {'num_nodes': 5045, 'num_edges': 6364, 'num_self_loops': 4699, 'degree_min': 0, 'degree_median': 0.0, 'degree_mean': 0.33002973240832506, 'degree_max': 20, 'degree_gini': 0.9324442777762897, 'isolated_genes': 4419}
2026-10-06 15:18:44,988 INFO lasser.run: training GEARS on cuda:0 (Tesla T4, 14.6 GB) for 1 epochs
2026-10-06 15:18:44,988 INFO lasser.utils: [gears_train] start
Start Training...
Epoch 1 Step 1 Train Loss: 0.5596
Epoch 1: Train Overall MSE: 0.0230 Validation Overall MSE: 0.0230.
Train Top 20 DE MSE: 0.4801 Validation Top 20 DE MSE: 0.5878.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.5993
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.02996632643043995
test_combo_seen0_pearson: 0.9144322
test_combo_seen0_mse_de: 0.4625143796309001
test_combo_seen0_pearson_de: 0.6717264917161729
test_combo_seen1_mse: 0.03057389294858589
test_combo_seen1_pearson: 0.91327226
test_combo_seen1_mse_de: 0.6132611111618665
test_combo_seen1_pearson_de: 0.6956092126147692
test_combo_seen2_mse: 0.027035597515733617
test_combo_seen2_pearson: 0.92172825
test_combo_seen2_mse_de: 0.8016995595473992
test_combo_seen2_pearson_de: 0.7346539
test_unseen_single_mse: 0.0236158084589988
test_unseen_single_pearson: 0.9315668
test_unseen_single_mse_de: 0.5099501771878244
test_unseen_single_pearson_de: 0.7764867506921291
test_combo_seen0_pearson_delta: 0.025164753
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.4888888888888888
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.3528265107212476
test_combo_seen0_mse_top20_de_non_dropout: 0.8612517697943581
test_combo_seen1_pearson_delta: -0.01461498
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.5139534883720931
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.39310637932478953
test_combo_seen1_mse_top20_de_non_dropout: 0.8670332329564316
test_combo_seen2_pearson_delta: -0.017309885
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.5078947368421052
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.4152202965140883
test_combo_seen2_mse_top20_de_non_dropout: 0.8497666089158309
test_unseen_single_pearson_delta: -0.035721947
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.5416666666666665
test_unseen_single_frac_sigma_below_1_non_dropout: 0.47431203963066715
test_unseen_single_mse_top20_de_non_dropout: 0.594056456660231
Done!
2026-10-06 15:19:50,036 INFO lasser.utils: [gears_train] done in 65.0s, peak CUDA memory 0.92 GB
2026-10-06 15:19:50,056 INFO lasser.utils: [evaluate] start
2026-10-06 15:19:53,151 INFO lasser.evaluation: test (eval.py): pearson_delta=-0.0188 mse_top20_de=0.5993 nmse_top20_de=1.7827 over 107 perts
2026-10-06 15:19:53,151 INFO lasser.evaluation:   combo_seen0    pearson_delta=0.0252 mse_top20_de=0.4625 (9 perts)
2026-10-06 15:19:53,151 INFO lasser.evaluation:   combo_seen1    pearson_delta=-0.0146 mse_top20_de=0.6133 (43 perts)
2026-10-06 15:19:53,152 INFO lasser.evaluation:   combo_seen2    pearson_delta=-0.0173 mse_top20_de=0.8017 (19 perts)
2026-10-06 15:19:53,152 INFO lasser.evaluation:   unseen_single  pearson_delta=-0.0357 mse_top20_de=0.5100 (36 perts)
2026-10-06 15:19:53,152 INFO lasser.utils: [evaluate] done in 3.1s, peak CUDA memory 1.19 GB
2026-10-06 15:19:53,172 INFO lasser.tracking: appended run 5bb0cdf8 to /kaggle/working/lasser_tests/runs/runs.csv
2026-10-06 15:19:53,173 INFO lasser.tracking: run bc272560 -> /kaggle/working/lasser_tests/runs/norman_seed1_gl_20261006-151953_test
2026-10-06 15:19:53,179 INFO lasser.run: device: cuda:0 (Tesla T4, 14.6 GB) (GEARS training and GSR graph learning)
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
here1
2026-10-06 15:19:53,183 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75_subgroup.pkl', 'norman_simulation_1_0.75.pkl'])
2026-10-06 15:19:53,183 INFO lasser.utils: [gsr_graph] start
2026-10-06 15:19:53,248 INFO lasser.graph: GSR graph learning on cuda:0 (Tesla T4, 14.6 GB)
2026-10-06 15:19:53,248 INFO lasser.utils: [gsr/data] start
2026-10-06 15:19:53,805 INFO lasser.data: training cells: 49849 (A0 subset 38824, H1 24957, H2 24892) over 138 training perturbations
2026-10-06 15:19:53,806 INFO lasser.utils: [gsr/data] done in 0.6s, peak CUDA memory 0.10 GB
2026-10-06 15:19:53,807 INFO lasser.utils: [gsr/views] start
2026-10-06 15:20:01,359 INFO lasser.data: metacells: 49849 cells -> 200 metacells
2026-10-06 15:20:01,423 INFO lasser.views: view E: dim 64, missing genes 234
2026-10-06 15:20:01,883 INFO lasser.views: view R: dim 32, missing genes 271
2026-10-06 15:20:02,166 INFO lasser.views: deepwalk epoch 1: loss 3.3745 over 425680 pairs
2026-10-06 15:20:02,168 INFO lasser.views: view S: dim 64, missing genes 4419
2026-10-06 15:20:02,169 INFO lasser.utils: [gsr/views] done in 8.4s, peak CUDA memory 0.16 GB
2026-10-06 15:20:02,169 INFO lasser.utils: [gsr/positives] start
2026-10-06 15:20:02,654 INFO lasser.pretrain: positives: {'h1_cells_used': 3000, 'candidate_pairs': 2920, 'bootstrap_kept_pairs': 781, 'positive_pairs': 781}
2026-10-06 15:20:02,654 INFO lasser.utils: [gsr/positives] done in 0.5s, peak CUDA memory 0.55 GB
2026-10-06 15:20:02,655 INFO lasser.utils: [gsr/pretrain] start
2026-10-06 15:20:02,747 INFO lasser.pretrain: link AUC of raw view features (baseline): {'E': 0.872, 'R': 0.7326, 'S': 0.3077, 'combined': 0.8342}
2026-10-06 15:20:03,465 INFO lasser.pretrain: pretrain step 5 (epoch 5): loss 5.1660 intra 5.0155 inter 5.4209 var 0.4919 | AUC {'E': 0.9602, 'R': 0.9303, 'S': 0.273, 'combined': 0.9555} | cos_std {'E': 0.254, 'R': 0.211, 'S': 0.151}
2026-10-06 15:20:03,787 INFO lasser.pretrain: pretrain step 10 (epoch 10): loss 5.0392 intra 4.9192 inter 5.2740 var 0.3122 | AUC {'E': 0.9372, 'R': 0.9412, 'S': 0.3072, 'combined': 0.9482} | cos_std {'E': 0.289, 'R': 0.312, 'S': 0.479}
2026-10-06 15:20:04,059 INFO lasser.pretrain: pretrain step 15 (epoch 15): loss 4.7241 intra 4.5879 inter 5.0259 var 0.2668 | AUC {'E': 0.9568, 'R': 0.9472, 'S': 0.2755, 'combined': 0.961} | cos_std {'E': 0.289, 'R': 0.32, 'S': 0.567}
2026-10-06 15:20:04,372 INFO lasser.pretrain: pretrain step 20 (epoch 20): loss 4.6737 intra 4.5636 inter 4.9065 var 0.2432 | AUC {'E': 0.9518, 'R': 0.9415, 'S': 0.2914, 'combined': 0.9578} | cos_std {'E': 0.322, 'R': 0.349, 'S': 0.559}
2026-10-06 15:20:04,395 INFO lasser.pretrain: pretraining done: best step 15, held-out link AUC 0.9610 (raw features 0.8342)
2026-10-06 15:20:04,402 INFO lasser.utils: [gsr/pretrain] done in 1.7s, peak CUDA memory 0.35 GB
2026-10-06 15:20:04,402 INFO lasser.utils: [gsr/refine] start
2026-10-06 15:20:04,532 INFO lasser.refine: refinement: {'a0_edges': 6364, 'removed': 20, 'added_directed': 38035, 'topup_directed': 0, 'refined_edges': 44379, 'new_weight_mean': 0.2686493694782257, 'a0_weight_mean': 0.5615240931510925}
2026-10-06 15:20:04,533 INFO lasser.utils: [gsr/refine] done in 0.1s, peak CUDA memory 0.15 GB
2026-10-06 15:20:04,533 INFO lasser.utils: [gsr/checks] start
2026-10-06 15:20:04,957 INFO lasser.checks: graph checks: H2 {'threshold': 0.2, 'hit_rate_added': 0.034, 'hit_rate_added_only': 0.034, 'hit_rate_topup': nan, 'hit_rate_degree_matched_random': 0.002, 'hit_rate_a0': 0.387, 'hit_rate_removed': 0.75, 'passes': True} | coverage {'low_degree_genes': 4935, 'low_degree_mean_degree_a0': 0.16757852077001012, 'low_degree_mean_degree_refined': 7.931509625126647, 'undirected_isolated_a0': 4419, 'undirected_isolated_refined': 0} | jaccard 0.030 | collapse ok True
2026-10-06 15:20:04,961 INFO lasser.utils: [gsr/checks] done in 0.4s, peak CUDA memory 0.40 GB
2026-10-06 15:20:05,053 INFO lasser.graph: GSR graph cached at /kaggle/working/lasser_tests/cache/gsr/norman_simulation_seed1_0.75_1729bcfa8982
2026-10-06 15:20:05,054 INFO lasser.utils: [gsr_graph] done in 11.9s, peak CUDA memory 0.40 GB
2026-10-06 15:20:05,055 INFO lasser.utils: [gears_init] start
Found local copy...
2026-10-06 15:20:24,001 INFO lasser.utils: [gears_init] done in 18.9s, peak CUDA memory 0.13 GB
2026-10-06 15:20:24,004 INFO lasser.run: co-expression graph used (gsr_refined): {'num_nodes': 5045, 'num_edges': 44379, 'num_self_loops': 4699, 'degree_min': 5, 'degree_median': 7.0, 'degree_mean': 7.865213082259663, 'degree_max': 25, 'degree_gini': 0.20170333930112855, 'isolated_genes': 0}
2026-10-06 15:20:24,092 INFO lasser.run: training GEARS on cuda:0 (Tesla T4, 14.6 GB) for 1 epochs
2026-10-06 15:20:24,093 INFO lasser.utils: [gears_train] start
Start Training...
Epoch 1 Step 1 Train Loss: 0.5596
Epoch 1: Train Overall MSE: 0.0229 Validation Overall MSE: 0.0230.
Train Top 20 DE MSE: 0.4785 Validation Top 20 DE MSE: 0.5859.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.5968
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.02988782214621703
test_combo_seen0_pearson: 0.91463375
test_combo_seen0_mse_de: 0.46051357293294537
test_combo_seen0_pearson_de: 0.6720408134990268
test_combo_seen1_mse: 0.030510763269524243
test_combo_seen1_pearson: 0.91343874
test_combo_seen1_mse_de: 0.6108034900633271
test_combo_seen1_pearson_de: 0.696712123273417
test_combo_seen2_mse: 0.026986997574567795
test_combo_seen2_pearson: 0.92186767
test_combo_seen2_mse_de: 0.7986275675265413
test_combo_seen2_pearson_de: 0.7354578
test_unseen_single_mse: 0.023585067053015035
test_unseen_single_pearson: 0.93165714
test_unseen_single_mse_de: 0.5077298168907873
test_unseen_single_pearson_de: 0.7771336622536182
test_combo_seen0_pearson_delta: 0.027333865
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.5
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.3528265107212476
test_combo_seen0_mse_top20_de_non_dropout: 0.8576094640625848
test_combo_seen1_pearson_delta: -0.012564907
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.5139534883720931
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.3904901002550222
test_combo_seen1_mse_top20_de_non_dropout: 0.863247967650031
test_combo_seen2_pearson_delta: -0.015206016
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.5052631578947367
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.41831627174628644
test_combo_seen2_mse_top20_de_non_dropout: 0.8465563090224015
test_unseen_single_pearson_delta: -0.034414716
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.538888888888889

In [4]:
# 3b. Optional test 9: full Norman, 1 epoch, flag off and on, checks the T4 memory budget.
%env LASSER_SMOKE=1
!cd /kaggle/working && python -m pytest {REPO_DIR}/tests/test_09_smoke.py -p no:cacheprovider -rA -s --tb=short 2>&1 | tee /kaggle/working/smoke_output.txt | grep -vE "it/s\]|s/it\]"
%env LASSER_SMOKE=0

env: LASSER_SMOKE=1
============================= test session starts ==============================
platform linux -- Python 3.13.15, pytest-8.4.2, pluggy-1.6.0
rootdir: /kaggle/working
plugins: fast-array-utils-1.5.1, zarr-3.4.0, typeguard-4.6.0, anyio-4.14.2, langsmith-0.12.1
collected 2 items

lasser-repo/tests/test_09_smoke.py Found local copy...
Found local copy...
Found local copy...
These perturbations are not in the GO graph and their perturbation can thus not be predicted
['RHOXF2BB+ctrl' 'LYL1+IER5L' 'ctrl+IER5L' 'KIAA1804+ctrl' 'IER5L+ctrl'
 'RHOXF2BB+ZBTB25' 'RHOXF2BB+SET']
Local copy of pyg dataset is detected. Loading...
Done!
2026-10-06 15:23:31,023 INFO lasser.tracking: run 84c27427 -> /kaggle/working/lasser_tests/runs/norman_seed1_base_20261006-152331_smoke
2026-10-06 15:23:31,091 INFO lasser.run: device: cuda:0 (Tesla T4, 14.6 GB) (GEARS training)
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
here1
2026-10-06 15:23:31,098 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75_subgroup.pkl', 'norman_simulation_1_0.75.pkl'])
2026-10-06 15:23:31,100 INFO lasser.utils: [gears_init] start
Found local copy...
2026-10-06 15:23:50,813 INFO lasser.utils: [gears_init] done in 19.7s, peak CUDA memory 0.03 GB
2026-10-06 15:23:50,817 INFO lasser.run: co-expression graph used (gears_static): {'num_nodes': 5045, 'num_edges': 6364, 'num_self_loops': 4699, 'degree_min': 0, 'degree_median': 0.0, 'degree_mean': 0.33002973240832506, 'degree_max': 20, 'degree_gini': 0.9324442777762897, 'isolated_genes': 4419}
2026-10-06 15:23:50,817 INFO lasser.run: training GEARS on cuda:0 (Tesla T4, 14.6 GB) for 1 epochs
2026-10-06 15:23:50,817 INFO lasser.utils: [gears_train] start
Start Training...
Epoch 1 Step 1 Train Loss: 0.5244
Epoch 1 Step 51 Train Loss: 0.6175
Epoch 1 Step 101 Train Loss: 0.5186
Epoch 1 Step 151 Train Loss: 0.5114
Epoch 1 Step 201 Train Loss: 0.4612
Epoch 1 Step 251 Train Loss: 0.6100
Epoch 1 Step 301 Train Loss: 0.4120
Epoch 1 Step 351 Train Loss: 0.5508
Epoch 1 Step 401 Train Loss: 0.5083
Epoch 1 Step 451 Train Loss: 0.5234
Epoch 1 Step 501 Train Loss: 0.4428
Epoch 1 Step 551 Train Loss: 0.6181
Epoch 1 Step 601 Train Loss: 0.4654
Epoch 1 Step 651 Train Loss: 0.4976
Epoch 1 Step 701 Train Loss: 0.4630
Epoch 1 Step 751 Train Loss: 0.4446
Epoch 1 Step 801 Train Loss: 0.4780
Epoch 1 Step 851 Train Loss: 0.4312
Epoch 1 Step 901 Train Loss: 0.5393
Epoch 1 Step 951 Train Loss: 0.4282
Epoch 1 Step 1001 Train Loss: 0.4214
Epoch 1 Step 1051 Train Loss: 0.4824
Epoch 1 Step 1101 Train Loss: 0.5048
Epoch 1 Step 1151 Train Loss: 0.4327
Epoch 1 Step 1201 Train Loss: 0.4347
Epoch 1 Step 1251 Train Loss: 0.4447
Epoch 1 Step 1301 Train Loss: 0.4770
Epoch 1 Step 1351 Train Loss: 0.4489
Epoch 1 Step 1401 Train Loss: 0.4231
Epoch 1 Step 1451 Train Loss: 0.4433
Epoch 1 Step 1501 Train Loss: 0.4457
Epoch 1 Step 1551 Train Loss: 0.4773
Epoch 1: Train Overall MSE: 0.0164 Validation Overall MSE: 0.0188.
Train Top 20 DE MSE: 0.2471 Validation Top 20 DE MSE: 0.5237.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.3667
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.02831564222772916
test_combo_seen0_pearson: 0.92565984
test_combo_seen0_mse_de: 0.4422735530469153
test_combo_seen0_pearson_de: 0.6739733219146729
test_combo_seen1_mse: 0.026709485820732837
test_combo_seen1_pearson: 0.9329899
test_combo_seen1_mse_de: 0.41080770962113555
test_combo_seen1_pearson_de: 0.7825060687785925
test_combo_seen2_mse: 0.026953346390081078
test_combo_seen2_pearson: 0.9294092
test_combo_seen2_mse_de: 0.38369020584382507
test_combo_seen2_pearson_de: 0.8632396
test_unseen_single_mse: 0.014657846897737019
test_unseen_single_pearson: 0.95976037
test_unseen_single_mse_de: 0.28602629131637514
test_unseen_single_pearson_de: 0.8527543627553515
test_combo_seen0_pearson_delta: 0.3631595
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.3777777777777778
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.6388888888888888
test_combo_seen0_mse_top20_de_non_dropout: 0.5432593433393372
test_combo_seen1_pearson_delta: 0.36011484
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.3267441860465116
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.6011627906976744
test_combo_seen1_mse_top20_de_non_dropout: 0.5011977264007856
test_combo_seen2_pearson_delta: 0.39043182
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.2578947368421053
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.7210526315789473
test_combo_seen2_mse_top20_de_non_dropout: 0.38779942769753306
test_unseen_single_pearson_delta: 0.2775031
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.3458333333333334
test_unseen_single_frac_sigma_below_1_non_dropout: 0.7527777777777778
test_unseen_single_mse_top20_de_non_dropout: 0.31052299588918686
Done!
2026-10-06 15:29:29,461 INFO lasser.utils: [gears_train] done in 338.6s, peak CUDA memory 0.87 GB
2026-10-06 15:29:29,484 INFO lasser.utils: [evaluate] start
2026-10-06 15:32:30,311 INFO lasser.evaluation: test (eval.py): pearson_delta=0.3380 mse_top20_de=0.3667 nmse_top20_de=4.5177 over 107 perts
2026-10-06 15:32:30,311 INFO lasser.evaluation:   combo_seen0    pearson_delta=0.3632 mse_top20_de=0.4423 (9 perts)
2026-10-06 15:32:30,312 INFO lasser.evaluation:   combo_seen1    pearson_delta=0.3601 mse_top20_de=0.4108 (43 perts)
2026-10-06 15:32:30,312 INFO lasser.evaluation:   combo_seen2    pearson_delta=0.3904 mse_top20_de=0.3837 (19 perts)
2026-10-06 15:32:30,312 INFO lasser.evaluation:   unseen_single  pearson_delta=0.2775 mse_top20_de=0.2860 (36 perts)
2026-10-06 15:32:30,313 INFO lasser.utils: [evaluate] done in 180.8s, peak CUDA memory 1.15 GB
2026-10-06 15:32:30,335 INFO lasser.tracking: appended run 84c27427 to /kaggle/working/lasser_tests/runs/runs.csv
{'gears_init': {'seconds': 19.71, 'peak_cuda_gb': 0.026}, 'gears_train': {'seconds': 338.64, 'peak_cuda_gb': 0.87}, 'evaluate': {'seconds': 180.83, 'peak_cuda_gb': 1.154}}
{'graph_learning': False, 'graph_source': 'gears_static', 'graph_num_nodes': 5045, 'graph_num_edges': 6364, 'graph_num_self_loops': 4699, 'graph_degree_min': 0, 'graph_degree_median': 0.0, 'graph_degree_mean': 0.33002973240832506, 'graph_degree_max': 20, 'graph_degree_gini': 0.9324442777762897, 'graph_isolated_genes': 4419, 'test_pearson_delta': 0.3379597474558878, 'test_pearson_delta_top20_de': 0.29319328920693566, 'test_mse_top20_de': 0.36665652513016606, 'test_nmse_top20_de': 4.517705123699708, 'test_nmse_top20_de_ratio_of_means': 0.839329660614871, 'test_frac_opposite_top20_de': 0.47616822429906536, 'test_mse': 0.02283312769815604, 'test_pearson': 0.9407444801077445, 'test_combo_seen0_pearson_delta': 0.36315948842413015, 'test_combo_seen0_mse_top20_de': 0.44227351910538143, 'test_combo_seen0_nmse_top20_de': 10.625507755791197, 'test_combo_seen1_pearson_delta': 0.3601148736338367, 'test_combo_seen1_mse_top20_de': 0.41080765452149304, 'test_combo_seen1_nmse_top20_de': 5.411365881645426, 'test_combo_seen2_pearson_delta': 0.39043187649087163, 'test_combo_seen2_mse_top20_de': 0.3836900372254221, 'test_combo_seen2_nmse_top20_de': 0.7417592219836902, 'test_unseen_single_pearson_delta': 0.27750312117725784, 'test_unseen_single_mse_top20_de': 0.2860262962575588, 'test_unseen_single_nmse_top20_de': 3.9161866751473458}
.2026-10-06 15:32:30,341 INFO lasser.tracking: run 8a244174 -> /kaggle/working/lasser_tests/runs/norman_seed1_gl_20261006-153230_smoke
2026-10-06 15:32:30,347 INFO lasser.run: device: cuda:0 (Tesla T4, 14.6 GB) (GEARS training and GSR graph learning)
Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!
here1
2026-10-06 15:32:30,356 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75_subgroup.pkl', 'norman_simulation_1_0.75.pkl'])
2026-10-06 15:32:30,358 INFO lasser.utils: [gsr_graph] start
2026-10-06 15:32:30,413 INFO lasser.graph: GSR graph learning on cuda:0 (Tesla T4, 14.6 GB)
2026-10-06 15:32:30,413 INFO lasser.utils: [gsr/data] start
2026-10-06 15:32:30,975 INFO lasser.data: training cells: 49849 (A0 subset 38824, H1 24957, H2 24892) over 138 training perturbations
2026-10-06 15:32:30,977 INFO lasser.utils: [gsr/data] done in 0.6s, peak CUDA memory 0.02 GB
2026-10-06 15:32:30,977 INFO lasser.utils: [gsr/views] start
2026-10-06 15:32:40,994 INFO lasser.data: metacells: 49849 cells -> 500 metacells
2026-10-06 15:32:41,711 INFO lasser.views: view E: dim 64, missing genes 234
2026-10-06 15:32:42,207 INFO lasser.views: view R: dim 32, missing genes 271
2026-10-06 15:32:42,633 INFO lasser.views: deepwalk epoch 1: loss 1.6828 over 1064200 pairs
2026-10-06 15:32:42,950 INFO lasser.views: deepwalk epoch 2: loss 0.0779 over 1064200 pairs
2026-10-06 15:32:43,243 INFO lasser.views: deepwalk epoch 3: loss 0.0568 over 1064200 pairs
2026-10-06 15:32:43,244 INFO lasser.views: view S: dim 64, missing genes 4419
2026-10-06 15:32:43,245 INFO lasser.utils: [gsr/views] done in 12.3s, peak CUDA memory 0.08 GB
2026-10-06 15:32:43,245 INFO lasser.utils: [gsr/positives] start
2026-10-06 15:32:49,476 INFO lasser.pretrain: positives: {'h1_cells_used': 19434, 'candidate_pairs': 1070, 'bootstrap_kept_pairs': 564, 'positive_pairs': 564}
2026-10-06 15:32:49,476 INFO lasser.utils: [gsr/positives] done in 6.2s, peak CUDA memory 1.57 GB
2026-10-06 15:32:49,477 INFO lasser.utils: [gsr/pretrain] start
2026-10-06 15:32:49,499 INFO lasser.pretrain: link AUC of raw view features (baseline): {'E': 0.9703, 'R': 0.8699, 'S': 0.7321, 'combined': 0.9697}
2026-10-06 15:32:49,933 INFO lasser.pretrain: pretrain step 10 (epoch 10): loss 4.6834 intra 4.4926 inter 5.1170 var 0.3473 | AUC {'E': 0.9684, 'R': 0.9665, 'S': 0.2286, 'combined': 0.9879} | cos_std {'E': 0.28, 'R': 0.35, 'S': 0.196}
2026-10-06 15:32:50,273 INFO lasser.pretrain: pretrain step 20 (epoch 20): loss 4.0445 intra 3.8817 inter 4.4139 var 0.2973 | AUC {'E': 0.9672, 'R': 0.9703, 'S': 0.2283, 'combined': 0.9872} | cos_std {'E': 0.313, 'R': 0.319, 'S': 0.296}
2026-10-06 15:32:50,601 INFO lasser.pretrain: pretrain step 30 (epoch 30): loss 3.7153 intra 3.5704 inter 4.0439 var 0.2649 | AUC {'E': 0.9595, 'R': 0.9592, 'S': 0.2436, 'combined': 0.9761} | cos_std {'E': 0.354, 'R': 0.354, 'S': 0.431}
2026-10-06 15:32:50,928 INFO lasser.pretrain: pretrain step 40 (epoch 40): loss 3.3569 intra 3.2225 inter 3.6610 var 0.2474 | AUC {'E': 0.9646, 'R': 0.9617, 'S': 0.2309, 'combined': 0.9799} | cos_std {'E': 0.328, 'R': 0.354, 'S': 0.416}
2026-10-06 15:32:51,278 INFO lasser.pretrain: pretrain step 50 (epoch 50): loss 3.2379 intra 3.1357 inter 3.4527 var 0.2291 | AUC {'E': 0.9707, 'R': 0.9601, 'S': 0.2305, 'combined': 0.9812} | cos_std {'E': 0.304, 'R': 0.343, 'S': 0.461}
2026-10-06 15:32:51,607 INFO lasser.pretrain: pretrain step 60 (epoch 60): loss 3.0068 intra 2.8903 inter 3.2716 var 0.2111 | AUC {'E': 0.9691, 'R': 0.964, 'S': 0.2305, 'combined': 0.9786} | cos_std {'E': 0.301, 'R': 0.323, 'S': 0.459}
2026-10-06 15:32:51,607 INFO lasser.pretrain: early stop at step 60 (best step 10, AUC 0.9879)
2026-10-06 15:32:51,624 INFO lasser.pretrain: pretraining done: best step 10, held-out link AUC 0.9879 (raw features 0.9697)
2026-10-06 15:32:51,629 INFO lasser.utils: [gsr/pretrain] done in 2.2s, peak CUDA memory 0.25 GB
2026-10-06 15:32:51,629 INFO lasser.utils: [gsr/refine] start
2026-10-06 15:32:51,710 INFO lasser.refine: refinement: {'a0_edges': 6364, 'removed': 20, 'added_directed': 38848, 'topup_directed': 0, 'refined_edges': 45192, 'new_weight_mean': 0.24377146363258362, 'a0_weight_mean': 0.5615240931510925}
2026-10-06 15:32:51,711 INFO lasser.utils: [gsr/refine] done in 0.1s, peak CUDA memory 0.07 GB
2026-10-06 15:32:51,711 INFO lasser.utils: [gsr/checks] start
2026-10-06 15:32:52,885 INFO lasser.checks: graph checks: H2 {'threshold': 0.2, 'hit_rate_added': 0.036, 'hit_rate_added_only': 0.036, 'hit_rate_topup': nan, 'hit_rate_degree_matched_random': 0.002, 'hit_rate_a0': 0.581, 'hit_rate_removed': 0.75, 'passes': True} | coverage {'low_degree_genes': 4935, 'low_degree_mean_degree_a0': 0.16757852077001012, 'low_degree_mean_degree_refined': 8.116109422492402, 'undirected_isolated_a0': 4419, 'undirected_isolated_refined': 0} | jaccard 0.032 | collapse ok True
2026-10-06 15:32:52,888 INFO lasser.utils: [gsr/checks] done in 1.2s, peak CUDA memory 1.14 GB
2026-10-06 15:32:52,984 INFO lasser.graph: GSR graph cached at /kaggle/working/lasser_tests/cache/gsr/norman_simulation_seed1_0.75_acff059d6c09
2026-10-06 15:32:52,985 INFO lasser.utils: [gsr_graph] done in 22.6s, peak CUDA memory 1.14 GB
2026-10-06 15:32:52,987 INFO lasser.utils: [gears_init] start
Found local copy...
2026-10-06 15:33:12,129 INFO lasser.utils: [gears_init] done in 19.1s, peak CUDA memory 0.04 GB
2026-10-06 15:33:12,133 INFO lasser.run: co-expression graph used (gsr_refined): {'num_nodes': 5045, 'num_edges': 45192, 'num_self_loops': 4699, 'degree_min': 5, 'degree_median': 7.0, 'degree_mean': 8.026362735381566, 'degree_max': 25, 'degree_gini': 0.20115459518422557, 'isolated_genes': 0}
2026-10-06 15:33:12,225 INFO lasser.run: training GEARS on cuda:0 (Tesla T4, 14.6 GB) for 1 epochs
2026-10-06 15:33:12,226 INFO lasser.utils: [gears_train] start
Start Training...
Epoch 1 Step 1 Train Loss: 0.5244
Epoch 1 Step 51 Train Loss: 0.6053
Epoch 1 Step 101 Train Loss: 0.5156
Epoch 1 Step 151 Train Loss: 0.5189
Epoch 1 Step 201 Train Loss: 0.4590
Epoch 1 Step 251 Train Loss: 0.5907
Epoch 1 Step 301 Train Loss: 0.4112
Epoch 1 Step 351 Train Loss: 0.5477
Epoch 1 Step 401 Train Loss: 0.5070
Epoch 1 Step 451 Train Loss: 0.5364
Epoch 1 Step 501 Train Loss: 0.4435
Epoch 1 Step 551 Train Loss: 0.5989
Epoch 1 Step 601 Train Loss: 0.4617
Epoch 1 Step 651 Train Loss: 0.5022
Epoch 1 Step 701 Train Loss: 0.4586
Epoch 1 Step 751 Train Loss: 0.4443
Epoch 1 Step 801 Train Loss: 0.4733
Epoch 1 Step 851 Train Loss: 0.4322
Epoch 1 Step 901 Train Loss: 0.5462
Epoch 1 Step 951 Train Loss: 0.4237
Epoch 1 Step 1001 Train Loss: 0.4198
Epoch 1 Step 1051 Train Loss: 0.4945
Epoch 1 Step 1101 Train Loss: 0.5063
Epoch 1 Step 1151 Train Loss: 0.4295
Epoch 1 Step 1201 Train Loss: 0.4361
Epoch 1 Step 1251 Train Loss: 0.4444
Epoch 1 Step 1301 Train Loss: 0.4791
Epoch 1 Step 1351 Train Loss: 0.4482
Epoch 1 Step 1401 Train Loss: 0.4176
Epoch 1 Step 1451 Train Loss: 0.4455
Epoch 1 Step 1501 Train Loss: 0.4358
Epoch 1 Step 1551 Train Loss: 0.4665
Epoch 1: Train Overall MSE: 0.0041 Validation Overall MSE: 0.0049.
Train Top 20 DE MSE: 0.1378 Validation Top 20 DE MSE: 0.3132.
Done!
Start Testing...
Best performing model: Test Top 20 DE MSE: 0.2376
Start doing subgroup analysis for simulation split...
test_combo_seen0_mse: 0.007282509468495846
test_combo_seen0_pearson: 0.9789392
test_combo_seen0_mse_de: 0.23310518782171938
test_combo_seen0_pearson_de: 0.7373310195075141
test_combo_seen1_mse: 0.008642866346595246
test_combo_seen1_pearson: 0.97610724
test_combo_seen1_mse_de: 0.2525887519857565
test_combo_seen1_pearson_de: 0.851472771444986
test_combo_seen2_mse: 0.0075913890951166026
test_combo_seen2_pearson: 0.97886205
test_combo_seen2_mse_de: 0.2621984681800792
test_combo_seen2_pearson_de: 0.90958184
test_unseen_single_mse: 0.003695629006769094
test_unseen_single_pearson: 0.9891579
test_unseen_single_mse_de: 0.20789148467075494
test_unseen_single_pearson_de: 0.8757315758201811
test_combo_seen0_pearson_delta: 0.5347455
test_combo_seen0_frac_opposite_direction_top20_non_dropout: 0.2
test_combo_seen0_frac_sigma_below_1_non_dropout: 0.7611111111111112
test_combo_seen0_mse_top20_de_non_dropout: 0.3306044166286786
test_combo_seen1_pearson_delta: 0.48440495
test_combo_seen1_frac_opposite_direction_top20_non_dropout: 0.21395348837209308
test_combo_seen1_frac_sigma_below_1_non_dropout: 0.7383720930232559
test_combo_seen1_mse_top20_de_non_dropout: 0.32077853901441705
test_combo_seen2_pearson_delta: 0.50888324
test_combo_seen2_frac_opposite_direction_top20_non_dropout: 0.16578947368421051
test_combo_seen2_frac_sigma_below_1_non_dropout: 0.8131578947368422
test_combo_seen2_mse_top20_de_non_dropout: 0.27068665937373515
test_unseen_single_pearson_delta: 0.42548665
test_unseen_single_frac_opposite_direction_top20_non_dropout: 0.2138888888888889
test_unseen_single_frac_sigma_below_1_non_dropout: 0.8624999999999999
test_unseen_single_mse_top20_de_non_dropout: 0.22543438332569268
Done!
2026-10-06 15:38:49,004 INFO lasser.utils: [gears_train] done in 336.8s, peak CUDA memory 0.87 GB
2026-10-06 15:38:49,025 INFO lasser.utils: [evaluate] start
2026-10-06 15:41:49,581 INFO lasser.evaluation: test (eval.py): pearson_delta=0.4732 mse_top20_de=0.2376 nmse_top20_de=1.4076 over 107 perts
2026-10-06 15:41:49,581 INFO lasser.evaluation:   combo_seen0    pearson_delta=0.5347 mse_top20_de=0.2331 (9 perts)
2026-10-06 15:41:49,582 INFO lasser.evaluation:   combo_seen1    pearson_delta=0.4844 mse_top20_de=0.2526 (43 perts)
2026-10-06 15:41:49,582 INFO lasser.evaluation:   combo_seen2    pearson_delta=0.5089 mse_top20_de=0.2622 (19 perts)
2026-10-06 15:41:49,582 INFO lasser.evaluation:   unseen_single  pearson_delta=0.4255 mse_top20_de=0.2079 (36 perts)
2026-10-06 15:41:49,583 INFO lasser.utils: [evaluate] done in 180.6s, peak CUDA memory 1.15 GB
2026-10-06 15:41:49,610 INFO lasser.tracking: appended run 8a244174 to /kaggle/working/lasser_tests/runs/runs.csv
{'gsr/data': {'seconds': 0.56, 'peak_cuda_gb': 0.017}, 'gsr/views': {'seconds': 12.27, 'peak_cuda_gb': 0.077}, 'gsr/positives': {'seconds': 6.23, 'peak_cuda_gb': 1.573}, 'gsr/pretrain': {'seconds': 2.15, 'peak_cuda_gb': 0.249}, 'gsr/refine': {'seconds': 0.08, 'peak_cuda_gb': 0.074}, 'gsr/checks': {'seconds': 1.18, 'peak_cuda_gb': 1.145}, 'gsr_graph_from_cache': False, 'gsr_graph': {'seconds': 22.63, 'peak_cuda_gb': 1.145}, 'gears_init': {'seconds': 19.14, 'peak_cuda_gb': 0.044}, 'gears_train': {'seconds': 336.78, 'peak_cuda_gb': 0.872}, 'evaluate': {'seconds': 180.56, 'peak_cuda_gb': 1.154}}
{'graph_learning': True, 'graph_source': 'gsr_refined', 'graph_num_nodes': 5045, 'graph_num_edges': 45192, 'graph_num_self_loops': 4699, 'graph_degree_min': 5, 'graph_degree_median': 7.0, 'graph_degree_mean': 8.026362735381566, 'graph_degree_max': 25, 'graph_degree_gini': 0.20115459518422557, 'graph_isolated_genes': 0, 'test_pearson_delta': 0.47316277953649705, 'test_pearson_delta_top20_de': 0.5501424141750957, 'test_mse_top20_de': 0.2376180508709295, 'test_nmse_top20_de': 1.407567574839743, 'test_nmse_top20_de_ratio_of_means': 0.5439419847298821, 'test_frac_opposite_top20_de': 0.3794392523364486, 'test_mse': 0.006677241730460218, 'test_pearson': 0.981225446421372, 'test_combo_seen0_pearson_delta': 0.5347455444265701, 'test_combo_seen0_mse_top20_de': 0.2331052604648802, 'test_combo_seen0_nmse_top20_de': 3.0719088527518004, 'test_combo_seen1_pearson_delta': 0.4844048798670401, 'test_combo_seen1_mse_top20_de': 0.25258879853022653, 'test_combo_seen1_nmse_top20_de': 1.7172196453165762, 'test_combo_seen2_pearson_delta': 0.508883262225828, 'test_combo_seen2_mse_top20_de': 0.26219841406533595, 'test_combo_seen2_nmse_top20_de': 0.5276124309639296, 'test_unseen_single_pearson_delta': 0.42548654705535, 'test_unseen_single_mse_top20_de': 0.20789155263790032, 'test_unseen_single_nmse_top20_de': 1.086040830448857}
.

=============================== warnings summary ===============================
lasser-repo/tests/test_09_smoke.py::test_smoke_full_norman[False]
lasser-repo/tests/test_09_smoke.py::test_smoke_full_norman[False]
  /usr/local/lib/python3.13/dist-packages/torch/jit/_script.py:1488: DeprecationWarning: `torch.jit.script` is deprecated. Please switch to `torch.compile` or `torch.export`.
    warnings.warn(

lasser-repo/tests/test_09_smoke.py::test_smoke_full_norman[False]

In [5]:
# 4. Load the data once and reuse it for both runs.
from lasser import GSRConfig, LasserConfig, load_pert_data, load_run, run_experiment

common = dict(dataset="norman", seed=1, epochs=20,
              data_dir="/kaggle/working/data", out_dir="/kaggle/working/runs",
              cache_dir="/kaggle/working/cache", repo_dir=REPO_DIR)
pert_data = load_pert_data(LasserConfig(**common))

Found local copy...
Found local copy...
Found local copy...
These perturbations are not in the GO graph and their perturbation can thus not be predicted
['RHOXF2BB+ctrl' 'LYL1+IER5L' 'ctrl+IER5L' 'KIAA1804+ctrl' 'IER5L+ctrl'
 'RHOXF2BB+ZBTB25' 'RHOXF2BB+SET']
Local copy of pyg dataset is detected. Loading...
Done!

In [6]:
# 5. Baseline: graph_learning=False is plain GEARS (plus logging and saving).
base = run_experiment(LasserConfig(**common, graph_learning=False), pert_data)
base["run_dir"]

2026-10-06 15:42:35,532 INFO lasser.tracking: run f71d4a24 -> /kaggle/working/runs/norman_seed1_base_20261006-154235
2026-10-06 15:42:35,592 INFO lasser.run: device: cuda:0 (Tesla T4, 14.6 GB) (GEARS training)

Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!

here1
2026-10-06 15:42:35,608 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75_subgroup.pkl', 'norman_simulation_1_0.75.pkl'])
2026-10-06 15:42:35,610 INFO lasser.utils: [gears_init] start

Found local copy...

2026-10-06 15:42:55,107 INFO lasser.utils: [gears_init] done in 19.5s, peak CUDA memory 0.03 GB
2026-10-06 15:42:55,111 INFO lasser.run: co-expression graph used (gears_static): {'num_nodes': 5045, 'num_edges': 6364, 'num_self_loops': 4699, 'degree_min': 0, 'degree_median': 0.0, 'degree_mean': 0.33002973240832506, 'degree_max': 20, 'degree_gini': 0.9324442777762897, 'isolated_genes': 4419}
2026-10-06 15:42:55,112 INFO lasser.run: training GEARS on cuda:0 (Tesla T4, 14.6 GB) for 20 epochs
2026-10-06 15:42:55,113 INFO lasser.utils: [gears_train] start

Start Training...
Epoch 1 Step 1 Train Loss: 0.5244
Epoch 1 Step 51 Train Loss: 0.6091
Epoch 1 Step 101 Train Loss: 0.5209
Epoch 1 Step 151 Train Loss: 0.5209
Epoch 1 Step 201 Train Loss: 0.4587
Epoch 1 Step 251 Train Loss: 0.5997
Epoch 1 Step 301 Train Loss: 0.4134
Epoch 1 Step 351 Train Loss: 0.5552
Epoch 1 Step 401 Train Loss: 0.5103
Epoch 1 Step 451 Train Loss: 0.5323
Epoch 1 Step 501 Train Loss: 0.4438
Epoch 1 Step 551 Train Loss: 0.6089
Epoch 1 Step 601 Train Loss: 0.4665
Epoch 1 Step 651 Train Loss: 0.5068
Epoch 1 Step 701 Train Loss: 0.4650
Epoch 1 Step 751 Train Loss: 0.4468
Epoch 1 Step 801 Train Loss: 0.4661
Epoch 1 Step 851 Train Loss: 0.4330
Epoch 1 Step 901 Train Loss: 0.5428
Epoch 1 Step 951 Train Loss: 0.4253
Epoch 1 Step 1001 Train Loss: 0.4217
Epoch 1 Step 1051 Train Loss: 0.4812
Epoch 1 Step 1101 Train Loss: 0.5036
Epoch 1 Step 1151 Train Loss: 0.4303
Epoch 1 Step 1201 Train Loss: 0.4306
Epoch 1 Step 1251 Train Loss: 0.4368
Epoch 1 Step 1301 Train Loss: 0.4825
Epoch 1 Step 1351 Train Loss: 0.4502
Epoch 1 Step 1401 Train Loss: 0.4172
Epoch 1 Step 1451 Train Loss: 0.4410
Epoch 1 Step 1501 Train Loss: 0.4368
Epoch 1 Step 1551 Train Loss: 0.4636
Epoch 1: Train Overall MSE: 0.0061 Validation Overall MSE: 0.0074.
Train Top 20 DE MSE: 0.1517 Validation Top 20 DE MSE: 0.3340.
Epoch 2 Step 1 Train Loss: 0.5305
Epoch 2 Step 51 Train Loss: 0.4487
Epoch 2 Step 101 Train Loss: 0.4395
Epoch 2 Step 151 Train Loss: 0.4640
Epoch 2 Step 201 Train Loss: 0.5754
Epoch 2 Step 251 Train Loss: 0.4353
Epoch 2 Step 301 Train Loss: 0.5220
Epoch 2 Step 351 Train Loss: 0.4188
Epoch 2 Step 401 Train Loss: 0.4769
Epoch 2 Step 451 Train Loss: 0.4105
Epoch 2 Step 501 Train Loss: 0.4853
Epoch 2 Step 551 Train Loss: 0.5199
Epoch 2 Step 601 Train Loss: 0.6004
Epoch 2 Step 651 Train Loss: 0.3954
Epoch 2 Step 701 Train Loss: 0.5385
Epoch 2 Step 751 Train Loss: 0.5253
Epoch 2 Step 801 Train Loss: 0.5293
Epoch 2 Step 851 Train Loss: 0.4735
Epoch 2 Step 901 Train Loss: 0.5754
Epoch 2 Step 951 Train Loss: 0.4307
Epoch 2 Step 1001 Train Loss: 0.4635
Epoch 2 Step 1051 Train Loss: 0.4783
Epoch 2 Step 1101 Train Loss: 0.5079
Epoch 2 Step 1151 Train Loss: 0.5014
Epoch 2 Step 1201 Train Loss: 0.4497
Epoch 2 Step 1251 Train Loss: 0.4772
Epoch 2 Step 1301 Train Loss: 0.6782
Epoch 2 Step 1351 Train Loss: 0.4437
Epoch 2 Step 1401 Train Loss: 0.6158
Epoch 2 Step 1451 Train Loss: 0.5284
Epoch 2 Step 1501 Train Loss: 0.5543
Epoch 2 Step 1551 Train Loss: 0.4093
Epoch 2: Train Overall MSE: 0.0037 Validation Overall MSE: 0.0043.
Train Top 20 DE MSE: 0.1273 Validation Top 20 DE MSE: 0.2141.
Epoch 3 Step 1 Train Loss: 0.5421
Epoch 3 Step 51 Train Loss: 0.4785
Epoch 3 Step 101 Train Loss: 0.5178
Epoch 3 Step 151 Train Loss: 0.4744
Epoch 3 Step 201 Train Loss: 0.5298
Epoch 3 Step 251 Train Loss: 0.5191
Epoch 3 Step 301 Train Loss: 0.5014
Epoch 3 Step 351 Train Loss: 0.5415
Epoch 3 Step 401 Train Loss: 0.5773
Epoch 3 Step 451 Train Loss: 0.5516
Epoch 3 Step 501 Train Loss: 0.4865
Epoch 3 Step 551 Train Loss: 0.4606
Epoch 3 Step 601 Train Loss: 0.4455
Epoch 3 Step 651 Train Loss: 0.4584
Epoch 3 Step 701 Train Loss: 0.4661
Epoch 3 Step 751 Train Loss: 0.5182
Epoch 3 Step 801 Train Loss: 0.4926
Epoch 3 Step 851 Train Loss: 0.5015
Epoch 3 Step 901 Train Loss: 0.4872
Epoch 3 Step 951 Train Loss: 0.4380
Epoch 3 Step 1001 Train Loss: 0.4580
Epoch 3 Step 1051 Train Loss: 0.4852
Epoch 3 Step 1101 Train Loss: 0.5365
Epoch 3 Step 1151 Train Loss: 0.5213
Epoch 3 Step 1201 Train Loss: 0.5137
Epoch 3 Step 1251 Train Loss: 0.5224
Epoch 3 Step 1301 Train Loss: 0.6051
Epoch 3 Step 1351 Train Loss: 0.5059
Epoch 3 Step 1401 Train Loss: 0.4441
Epoch 3 Step 1451 Train Loss: 0.4392
Epoch 3 Step 1501 Train Loss: 0.4358
Epoch 3 Step 1551 Train Loss: 0.5385
Epoch 3: Train Overall MSE: 0.0024 Validation Overall MSE: 0.0033.
Train Top 20 DE MSE: 0.0844 Validation Top 20 DE MSE: 0.2396.
Epoch 4 Step 1 Train Loss: 0.5470
Epoch 4 Step 51 Train Loss: 0.5144
Epoch 4 Step 101 Train Loss: 0.4745
Epoch 4 Step 151 Train Loss: 0.6257
Epoch 4 Step 201 Train Loss: 0.4991
Epoch 4 Step 251 Train Loss: 0.4830
Epoch 4 Step 301 Train Loss: 0.4981
Epoch 4 Step 351 Train Loss: 0.5002
Epoch 4 Step 401 Train Loss: 0.5284
Epoch 4 Step 451 Train Loss: 0.5021
Epoch 4 Step 501 Train Loss: 0.4976
Epoch 4 Step 551 Train Loss: 0.4798
Epoch 4 Step 601 Train Loss: 0.4353
Epoch 4 Step 651 Train Loss: 0.4759
Epoch 4 Step 701 Train Loss: 0.5294
Epoch 4 Step 751 Train Loss: 0.4675
Epoch 4 Step 801 Train Loss: 0.5130
Epoch 4 Step 851 Train Loss: 0.4485
Epoch 4 Step 901 Train Loss: 0.5075
Epoch 4 Step 951 Train Loss: 0.5110
Epoch 4 Step 1001 Train Loss: 0.5804
Epoch 4 Step 1051 Train Loss: 0.5027
Epoch 4 Step 1101 Train Loss: 0.5099
Epoch 4 Step 1151 Train Loss: 0.5035
Epoch 4 Step 1201 Train Loss: 0.4717
Epoch 4 Step 1251 Train Loss: 0.5171
Epoch 4 Step 1301 Train Loss: 0.5060
Epoch 4 Step 1351 Train Loss: 0.4402
Epoch 4 Step 1401 Train Loss: 0.5575
Epoch 4 Step 1451 Train Loss: 0.4744
Epoch 4 Step 1501 Train Loss: 0.4933
Epoch 4 Step 1551 Train Loss: 0.5100
Epoch 4: Train Overall MSE: 0.0026 Validation Overall MSE: 0.0040.
Train Top 20 DE MSE: 0.0885 Validation Top 20 DE MSE: 0.2533.
Epoch 5 Step 1 Train Loss: 0.6226
Epoch 5 Step 51 Train Loss: 0.4685
Epoch 5 Step 101 Train Loss: 0.4872
Epoch 5 Step 151 Train Loss: 0.5081
Epoch 5 Step 201 Train Loss: 0.4816
Epoch 5 Step 251 Train Loss: 0.5140
Epoch 5 Step 301 Train Loss: 0.4726
Epoch 5 Step 351 Train Loss: 0.5876
Epoch 5 Step 401 Train Loss: 0.5050
Epoch 5 Step 451 Train Loss: 0.5482
Epoch 5 Step 501 Train Loss: 0.5429
Epoch 5 Step 551 Train Loss: 0.5379
Epoch 5 Step 601 Train Loss: 0.4805
Epoch 5 Step 651 Train Loss: 0.5698
Epoch 5 Step 701 Train Loss: 0.5596
Epoch 5 Step 751 Train Loss: 0.4975
Epoch 5 Step 801 Train Loss: 0.4637
Epoch 5 Step 851 Train Loss: 0.5095
Epoch 5 Step 901 Train Loss: 0.5003
Epoch 5 Step 951 Train Loss: 0.4762
Epoch 5 Step 1001 Train Loss: 0.5143
Epoch 5 Step 1051 Train Loss: 0.5721
Epoch 5 Step 1101 Train Loss: 0.5930
Epoch 5 Step 1151 Train Loss: 0.5459
Epoch 5 Step 1201 Train Loss: 0.5719
Epoch 5 Step 1251 Train Loss: 0.5765
Epoch 5 Step 1301 Train Loss: 0.5194
Epoch 5 Step 1351 Train Loss: 0.5324
Epoch 5 Step 1401 Train Loss: 0.4790
Epoch 5 Step 1451 Train Loss: 0.5518
Epoch 5 Step 1501 Train Loss: 0.5038
Epoch 5 Step 1551 Train Loss: 0.4708
Epoch 5: Train Overall MSE: 0.0024 Validation Overall MSE: 0.0035.
Train Top 20 DE MSE: 0.0781 Validation Top 20 DE MSE: 0.2320.
Epoch 6 Step 1 Train Loss: 0.4323
Epoch 6 Step 51 Train Loss: 0.5222
Epoch 6 Step 101 Train Loss: 0.4582
Epoch 6 Step 151 Train Loss: 0.5034
Epoch 6 Step 201 Train Loss: 0.4677
Epoch 6 Step 251 Train Loss: 0.5075
Epoch 6 Step 301 Train Loss: 0.5622
Epoch 6 Step 351 Train Loss: 0.5094
Epoch 6 Step 401 Train Loss: 0.5173
Epoch 6 Step 451 Train Loss: 0.4744
Epoch 6 Step 501 Train Loss: 0.4433
Epoch 6 Step 551 Train Loss: 0.4568
Epoch 6 Step 601 Train Loss: 0.4664
Epoch 6 Step 651 Train Loss: 0.5623
Epoch 6 Step 701 Train Loss: 0.5265
Epoch 6 Step 751 Train Loss: 0.5674
Epoch 6 Step 801 Train Loss: 0.4597
Epoch 6 Step 851 Train Loss: 0.5400
Epoch 6 Step 901 Train Loss: 0.4714
Epoch 6 Step 951 Train Loss: 0.4946
Epoch 6 Step 1001 Train Loss: 0.5203
Epoch 6 Step 1051 Train Loss: 0.4864
Epoch 6 Step 1101 Train Loss: 0.4661
Epoch 6 Step 1151 Train Loss: 0.5346
Epoch 6 Step 1201 Train Loss: 0.4820
Epoch 6 Step 1251 Train Loss: 0.5312
Epoch 6 Step 1301 Train Loss: 0.4415
Epoch 6 Step 1351 Train Loss: 0.4509
Epoch 6 Step 1401 Train Loss: 0.5331
Epoch 6 Step 1451 Train Loss: 0.5960
Epoch 6 Step 1501 Train Loss: 0.5577
Epoch 6 Step 1551 Train Loss: 0.6010
Epoch 6: Train Overall MSE: 0.0024 Validation Overall MSE: 0.0035.
Train Top 20 DE MSE: 0.0757 Validation Top 20 DE MSE: 0.2170.
Epoch 7 Step 1 Train Loss: 0.5040
Epoch 7 Step 51 Train Loss: 0.4932
Epoch 7 Step 101 Train Loss: 0.5254
Epoch 7 Step 151 Train Loss: 0.5161
Epoch 7 Step 201 Train Loss: 0.4812
Epoch 7 Step 251 Train Loss: 0.4881
Epoch 7 Step 301 Train Loss: 0.4813
Epoch 7 Step 351 Train Loss: 0.4898
Epoch 7 Step 401 Train Loss: 0.5216
Epoch 7 Step 451 Train Loss: 0.4960
Epoch 7 Step 501 Train Loss: 0.5518
Epoch 7 Step 551 Train Loss: 0.5376
Epoch 7 Step 601 Train Loss: 0.4575
Epoch 7 Step 651 Train Loss: 0.4622
Epoch 7 Step 701 Train Loss: 0.4871
Epoch 7 Step 751 Train Loss: 0.5251
Epoch 7 Step 801 Train Loss: 0.5277
Epoch 7 Step 851 Train Loss: 0.5611
Epoch 7 Step 901 Train Loss: 0.5344
Epoch 7 Step 951 Train Loss: 0.5472
Epoch 7 Step 1001 Train Loss: 0.4932
Epoch 7 Step 1051 Train Loss: 0.5216
Epoch 7 Step 1101 Train Loss: 0.4352
Epoch 7 Step 1151 Train Loss: 0.4815
Epoch 7 Step 1201 Train Loss: 0.5272
Epoch 7 Step 1251 Train Loss: 0.4919
Epoch 7 Step 1301 Train Loss: 0.4853
Epoch 7 Step 1351 Train Loss: 0.5063
Epoch 7 Step 1401 Train Loss: 0.5767
Epoch 7 Step 1451 Train Loss: 0.5221
Epoch 7 Step 1501 Train Loss: 0.4903
Epoch 7 Step 1551 Train Loss: 0.5283
Epoch 7: Train Overall MSE: 0.0024 Validation Overall MSE: 0.0035.
Train Top 20 DE MSE: 0.0765 Validation Top 20 DE MSE: 0.2357.
Epoch 8 Step 1 Train Loss: 0.5082
Epoch 8 Step 51 Train Loss: 0.4885
Epoch 8 Step 101 Train Loss: 0.5716
Epoch 8 Step 151 Train Loss: 0.5039
Epoch 8 Step 201 Train Loss: 0.5062
Epoch 8 Step 251 Train Loss: 0.5097
Epoch 8 Step 301 Train Loss: 0.5492
Epoch 8 Step 351 Train Loss: 0.4838
Epoch 8 Step 401 Train Loss: 0.5173
Epoch 8 Step 451 Train Loss: 0.5891
Epoch 8 Step 501 Train Loss: 0.5263
Epoch 8 Step 551 Train Loss: 0.5229
Epoch 8 Step 601 Train Loss: 0.6369
Epoch 8 Step 651 Train Loss: 0.5710
Epoch 8 Step 701 Train Loss: 0.5517
Epoch 8 Step 751 Train Loss: 0.5117
Epoch 8 Step 801 Train Loss: 0.6173
Epoch 8 Step 851 Train Loss: 0.5653
Epoch 8 Step 901 Train Loss: 0.6134
Epoch 8 Step 951 Train Loss: 0.6045
Epoch 8 Step 1001 Train Loss: 0.5407
Epoch 8 Step 1051 Train Loss: 0.4900
Epoch 8 Step 1101 Train Loss: 0.5728
Epoch 8 Step 1151 Train Loss: 0.4981
Epoch 8 Step 1201 Train Loss: 0.5318
Epoch 8 Step 1251 Train Loss: 0.4617
Epoch 8 Step 1301 Train Loss: 0.4697
Epoch 8 Step 1351 Train Loss: 0.4776
Epoch 8 Step 1401 Train Loss: 0.5891
Epoch 8 Step 1451 Train Loss: 0.5076
Epoch 8 Step 1501 Train Loss: 0.5241
Epoch 8 Step 1551 Train Loss: 0.4926
Epoch 8: Train Overall MSE: 0.0023 Validation Overall MSE: 0.0034.
Train Top 20 DE MSE: 0.0772 Validation Top 20 DE MSE: 0.2334.
Epoch 9 Step 1 Train Loss: 0.4483
Epoch 9 Step 51 Train Loss: 0.5188
Epoch 9 Step 101 Train Loss: 0.5236
Epoch 9 Step 151 Train Loss: 0.5959
Epoch 9 Step 201 Train Loss: 0.5367
Epoch 9 Step 251 Train Loss: 0.5262
Epoch 9 Step 301 Train Loss: 0.4749
Epoch 9 Step 351 Train Loss: 0.4938
Epoch 9 Step 401 Train Loss: 0.6342
Epoch 9 Step 451 Train Loss: 0.5276
Epoch 9 Step 501 Train Loss: 0.5014
Epoch 9 Step 551 Train Loss: 0.5176
Epoch 9 Step 601 Train Loss: 0.5137
Epoch 9 Step 651 Train Loss: 0.6124
Epoch 9 Step 701 Train Loss: 0.4873
Epoch 9 Step 751 Train Loss: 0.4660
Epoch 9 Step 801 Train Loss: 0.4960
Epoch 9 Step 851 Train Loss: 0.5441
Epoch 9 Step 901 Train Loss: 0.4788
Epoch 9 Step 951 Train Loss: 0.4802
Epoch 9 Step 1001 Train Loss: 0.5478
Epoch 9 Step 1051 Train Loss: 0.5735
Epoch 9 Step 1101 Train Loss: 0.5746
Epoch 9 Step 1151 Train Loss: 0.6003
Epoch 9 Step 1201 Train Loss: 0.5469
Epoch 9 Step 1251 Train Loss: 0.6355
Epoch 9 Step 1301 Train Loss: 0.4875
Epoch 9 Step 1351 Train Loss: 0.4951
Epoch 9 Step 1401 Train Loss: 0.6026
Epoch 9 Step 1451 Train Loss: 0.5764
Epoch 9 Step 1501 Train Loss: 0.4787
Epoch 9 Step 1551 Train Loss: 0.5208
Epoch 9: Train Overall MSE: 0.0025 Validation Overall MSE: 0.0036.
Train Top 20 DE MSE: 0.0721 Validation Top 20 DE MSE: 0.2263.
Epoch 10 Step 1 Train Loss: 0.4479
Epoch 10 Step 51 Train Loss: 0.5318
Epoch 10 Step 101 Train Loss: 0.4493
Epoch 10 Step 151 Train Loss: 0.4949
Epoch 10 Step 201 Train Loss: 0.5375
Epoch 10 Step 251 Train Loss: 0.4421
Epoch 10 Step 301 Train Loss: 0.4988
Epoch 10 Step 351 Train Loss: 0.5224
Epoch 10 Step 401 Train Loss: 0.5221
Epoch 10 Step 451 Train Loss: 0.5421
Epoch 10 Step 501 Train Loss: 0.5087
Epoch 10 Step 551 Train Loss: 0.4829
Epoch 10 Step 601 Train Loss: 0.5679
Epoch 10 Step 651 Train Loss: 0.5590
Epoch 10 Step 701 Train Loss: 0.5705
Epoch 10 Step 751 Train Loss: 0.5293
Epoch 10 Step 801 Train Loss: 0.5940
Epoch 10 Step 851 Train Loss: 0.4552
Epoch 10 Step 901 Train Loss: 0.4914
Epoch 10 Step 951 Train Loss: 0.5366
Epoch 10 Step 1001 Train Loss: 0.4415
Epoch 10 Step 1051 Train Loss: 0.5175
Epoch 10 Step 1101 Train Loss: 0.4889
Epoch 10 Step 1151 Train Loss: 0.5163
Epoch 10 Step 1201 Train Loss: 0.4905
Epoch 10 Step 1251 Train Loss: 0.5079
Epoch 10 Step 1301 Train Loss: 0.5043
Epoch 10 Step 1351 Train Loss: 0.4396
Epoch 10 Step 1401 Train Loss: 0.4733
Epoch 10 Step 1451 Train Loss: 0.5190
Epoch 10 Step 1501 Train Loss: 0.4494
Epoch 10 Step 1551 Train Loss: 0.5511
Epoch 10: Train Overall MSE: 0.0022 Validation Overall MSE: 0.0033.
Train Top 20 DE MSE: 0.0790 Validation Top 20 DE MSE: 0.2282.
Epoch 11 Step 1 Train Loss: 0.5204
Epoch 11 Step 51 Train Loss: 0.5072
Epoch 11 Step 101 Train Loss: 0.4797
Epoch 11 Step 151 Train Loss: 0.5409
Epoch 11 Step 201 Train Loss: 0.5157
Epoch 11 Step 251 Train Loss: 0.4688
Epoch 11 Step 301 Train Loss: 0.5447
Epoch 11 Step 351 Train Loss: 0.5055
Epoch 11 Step 401 Train Loss: 0.5381
Epoch 11 Step 451 Train Loss: 0.4661
Epoch 11 Step 501 Train Loss: 0.4576
Epoch 11 Step 551 Train Loss: 0.5205
Epoch 11 Step 601 Train Loss: 0.4751
Epoch 11 Step 651 Train Loss: 0.4306
Epoch 11 Step 701 Train Loss: 0.5397
Epoch 11 Step 751 Train Loss: 0.4608
Epoch 11 Step 801 Train Loss: 0.5476
Epoch 11 Step 851 Train Loss: 0.5267
Epoch 11 Step 901 Train Loss: 0.6002
Epoch 11 Step 951 Train Loss: 0.4753
Epoch 11 Step 1001 Train Loss: 0.4766
Epoch 11 Step 1051 Train Loss: 0.4407
Epoch 11 Step 1101 Train Loss: 0.4389
Epoch 11 Step 1151 Train Loss: 0.5273
Epoch 11 Step 1201 Train Loss: 0.5315
Epoch 11 Step 1251 Train Loss: 0.4455
Epoch 11 Step 1301 Train Loss: 0.5815
Epoch 11 Step 1351 Train Loss: 0.4841
Epoch 11 Step 1401 Train Loss: 0.5241
Epoch 11 Step 1451 Train Loss: 0.5189
Epoch 11 Step 1501 Train Loss: 0.4648
Epoch 11 Step 1551 Train Loss: 0.5942
Epoch 11: Train Overall MSE: 0.0024 Validation Overall MSE: 0.0035.
Train Top 20 DE MSE: 0.0723 Validation Top 20 DE MSE: 0.2305.
Epoch 12 Step 1 Train Loss: 0.5994
Epoch 12 Step 51 Train Loss: 0.4946
Epoch 12 Step 101 Train Loss: 0.4670
Epoch 12 Step 151 Train Loss: 0.4933
Epoch 12 Step 201 Train Loss: 0.4734
Epoch 12 Step 251 Train Loss: 0.5173
Epoch 12 Step 301 Train Loss: 0.4924
Epoch 12 Step 351 Train Loss: 0.4622
Epoch 12 Step 401 Train Loss: 0.5796
Epoch 12 Step 451 Train Loss: 0.6046
Epoch 12 Step 501 Train Loss: 0.5381
Epoch 12 Step 551 Train Loss: 0.4838
Epoch 12 Step 601 Train Loss: 0.4648
Epoch 12 Step 651 Train Loss: 0.5115
Epoch 12 Step 701 Train Loss: 0.4992
Epoch 12 Step 751 Train Loss: 0.5021
Epoch 12 Step 801 Train Loss: 0.5137
Epoch 12 Step 851 Train Loss: 0.5500
Epoch 12 Step 901 Train Loss: 0.4639
Epoch 12 Step 951 Train Loss: 0.5005
Epoch 12 Step 1001 Train Loss: 0.4375
Epoch 12 Step 1051 Train Loss: 0.4422
Epoch 12 Step 1101 Train Loss: 0.4780
Epoch 12 Step 1151 Train Loss: 0.4813
Epoch 12 Step 1201 Train Loss: 0.4826
Epoch 12 Step 1251 Train Loss: 0.4700
Epoch 12 Step 1301 Train Loss: 0.5302
Epoch 12 Step 1351 Train Loss: 0.4873
Epoch 12 Step 1401 Train Loss: 0.4122
Epoch 12 Step 1451 Train Loss: 0.4884
Epoch 12 Step 1501 Train Loss: 0.4491
Epoch 12 Step 1551 Train Loss: 0.5082
Epoch 12: Train Overall MSE: 0.0023 Validation Overall MSE: 0.0034.
Train Top 20 DE MSE: 0.0725 Validation Top 20 DE MSE: 0.2270.
Epoch 13 Step 1 Train Loss: 0.4695
Epoch 13 Step 51 Train Loss: 0.5320
Epoch 13 Step 101 Train Loss: 0.4369
Epoch 13 Step 151 Train Loss: 0.4601
Epoch 13 Step 201 Train Loss: 0.4454
Epoch 13 Step 251 Train Loss: 0.5158
Epoch 13 Step 301 Train Loss: 0.5343
Epoch 13 Step 351 Train Loss: 0.4689
Epoch 13 Step 401 Train Loss: 0.5865
Epoch 13 Step 451 Train Loss: 0.4759
Epoch 13 Step 501 Train Loss: 0.5445
Epoch 13 Step 551 Train Loss: 0.4883
Epoch 13 Step 601 Train Loss: 0.4579
Epoch 13 Step 651 Train Loss: 0.5374
Epoch 13 Step 701 Train Loss: 0.5348
Epoch 13 Step 751 Train Loss: 0.5266
Epoch 13 Step 801 Train Loss: 0.5008
Epoch 13 Step 851 Train Loss: 0.5026
Epoch 13 Step 901 Train Loss: 0.4869
Epoch 13 Step 951 Train Loss: 0.4501
Epoch 13 Step 1001 Train Loss: 0.5249
Epoch 13 Step 1051 Train Loss: 0.4773
Epoch 13 Step 1101 Train Loss: 0.4946
Epoch 13 Step 1151 Train Loss: 0.5900
Epoch 13 Step 1201 Train Loss: 0.5285
Epoch 13 Step 1251 Train Loss: 0.5947
Epoch 13 Step 1301 Train Loss: 0.4728
Epoch 13 Step 1351 Train Loss: 0.5062
Epoch 13 Step 1401 Train Loss: 0.5063
Epoch 13 Step 1451 Train Loss: 0.5297
Epoch 13 Step 1501 Train Loss: 0.4289
Epoch 13 Step 1551 Train Loss: 0.5304
Epoch 13: Train Overall MSE: 0.0023 Validation Overall MSE: 0.0034.
Train Top 20 DE MSE: 0.0751 Validation Top 20 DE MSE: 0.2303.
Epoch 14 Step 1 Train Loss: 0.5012
Epoch 14 Step 51 Train Loss: 0.4792
Epoch 14 Step 101 Train Loss: 0.4759
Epoch 14 Step 151 Train Loss: 0.4755
Epoch 14 Step 201 Train Loss: 0.5439
Epoch 14 Step 251 Train Loss: 0.4463
Epoch 14 Step 301 Train Loss: 0.5069
Epoch 14 Step 351 Train Loss: 0.4858
Epoch 14 Step 401 Train Loss: 0.4774
Epoch 14 Step 451 Train Loss: 0.6519
Epoch 14 Step 501 Train Loss: 0.5189
Epoch 14 Step 551 Train Loss: 0.5058
Epoch 14 Step 601 Train Loss: 0.4925
Epoch 14 Step 651 Train Loss: 0.5230
Epoch 14 Step 701 Train Loss: 0.5233
Epoch 14 Step 751 Train Loss: 0.5780
Epoch 14 Step 801 Train Loss: 0.5373
Epoch 14 Step 851 Train Loss: 0.5396
Epoch 14 Step 901 Train Loss: 0.4729
Epoch 14 Step 951 Train Loss: 0.4754
Epoch 14 Step 1001 Train Loss: 0.4608
Epoch 14 Step 1051 Train Loss: 0.4693
Epoch 14 Step 1101 Train Loss: 0.4915
Epoch 14 Step 1151 Train Loss: 0.4839
Epoch 14 Step 1201 Train Loss: 0.6270
Epoch 14 Step 1251 Train Loss: 0.5300
Epoch 14 Step 1301 Train Loss: 0.6540
Epoch 14 Step 1351 Train Loss: 0.5045
Epoch 14 Step 1401 Train Loss: 0.4565
Epoch 14 Step 1451 Train Loss: 0.6118
Epoch 14 Step 1501 Train Loss: 0.4864
Epoch 14 Step 1551 Train Loss: 0.5471
Epoch 14: Train Overall MSE: 0.0023 Validation Overall MSE: 0.0034.
Train Top 20 DE MSE: 0.0768 Validation Top 20 DE MSE: 0.2324.
Epoch 15 Step 1 Train Loss: 0.4911
Epoch 15 Step 51 Train Loss: 0.4813
Epoch 15 Step 101 Train Loss: 0.6267
Epoch 15 Step 151 Train Loss: 0.5121
Epoch 15 Step 201 Train Loss: 0.4772
Epoch 15 Step 251 Train Loss: 0.4936
Epoch 15 Step 301 Train Loss: 0.4571
Epoch 15 Step 351 Train Loss: 0.5849
Epoch 15 Step 401 Train Loss: 0.5369
Epoch 15 Step 451 Train Loss: 0.5897
Epoch 15 Step 501 Train Loss: 0.5443
Epoch 15 Step 551 Train Loss: 0.4954
Epoch 15 Step 601 Train Loss: 0.5386
Epoch 15 Step 651 Train Loss: 0.4657
Epoch 15 Step 701 Train Loss: 0.4892
Epoch 15 Step 751 Train Loss: 0.5136
Epoch 15 Step 801 Train Loss: 0.4623
Epoch 15 Step 851 Train Loss: 0.4125
Epoch 15 Step 901 Train Loss: 0.5509
Epoch 15 Step 951 Train Loss: 0.5287
Epoch 15 Step 1001 Train Loss: 0.5872
Epoch 15 Step 1051 Train Loss: 0.5120
Epoch 15 Step 1101 Train Loss: 0.4880
Epoch 15 Step 1151 Train Loss: 0.5665
Epoch 15 Step 1201 Train Loss: 0.4693
Epoch 15 Step 1251 Train Loss: 0.5363
Epoch 15 Step 1301 Train Loss: 0.5187
Epoch 15 Step 1351 Train Loss: 0.5526
Epoch 15 Step 1401 Train Loss: 0.4476
Epoch 15 Step 1451 Train Loss: 0.6105
Epoch 15 Step 1501 Train Loss: 0.4658
Epoch 15 Step 1551 Train Loss: 0.5177
Epoch 15: Train Overall MSE: 0.0023 Validation Overall MSE: 0.0035.
Train Top 20 DE MSE: 0.0769 Validation Top 20 DE MSE: 0.2323.
Epoch 16 Step 1 Train Loss: 0.5279
Epoch 16 Step 51 Train Loss: 0.5004
Epoch 16 Step 101 Train Loss: 0.5234
Epoch 16 Step 151 Train Loss: 0.4806
Epoch 16 Step 201 Train Loss: 0.5077
Epoch 16 Step 251 Train Loss: 0.5337
Epoch 16 Step 301 Train Loss: 0.4773
Epoch 16 Step 351 Train Loss: 0.4436
Epoch 16 Step 401 Train Loss: 0.5184
Epoch 16 Step 451 Train Loss: 0.5108
Epoch 16 Step 501 Train Loss: 0.4702

2026-10-06 17:05:50,246 INFO lasser.utils: [gears_train] done in 4975.1s, peak CUDA memory 0.87 GB
2026-10-06 17:05:50,270 INFO lasser.utils: [evaluate] start
2026-10-06 17:08:50,740 INFO lasser.evaluation: test (eval.py): pearson_delta=0.5338 mse_top20_de=0.2105 nmse_top20_de=1.4284 over 107 perts
2026-10-06 17:08:50,741 INFO lasser.evaluation:   combo_seen0    pearson_delta=0.6349 mse_top20_de=0.1419 (9 perts)
2026-10-06 17:08:50,741 INFO lasser.evaluation:   combo_seen1    pearson_delta=0.5586 mse_top20_de=0.2077 (43 perts)
2026-10-06 17:08:50,742 INFO lasser.evaluation:   combo_seen2    pearson_delta=0.5626 mse_top20_de=0.2429 (19 perts)
2026-10-06 17:08:50,743 INFO lasser.evaluation:   unseen_single  pearson_delta=0.4636 mse_top20_de=0.2139 (36 perts)
2026-10-06 17:08:50,745 INFO lasser.utils: [evaluate] done in 180.5s, peak CUDA memory 1.15 GB
2026-10-06 17:08:50,765 INFO lasser.tracking: appended run f71d4a24 to /kaggle/working/runs/runs.csv

'/kaggle/working/runs/norman_seed1_base_20261006-154235'

In [7]:
# 6. Graph learning: GSR-refined co-expression graph (defaults from the plan, section 11).
gl = run_experiment(LasserConfig(**common, graph_learning=True, gsr=GSRConfig()), pert_data)
gl["run_dir"], gl["checks"]["h2"], gl["checks"]["refine"]

2026-10-06 17:08:50,840 INFO lasser.tracking: run 493c3ac6 -> /kaggle/working/runs/norman_seed1_gl_20261006-170850
2026-10-06 17:08:50,849 INFO lasser.run: device: cuda:0 (Tesla T4, 14.6 GB) (GEARS training and GSR graph learning)

Local copy of split is detected. Loading...
Simulation split test composition:
combo_seen0:9
combo_seen1:43
combo_seen2:19
unseen_single:36
Done!
Creating dataloaders....
Done!

here1
2026-10-06 17:08:50,864 INFO lasser.tracking: split hash f93e7d59ee239960 (copied ['norman_simulation_1_0.75_subgroup.pkl', 'norman_simulation_1_0.75.pkl'])
2026-10-06 17:08:50,867 INFO lasser.utils: [gsr_graph] start
2026-10-06 17:08:50,923 INFO lasser.graph: GSR graph learning on cuda:0 (Tesla T4, 14.6 GB)
2026-10-06 17:08:50,924 INFO lasser.utils: [gsr/data] start
2026-10-06 17:08:51,456 INFO lasser.data: training cells: 49849 (A0 subset 38824, H1 24957, H2 24892) over 138 training perturbations
2026-10-06 17:08:51,457 INFO lasser.utils: [gsr/data] done in 0.5s, peak CUDA memory 0.05 GB
2026-10-06 17:08:51,458 INFO lasser.utils: [gsr/views] start
2026-10-06 17:09:01,444 INFO lasser.data: metacells: 49849 cells -> 500 metacells
2026-10-06 17:09:02,773 INFO lasser.views: view E: dim 64, missing genes 234
2026-10-06 17:09:03,271 INFO lasser.views: view R: dim 32, missing genes 271
2026-10-06 17:09:03,669 INFO lasser.views: deepwalk epoch 1: loss 1.6828 over 1064200 pairs
2026-10-06 17:09:03,979 INFO lasser.views: deepwalk epoch 2: loss 0.0779 over 1064200 pairs
2026-10-06 17:09:04,269 INFO lasser.views: deepwalk epoch 3: loss 0.0568 over 1064200 pairs
2026-10-06 17:09:04,271 INFO lasser.views: view S: dim 64, missing genes 4419
2026-10-06 17:09:04,273 INFO lasser.utils: [gsr/views] done in 12.8s, peak CUDA memory 0.11 GB
2026-10-06 17:09:04,273 INFO lasser.utils: [gsr/positives] start
2026-10-06 17:09:10,470 INFO lasser.pretrain: positives: {'h1_cells_used': 19434, 'candidate_pairs': 1070, 'bootstrap_kept_pairs': 564, 'positive_pairs': 564}
2026-10-06 17:09:10,472 INFO lasser.utils: [gsr/positives] done in 6.2s, peak CUDA memory 1.61 GB
2026-10-06 17:09:10,472 INFO lasser.utils: [gsr/pretrain] start
2026-10-06 17:09:10,496 INFO lasser.pretrain: link AUC of raw view features (baseline): {'E': 0.9703, 'R': 0.8699, 'S': 0.7321, 'combined': 0.9697}
2026-10-06 17:09:10,939 INFO lasser.pretrain: pretrain step 10 (epoch 10): loss 4.6834 intra 4.4926 inter 5.1170 var 0.3473 | AUC {'E': 0.9684, 'R': 0.9665, 'S': 0.2286, 'combined': 0.9879} | cos_std {'E': 0.28, 'R': 0.35, 'S': 0.196}
2026-10-06 17:09:11,288 INFO lasser.pretrain: pretrain step 20 (epoch 20): loss 4.0445 intra 3.8817 inter 4.4139 var 0.2973 | AUC {'E': 0.9672, 'R': 0.9703, 'S': 0.2283, 'combined': 0.9872} | cos_std {'E': 0.313, 'R': 0.319, 'S': 0.296}
2026-10-06 17:09:11,623 INFO lasser.pretrain: pretrain step 30 (epoch 30): loss 3.7153 intra 3.5704 inter 4.0439 var 0.2649 | AUC {'E': 0.9595, 'R': 0.9592, 'S': 0.2436, 'combined': 0.9761} | cos_std {'E': 0.354, 'R': 0.354, 'S': 0.431}
2026-10-06 17:09:11,960 INFO lasser.pretrain: pretrain step 40 (epoch 40): loss 3.3569 intra 3.2225 inter 3.6610 var 0.2474 | AUC {'E': 0.9646, 'R': 0.9617, 'S': 0.2309, 'combined': 0.9799} | cos_std {'E': 0.328, 'R': 0.354, 'S': 0.416}
2026-10-06 17:09:12,318 INFO lasser.pretrain: pretrain step 50 (epoch 50): loss 3.2379 intra 3.1357 inter 3.4527 var 0.2291 | AUC {'E': 0.9707, 'R': 0.9601, 'S': 0.2443, 'combined': 0.9812} | cos_std {'E': 0.304, 'R': 0.343, 'S': 0.461}
2026-10-06 17:09:12,654 INFO lasser.pretrain: pretrain step 60 (epoch 60): loss 3.0067 intra 2.8902 inter 3.2716 var 0.2111 | AUC {'E': 0.9691, 'R': 0.9636, 'S': 0.2443, 'combined': 0.9786} | cos_std {'E': 0.301, 'R': 0.323, 'S': 0.459}
2026-10-06 17:09:12,655 INFO lasser.pretrain: early stop at step 60 (best step 10, AUC 0.9879)
2026-10-06 17:09:12,674 INFO lasser.pretrain: pretraining done: best step 10, held-out link AUC 0.9879 (raw features 0.9697)
2026-10-06 17:09:12,679 INFO lasser.utils: [gsr/pretrain] done in 2.2s, peak CUDA memory 0.28 GB
2026-10-06 17:09:12,679 INFO lasser.utils: [gsr/refine] start
2026-10-06 17:09:12,762 INFO lasser.refine: refinement: {'a0_edges': 6364, 'removed': 20, 'added_directed': 38848, 'topup_directed': 0, 'refined_edges': 45192, 'new_weight_mean': 0.24045628309249878, 'a0_weight_mean': 0.5615240931510925}
2026-10-06 17:09:12,763 INFO lasser.utils: [gsr/refine] done in 0.1s, peak CUDA memory 0.11 GB
2026-10-06 17:09:12,764 INFO lasser.utils: [gsr/checks] start
2026-10-06 17:09:13,915 INFO lasser.checks: graph checks: H2 {'threshold': 0.2, 'hit_rate_added': 0.036, 'hit_rate_added_only': 0.036, 'hit_rate_topup': nan, 'hit_rate_degree_matched_random': 0.002, 'hit_rate_a0': 0.581, 'hit_rate_removed': 0.75, 'passes': True} | coverage {'low_degree_genes': 4935, 'low_degree_mean_degree_a0': 0.16757852077001012, 'low_degree_mean_degree_refined': 8.11631205673759, 'undirected_isolated_a0': 4419, 'undirected_isolated_refined': 0} | jaccard 0.032 | collapse ok True
2026-10-06 17:09:13,919 INFO lasser.utils: [gsr/checks] done in 1.2s, peak CUDA memory 1.18 GB
2026-10-06 17:09:14,016 INFO lasser.graph: GSR graph cached at /kaggle/working/cache/gsr/norman_simulation_seed1_0.75_acff059d6c09
2026-10-06 17:09:14,018 INFO lasser.utils: [gsr_graph] done in 23.2s, peak CUDA memory 1.18 GB
2026-10-06 17:09:14,020 INFO lasser.utils: [gears_init] start

Found local copy...

2026-10-06 17:09:32,830 INFO lasser.utils: [gears_init] done in 18.8s, peak CUDA memory 0.08 GB
2026-10-06 17:09:32,835 INFO lasser.run: co-expression graph used (gsr_refined): {'num_nodes': 5045, 'num_edges': 45192, 'num_self_loops': 4699, 'degree_min': 5, 'degree_median': 7.0, 'degree_mean': 8.026362735381566, 'degree_max': 25, 'degree_gini': 0.20116415036019025, 'isolated_genes': 0}
2026-10-06 17:09:32,924 INFO lasser.run: training GEARS on cuda:0 (Tesla T4, 14.6 GB) for 20 epochs
2026-10-06 17:09:32,925 INFO lasser.utils: [gears_train] start

Start Training...
Epoch 1 Step 1 Train Loss: 0.5244
Epoch 1 Step 51 Train Loss: 0.6062
Epoch 1 Step 101 Train Loss: 0.5209
Epoch 1 Step 151 Train Loss: 0.5244
Epoch 1 Step 201 Train Loss: 0.4638
Epoch 1 Step 251 Train Loss: 0.5955
Epoch 1 Step 301 Train Loss: 0.4118
Epoch 1 Step 351 Train Loss: 0.5500
Epoch 1 Step 401 Train Loss: 0.5074
Epoch 1 Step 451 Train Loss: 0.5306
Epoch 1 Step 501 Train Loss: 0.4490
Epoch 1 Step 551 Train Loss: 0.6113
Epoch 1 Step 601 Train Loss: 0.4674
Epoch 1 Step 651 Train Loss: 0.5061
Epoch 1 Step 701 Train Loss: 0.4643
Epoch 1 Step 751 Train Loss: 0.4464
Epoch 1 Step 801 Train Loss: 0.4670
Epoch 1 Step 851 Train Loss: 0.4354
Epoch 1 Step 901 Train Loss: 0.5447
Epoch 1 Step 951 Train Loss: 0.4254
Epoch 1 Step 1001 Train Loss: 0.4187
Epoch 1 Step 1051 Train Loss: 0.4877
Epoch 1 Step 1101 Train Loss: 0.5040
Epoch 1 Step 1151 Train Loss: 0.4317
Epoch 1 Step 1201 Train Loss: 0.4371
Epoch 1 Step 1251 Train Loss: 0.4386
Epoch 1 Step 1301 Train Loss: 0.4777
Epoch 1 Step 1351 Train Loss: 0.4459
Epoch 1 Step 1401 Train Loss: 0.4198
Epoch 1 Step 1451 Train Loss: 0.4389
Epoch 1 Step 1501 Train Loss: 0.4372
Epoch 1 Step 1551 Train Loss: 0.4670
Epoch 1: Train Overall MSE: 0.0032 Validation Overall MSE: 0.0041.
Train Top 20 DE MSE: 0.1239 Validation Top 20 DE MSE: 0.2875.
Epoch 2 Step 1 Train Loss: 0.5267
Epoch 2 Step 51 Train Loss: 0.4479
Epoch 2 Step 101 Train Loss: 0.4425
Epoch 2 Step 151 Train Loss: 0.4678
Epoch 2 Step 201 Train Loss: 0.5735
Epoch 2 Step 251 Train Loss: 0.4346
Epoch 2 Step 301 Train Loss: 0.5240
Epoch 2 Step 351 Train Loss: 0.4180
Epoch 2 Step 401 Train Loss: 0.4760
Epoch 2 Step 451 Train Loss: 0.4116
Epoch 2 Step 501 Train Loss: 0.4733
Epoch 2 Step 551 Train Loss: 0.5249
Epoch 2 Step 601 Train Loss: 0.6046
Epoch 2 Step 651 Train Loss: 0.3966
Epoch 2 Step 701 Train Loss: 0.5389
Epoch 2 Step 751 Train Loss: 0.5237
Epoch 2 Step 801 Train Loss: 0.5271
Epoch 2 Step 851 Train Loss: 0.4704
Epoch 2 Step 901 Train Loss: 0.5777
Epoch 2 Step 951 Train Loss: 0.4324
Epoch 2 Step 1001 Train Loss: 0.4609
Epoch 2 Step 1051 Train Loss: 0.4807
Epoch 2 Step 1101 Train Loss: 0.5110
Epoch 2 Step 1151 Train Loss: 0.4992
Epoch 2 Step 1201 Train Loss: 0.4527
Epoch 2 Step 1251 Train Loss: 0.4775
Epoch 2 Step 1301 Train Loss: 0.6758
Epoch 2 Step 1351 Train Loss: 0.4442
Epoch 2 Step 1401 Train Loss: 0.6072
Epoch 2 Step 1451 Train Loss: 0.5310
Epoch 2 Step 1501 Train Loss: 0.5554
Epoch 2 Step 1551 Train Loss: 0.4054
Epoch 2: Train Overall MSE: 0.0040 Validation Overall MSE: 0.0048.
Train Top 20 DE MSE: 0.1317 Validation Top 20 DE MSE: 0.3456.
Epoch 3 Step 1 Train Loss: 0.5326
Epoch 3 Step 51 Train Loss: 0.4813
Epoch 3 Step 101 Train Loss: 0.5189
Epoch 3 Step 151 Train Loss: 0.4733
Epoch 3 Step 201 Train Loss: 0.5251
Epoch 3 Step 251 Train Loss: 0.5181
Epoch 3 Step 301 Train Loss: 0.4992
Epoch 3 Step 351 Train Loss: 0.5423
Epoch 3 Step 401 Train Loss: 0.5746
Epoch 3 Step 451 Train Loss: 0.5461
Epoch 3 Step 501 Train Loss: 0.4851
Epoch 3 Step 551 Train Loss: 0.4608
Epoch 3 Step 601 Train Loss: 0.4401
Epoch 3 Step 651 Train Loss: 0.4499
Epoch 3 Step 701 Train Loss: 0.4676
Epoch 3 Step 751 Train Loss: 0.5137
Epoch 3 Step 801 Train Loss: 0.4948
Epoch 3 Step 851 Train Loss: 0.5046
Epoch 3 Step 901 Train Loss: 0.4848
Epoch 3 Step 951 Train Loss: 0.4357
Epoch 3 Step 1001 Train Loss: 0.4652
Epoch 3 Step 1051 Train Loss: 0.4859
Epoch 3 Step 1101 Train Loss: 0.5394
Epoch 3 Step 1151 Train Loss: 0.5188
Epoch 3 Step 1201 Train Loss: 0.5118
Epoch 3 Step 1251 Train Loss: 0.5224
Epoch 3 Step 1301 Train Loss: 0.6009
Epoch 3 Step 1351 Train Loss: 0.5052
Epoch 3 Step 1401 Train Loss: 0.4380
Epoch 3 Step 1451 Train Loss: 0.4405
Epoch 3 Step 1501 Train Loss: 0.4350
Epoch 3 Step 1551 Train Loss: 0.5374
Epoch 3: Train Overall MSE: 0.0024 Validation Overall MSE: 0.0034.
Train Top 20 DE MSE: 0.0868 Validation Top 20 DE MSE: 0.2366.
Epoch 4 Step 1 Train Loss: 0.5468
Epoch 4 Step 51 Train Loss: 0.5147
Epoch 4 Step 101 Train Loss: 0.4795
Epoch 4 Step 151 Train Loss: 0.6198
Epoch 4 Step 201 Train Loss: 0.4944
Epoch 4 Step 251 Train Loss: 0.4797
Epoch 4 Step 301 Train Loss: 0.4981
Epoch 4 Step 351 Train Loss: 0.5029
Epoch 4 Step 401 Train Loss: 0.5258
Epoch 4 Step 451 Train Loss: 0.4940
Epoch 4 Step 501 Train Loss: 0.4980
Epoch 4 Step 551 Train Loss: 0.4751
Epoch 4 Step 601 Train Loss: 0.4346
Epoch 4 Step 651 Train Loss: 0.4754
Epoch 4 Step 701 Train Loss: 0.5274
Epoch 4 Step 751 Train Loss: 0.4648
Epoch 4 Step 801 Train Loss: 0.5109
Epoch 4 Step 851 Train Loss: 0.4447
Epoch 4 Step 901 Train Loss: 0.5115
Epoch 4 Step 951 Train Loss: 0.5108
Epoch 4 Step 1001 Train Loss: 0.5734
Epoch 4 Step 1051 Train Loss: 0.4985
Epoch 4 Step 1101 Train Loss: 0.5074
Epoch 4 Step 1151 Train Loss: 0.5083
Epoch 4 Step 1201 Train Loss: 0.4754
Epoch 4 Step 1251 Train Loss: 0.5228
Epoch 4 Step 1301 Train Loss: 0.5073
Epoch 4 Step 1351 Train Loss: 0.4415
Epoch 4 Step 1401 Train Loss: 0.5546
Epoch 4 Step 1451 Train Loss: 0.4786
Epoch 4 Step 1501 Train Loss: 0.4947
Epoch 4 Step 1551 Train Loss: 0.4990
Epoch 4: Train Overall MSE: 0.0024 Validation Overall MSE: 0.0037.
Train Top 20 DE MSE: 0.0926 Validation Top 20 DE MSE: 0.2610.
Epoch 5 Step 1 Train Loss: 0.6224
Epoch 5 Step 51 Train Loss: 0.4696
Epoch 5 Step 101 Train Loss: 0.4851
Epoch 5 Step 151 Train Loss: 0.5063
Epoch 5 Step 201 Train Loss: 0.4767
Epoch 5 Step 251 Train Loss: 0.5142
Epoch 5 Step 301 Train Loss: 0.4761
Epoch 5 Step 351 Train Loss: 0.5845
Epoch 5 Step 401 Train Loss: 0.5057
Epoch 5 Step 451 Train Loss: 0.5504
Epoch 5 Step 501 Train Loss: 0.5439
Epoch 5 Step 551 Train Loss: 0.5355
Epoch 5 Step 601 Train Loss: 0.4805
Epoch 5 Step 651 Train Loss: 0.5680
Epoch 5 Step 701 Train Loss: 0.5581
Epoch 5 Step 751 Train Loss: 0.4934
Epoch 5 Step 801 Train Loss: 0.4673
Epoch 5 Step 851 Train Loss: 0.5033
Epoch 5 Step 901 Train Loss: 0.4968
Epoch 5 Step 951 Train Loss: 0.4716
Epoch 5 Step 1001 Train Loss: 0.5103
Epoch 5 Step 1051 Train Loss: 0.5709
Epoch 5 Step 1101 Train Loss: 0.5899
Epoch 5 Step 1151 Train Loss: 0.5448
Epoch 5 Step 1201 Train Loss: 0.5646
Epoch 5 Step 1251 Train Loss: 0.5717
Epoch 5 Step 1301 Train Loss: 0.5213
Epoch 5 Step 1351 Train Loss: 0.5302
Epoch 5 Step 1401 Train Loss: 0.4807
Epoch 5 Step 1451 Train Loss: 0.5516
Epoch 5 Step 1501 Train Loss: 0.5007
Epoch 5 Step 1551 Train Loss: 0.4679
Epoch 5: Train Overall MSE: 0.0023 Validation Overall MSE: 0.0033.
Train Top 20 DE MSE: 0.0742 Validation Top 20 DE MSE: 0.2097.
Epoch 6 Step 1 Train Loss: 0.4288
Epoch 6 Step 51 Train Loss: 0.5250
Epoch 6 Step 101 Train Loss: 0.4538
Epoch 6 Step 151 Train Loss: 0.5016
Epoch 6 Step 201 Train Loss: 0.4689
Epoch 6 Step 251 Train Loss: 0.5069
Epoch 6 Step 301 Train Loss: 0.5579
Epoch 6 Step 351 Train Loss: 0.5138
Epoch 6 Step 401 Train Loss: 0.5121
Epoch 6 Step 451 Train Loss: 0.4712
Epoch 6 Step 501 Train Loss: 0.4432
Epoch 6 Step 551 Train Loss: 0.4603
Epoch 6 Step 601 Train Loss: 0.4626
Epoch 6 Step 651 Train Loss: 0.5649
Epoch 6 Step 701 Train Loss: 0.5273
Epoch 6 Step 751 Train Loss: 0.5665
Epoch 6 Step 801 Train Loss: 0.4584
Epoch 6 Step 851 Train Loss: 0.5346
Epoch 6 Step 901 Train Loss: 0.4661
Epoch 6 Step 951 Train Loss: 0.4926
Epoch 6 Step 1001 Train Loss: 0.5204
Epoch 6 Step 1051 Train Loss: 0.4836
Epoch 6 Step 1101 Train Loss: 0.4654
Epoch 6 Step 1151 Train Loss: 0.5304
Epoch 6 Step 1201 Train Loss: 0.4821
Epoch 6 Step 1251 Train Loss: 0.5326
Epoch 6 Step 1301 Train Loss: 0.4460
Epoch 6 Step 1351 Train Loss: 0.4507
Epoch 6 Step 1401 Train Loss: 0.5345
Epoch 6 Step 1451 Train Loss: 0.5980
Epoch 6 Step 1501 Train Loss: 0.5550
Epoch 6 Step 1551 Train Loss: 0.5942
Epoch 6: Train Overall MSE: 0.0021 Validation Overall MSE: 0.0032.
Train Top 20 DE MSE: 0.0735 Validation Top 20 DE MSE: 0.2126.
Epoch 7 Step 1 Train Loss: 0.5011
Epoch 7 Step 51 Train Loss: 0.4876
Epoch 7 Step 101 Train Loss: 0.5212
Epoch 7 Step 151 Train Loss: 0.5129
Epoch 7 Step 201 Train Loss: 0.4802
Epoch 7 Step 251 Train Loss: 0.4849
Epoch 7 Step 301 Train Loss: 0.4851
Epoch 7 Step 351 Train Loss: 0.4880
Epoch 7 Step 401 Train Loss: 0.5151
Epoch 7 Step 451 Train Loss: 0.4974
Epoch 7 Step 501 Train Loss: 0.5553
Epoch 7 Step 551 Train Loss: 0.5337
Epoch 7 Step 601 Train Loss: 0.4565
Epoch 7 Step 651 Train Loss: 0.4637
Epoch 7 Step 701 Train Loss: 0.4879
Epoch 7 Step 751 Train Loss: 0.5233
Epoch 7 Step 801 Train Loss: 0.5278
Epoch 7 Step 851 Train Loss: 0.5600
Epoch 7 Step 901 Train Loss: 0.5356
Epoch 7 Step 951 Train Loss: 0.5456
Epoch 7 Step 1001 Train Loss: 0.4939
Epoch 7 Step 1051 Train Loss: 0.5157
Epoch 7 Step 1101 Train Loss: 0.4348
Epoch 7 Step 1151 Train Loss: 0.4783
Epoch 7 Step 1201 Train Loss: 0.5279
Epoch 7 Step 1251 Train Loss: 0.4896
Epoch 7 Step 1301 Train Loss: 0.4813
Epoch 7 Step 1351 Train Loss: 0.5085
Epoch 7 Step 1401 Train Loss: 0.5732
Epoch 7 Step 1451 Train Loss: 0.5208
Epoch 7 Step 1501 Train Loss: 0.4920
Epoch 7 Step 1551 Train Loss: 0.5234
Epoch 7: Train Overall MSE: 0.0022 Validation Overall MSE: 0.0035.
Train Top 20 DE MSE: 0.0715 Validation Top 20 DE MSE: 0.2334.
Epoch 8 Step 1 Train Loss: 0.5081
Epoch 8 Step 51 Train Loss: 0.4870
Epoch 8 Step 101 Train Loss: 0.5727
Epoch 8 Step 151 Train Loss: 0.5073
Epoch 8 Step 201 Train Loss: 0.5048
Epoch 8 Step 251 Train Loss: 0.5044
Epoch 8 Step 301 Train Loss: 0.5449
Epoch 8 Step 351 Train Loss: 0.4840
Epoch 8 Step 401 Train Loss: 0.5181
Epoch 8 Step 451 Train Loss: 0.5865
Epoch 8 Step 501 Train Loss: 0.5240
Epoch 8 Step 551 Train Loss: 0.5170
Epoch 8 Step 601 Train Loss: 0.6338
Epoch 8 Step 651 Train Loss: 0.5724
Epoch 8 Step 701 Train Loss: 0.5506
Epoch 8 Step 751 Train Loss: 0.5151
Epoch 8 Step 801 Train Loss: 0.6179
Epoch 8 Step 851 Train Loss: 0.5703
Epoch 8 Step 901 Train Loss: 0.6118
Epoch 8 Step 951 Train Loss: 0.6048
Epoch 8 Step 1001 Train Loss: 0.5426
Epoch 8 Step 1051 Train Loss: 0.4881
Epoch 8 Step 1101 Train Loss: 0.5718
Epoch 8 Step 1151 Train Loss: 0.5018
Epoch 8 Step 1201 Train Loss: 0.5305
Epoch 8 Step 1251 Train Loss: 0.4630
Epoch 8 Step 1301 Train Loss: 0.4671
Epoch 8 Step 1351 Train Loss: 0.4771
Epoch 8 Step 1401 Train Loss: 0.5863
Epoch 8 Step 1451 Train Loss: 0.5060
Epoch 8 Step 1501 Train Loss: 0.5214
Epoch 8 Step 1551 Train Loss: 0.4921
Epoch 8: Train Overall MSE: 0.0021 Validation Overall MSE: 0.0033.
Train Top 20 DE MSE: 0.0716 Validation Top 20 DE MSE: 0.2269.
Epoch 9 Step 1 Train Loss: 0.4479
Epoch 9 Step 51 Train Loss: 0.5245
Epoch 9 Step 101 Train Loss: 0.5206
Epoch 9 Step 151 Train Loss: 0.5964
Epoch 9 Step 201 Train Loss: 0.5394
Epoch 9 Step 251 Train Loss: 0.5219
Epoch 9 Step 301 Train Loss: 0.4750
Epoch 9 Step 351 Train Loss: 0.4961
Epoch 9 Step 401 Train Loss: 0.6330
Epoch 9 Step 451 Train Loss: 0.5258
Epoch 9 Step 501 Train Loss: 0.5002
Epoch 9 Step 551 Train Loss: 0.5172
Epoch 9 Step 601 Train Loss: 0.5139
Epoch 9 Step 651 Train Loss: 0.6127
Epoch 9 Step 701 Train Loss: 0.4913
Epoch 9 Step 751 Train Loss: 0.4733
Epoch 9 Step 801 Train Loss: 0.4948
Epoch 9 Step 851 Train Loss: 0.5413
Epoch 9 Step 901 Train Loss: 0.4788
Epoch 9 Step 951 Train Loss: 0.4814
Epoch 9 Step 1001 Train Loss: 0.5433
Epoch 9 Step 1051 Train Loss: 0.5730
Epoch 9 Step 1101 Train Loss: 0.5756
Epoch 9 Step 1151 Train Loss: 0.5970
Epoch 9 Step 1201 Train Loss: 0.5465
Epoch 9 Step 1251 Train Loss: 0.6311
Epoch 9 Step 1301 Train Loss: 0.4861
Epoch 9 Step 1351 Train Loss: 0.4957
Epoch 9 Step 1401 Train Loss: 0.6066
Epoch 9 Step 1451 Train Loss: 0.5719
Epoch 9 Step 1501 Train Loss: 0.4867
Epoch 9 Step 1551 Train Loss: 0.5221
Epoch 9: Train Overall MSE: 0.0022 Validation Overall MSE: 0.0035.
Train Top 20 DE MSE: 0.0680 Validation Top 20 DE MSE: 0.2194.
Epoch 10 Step 1 Train Loss: 0.4487
Epoch 10 Step 51 Train Loss: 0.5304
Epoch 10 Step 101 Train Loss: 0.4523
Epoch 10 Step 151 Train Loss: 0.4977
Epoch 10 Step 201 Train Loss: 0.5321
Epoch 10 Step 251 Train Loss: 0.4378
Epoch 10 Step 301 Train Loss: 0.4962
Epoch 10 Step 351 Train Loss: 0.5214
Epoch 10 Step 401 Train Loss: 0.5212
Epoch 10 Step 451 Train Loss: 0.5408
Epoch 10 Step 501 Train Loss: 0.5121
Epoch 10 Step 551 Train Loss: 0.4787
Epoch 10 Step 601 Train Loss: 0.5698
Epoch 10 Step 651 Train Loss: 0.5548
Epoch 10 Step 701 Train Loss: 0.5686
Epoch 10 Step 751 Train Loss: 0.5251
Epoch 10 Step 801 Train Loss: 0.5937
Epoch 10 Step 851 Train Loss: 0.4581
Epoch 10 Step 901 Train Loss: 0.4949
Epoch 10 Step 951 Train Loss: 0.5367
Epoch 10 Step 1001 Train Loss: 0.4354
Epoch 10 Step 1051 Train Loss: 0.5099
Epoch 10 Step 1101 Train Loss: 0.4887
Epoch 10 Step 1151 Train Loss: 0.5077
Epoch 10 Step 1201 Train Loss: 0.4896
Epoch 10 Step 1251 Train Loss: 0.5036
Epoch 10 Step 1301 Train Loss: 0.4999
Epoch 10 Step 1351 Train Loss: 0.4282
Epoch 10 Step 1401 Train Loss: 0.4696
Epoch 10 Step 1451 Train Loss: 0.5184
Epoch 10 Step 1501 Train Loss: 0.4498
Epoch 10 Step 1551 Train Loss: 0.5533
Epoch 10: Train Overall MSE: 0.0020 Validation Overall MSE: 0.0033.
Train Top 20 DE MSE: 0.0774 Validation Top 20 DE MSE: 0.2231.
Epoch 11 Step 1 Train Loss: 0.5214
Epoch 11 Step 51 Train Loss: 0.5124
Epoch 11 Step 101 Train Loss: 0.4832
Epoch 11 Step 151 Train Loss: 0.5342
Epoch 11 Step 201 Train Loss: 0.5104
Epoch 11 Step 251 Train Loss: 0.4648
Epoch 11 Step 301 Train Loss: 0.5483
Epoch 11 Step 351 Train Loss: 0.5092
Epoch 11 Step 401 Train Loss: 0.5420
Epoch 11 Step 451 Train Loss: 0.4650
Epoch 11 Step 501 Train Loss: 0.4477
Epoch 11 Step 551 Train Loss: 0.5236
Epoch 11 Step 601 Train Loss: 0.4744
Epoch 11 Step 651 Train Loss: 0.4318
Epoch 11 Step 701 Train Loss: 0.5317
Epoch 11 Step 751 Train Loss: 0.4660
Epoch 11 Step 801 Train Loss: 0.5414
Epoch 11 Step 851 Train Loss: 0.5263
Epoch 11 Step 901 Train Loss: 0.5922
Epoch 11 Step 951 Train Loss: 0.4668
Epoch 11 Step 1001 Train Loss: 0.4762
Epoch 11 Step 1051 Train Loss: 0.4426
Epoch 11 Step 1101 Train Loss: 0.4322
Epoch 11 Step 1151 Train Loss: 0.5252
Epoch 11 Step 1201 Train Loss: 0.5256
Epoch 11 Step 1251 Train Loss: 0.4415
Epoch 11 Step 1301 Train Loss: 0.5831
Epoch 11 Step 1351 Train Loss: 0.4850
Epoch 11 Step 1401 Train Loss: 0.5208
Epoch 11 Step 1451 Train Loss: 0.5203
Epoch 11 Step 1501 Train Loss: 0.4627
Epoch 11 Step 1551 Train Loss: 0.5884
Epoch 11: Train Overall MSE: 0.0022 Validation Overall MSE: 0.0034.
Train Top 20 DE MSE: 0.0666 Validation Top 20 DE MSE: 0.2297.
Epoch 12 Step 1 Train Loss: 0.5969
Epoch 12 Step 51 Train Loss: 0.4916
Epoch 12 Step 101 Train Loss: 0.4621
Epoch 12 Step 151 Train Loss: 0.4952
Epoch 12 Step 201 Train Loss: 0.4724
Epoch 12 Step 251 Train Loss: 0.5177
Epoch 12 Step 301 Train Loss: 0.4906
Epoch 12 Step 351 Train Loss: 0.4595
Epoch 12 Step 401 Train Loss: 0.5769
Epoch 12 Step 451 Train Loss: 0.6042
Epoch 12 Step 501 Train Loss: 0.5417
Epoch 12 Step 551 Train Loss: 0.4859
Epoch 12 Step 601 Train Loss: 0.4646
Epoch 12 Step 651 Train Loss: 0.5081
Epoch 12 Step 701 Train Loss: 0.5005
Epoch 12 Step 751 Train Loss: 0.5059
Epoch 12 Step 801 Train Loss: 0.5127
Epoch 12 Step 851 Train Loss: 0.5483
Epoch 12 Step 901 Train Loss: 0.4627
Epoch 12 Step 951 Train Loss: 0.4988
Epoch 12 Step 1001 Train Loss: 0.4353
Epoch 12 Step 1051 Train Loss: 0.4411
Epoch 12 Step 1101 Train Loss: 0.4804
Epoch 12 Step 1151 Train Loss: 0.4814
Epoch 12 Step 1201 Train Loss: 0.4829
Epoch 12 Step 1251 Train Loss: 0.4670
Epoch 12 Step 1301 Train Loss: 0.5261
Epoch 12 Step 1351 Train Loss: 0.4882
Epoch 12 Step 1401 Train Loss: 0.4087
Epoch 12 Step 1451 Train Loss: 0.4900
Epoch 12 Step 1501 Train Loss: 0.4497
Epoch 12 Step 1551 Train Loss: 0.5090
Epoch 12: Train Overall MSE: 0.0022 Validation Overall MSE: 0.0034.
Train Top 20 DE MSE: 0.0657 Validation Top 20 DE MSE: 0.2210.
Epoch 13 Step 1 Train Loss: 0.4684
Epoch 13 Step 51 Train Loss: 0.5296
Epoch 13 Step 101 Train Loss: 0.4391
Epoch 13 Step 151 Train Loss: 0.4629
Epoch 13 Step 201 Train Loss: 0.4409
Epoch 13 Step 251 Train Loss: 0.5167
Epoch 13 Step 301 Train Loss: 0.5344
Epoch 13 Step 351 Train Loss: 0.4676
Epoch 13 Step 401 Train Loss: 0.5826
Epoch 13 Step 451 Train Loss: 0.4735
Epoch 13 Step 501 Train Loss: 0.5376
Epoch 13 Step 551 Train Loss: 0.4830
Epoch 13 Step 601 Train Loss: 0.4642
Epoch 13 Step 651 Train Loss: 0.5384
Epoch 13 Step 701 Train Loss: 0.5320
Epoch 13 Step 751 Train Loss: 0.5284
Epoch 13 Step 801 Train Loss: 0.5019
Epoch 13 Step 851 Train Loss: 0.5009
Epoch 13 Step 901 Train Loss: 0.4893
Epoch 13 Step 951 Train Loss: 0.4476
Epoch 13 Step 1001 Train Loss: 0.5207
Epoch 13 Step 1051 Train Loss: 0.4754
Epoch 13 Step 1101 Train Loss: 0.4982
Epoch 13 Step 1151 Train Loss: 0.5858
Epoch 13 Step 1201 Train Loss: 0.5272
Epoch 13 Step 1251 Train Loss: 0.5973
Epoch 13 Step 1301 Train Loss: 0.4701
Epoch 13 Step 1351 Train Loss: 0.4989
Epoch 13 Step 1401 Train Loss: 0.5033
Epoch 13 Step 1451 Train Loss: 0.5278
Epoch 13 Step 1501 Train Loss: 0.4287
Epoch 13 Step 1551 Train Loss: 0.5289
Epoch 13: Train Overall MSE: 0.0021 Validation Overall MSE: 0.0034.
Train Top 20 DE MSE: 0.0709 Validation Top 20 DE MSE: 0.2253.
Epoch 14 Step 1 Train Loss: 0.5008
Epoch 14 Step 51 Train Loss: 0.4818
Epoch 14 Step 101 Train Loss: 0.4753
Epoch 14 Step 151 Train Loss: 0.4691
Epoch 14 Step 201 Train Loss: 0.5394
Epoch 14 Step 251 Train Loss: 0.4447
Epoch 14 Step 301 Train Loss: 0.5087
Epoch 14 Step 351 Train Loss: 0.4841
Epoch 14 Step 401 Train Loss: 0.4765
Epoch 14 Step 451 Train Loss: 0.6545
Epoch 14 Step 501 Train Loss: 0.5147
Epoch 14 Step 551 Train Loss: 0.5042
Epoch 14 Step 601 Train Loss: 0.4913
Epoch 14 Step 651 Train Loss: 0.5232
Epoch 14 Step 701 Train Loss: 0.5236
Epoch 14 Step 751 Train Loss: 0.5785
Epoch 14 Step 801 Train Loss: 0.5348
Epoch 14 Step 851 Train Loss: 0.5405
Epoch 14 Step 901 Train Loss: 0.4783
Epoch 14 Step 951 Train Loss: 0.4774
Epoch 14 Step 1001 Train Loss: 0.4612
Epoch 14 Step 1051 Train Loss: 0.4670
Epoch 14 Step 1101 Train Loss: 0.4879
Epoch 14 Step 1151 Train Loss: 0.4820
Epoch 14 Step 1201 Train Loss: 0.6253
Epoch 14 Step 1251 Train Loss: 0.5340
Epoch 14 Step 1301 Train Loss: 0.6444
Epoch 14 Step 1351 Train Loss: 0.5039
Epoch 14 Step 1401 Train Loss: 0.4560
Epoch 14 Step 1451 Train Loss: 0.6035
Epoch 14 Step 1501 Train Loss: 0.4847
Epoch 14 Step 1551 Train Loss: 0.5480
Epoch 14: Train Overall MSE: 0.0021 Validation Overall MSE: 0.0033.
Train Top 20 DE MSE: 0.0734 Validation Top 20 DE MSE: 0.2256.
Epoch 15 Step 1 Train Loss: 0.4903
Epoch 15 Step 51 Train Loss: 0.4779
Epoch 15 Step 101 Train Loss: 0.6192
Epoch 15 Step 151 Train Loss: 0.5140
Epoch 15 Step 201 Train Loss: 0.4701
Epoch 15 Step 251 Train Loss: 0.4882
Epoch 15 Step 301 Train Loss: 0.4577
Epoch 15 Step 351 Train Loss: 0.5820
Epoch 15 Step 401 Train Loss: 0.5312
Epoch 15 Step 451 Train Loss: 0.5909
Epoch 15 Step 501 Train Loss: 0.5481
Epoch 15 Step 551 Train Loss: 0.4925
Epoch 15 Step 601 Train Loss: 0.5348
Epoch 15 Step 651 Train Loss: 0.4612
Epoch 15 Step 701 Train Loss: 0.4901
Epoch 15 Step 751 Train Loss: 0.5089
Epoch 15 Step 801 Train Loss: 0.4602
Epoch 15 Step 851 Train Loss: 0.4092
Epoch 15 Step 901 Train Loss: 0.5479
Epoch 15 Step 951 Train Loss: 0.5256
Epoch 15 Step 1001 Train Loss: 0.5867
Epoch 15 Step 1051 Train Loss: 0.5075
Epoch 15 Step 1101 Train Loss: 0.4855
Epoch 15 Step 1151 Train Loss: 0.5631
Epoch 15 Step 1201 Train Loss: 0.4726
Epoch 15 Step 1251 Train Loss: 0.5297
Epoch 15 Step 1301 Train Loss: 0.5162
Epoch 15 Step 1351 Train Loss: 0.5514
Epoch 15 Step 1401 Train Loss: 0.4501
Epoch 15 Step 1451 Train Loss: 0.6036
Epoch 15 Step 1501 Train Loss: 0.4633
Epoch 15 Step 1551 Train Loss: 0.5182
Epoch 15: Train Overall MSE: 0.0021 Validation Overall MSE: 0.0033.
Train Top 20 DE MSE: 0.0742 Validation Top 20 DE MSE: 0.2244.
Epoch 16 Step 1 Train Loss: 0.5243
Epoch 16 Step 51 Train Loss: 0.4891
Epoch 16 Step 101 Train Loss: 0.5197
Epoch 16 Step 151 Train Loss: 0.4837
Epoch 16 Step 201 Train Loss: 0.5102
Epoch 16 Step 251 Train Loss: 0.5346
Epoch 16 Step 301 Train Loss: 0.4790
Epoch 16 Step 351 Train Loss: 0.4407
Epoch 16 Step 401 Train Loss: 0.5166
Epoch 16 Step 451 Train Loss: 0.5148
Epoch 16 Step 501 Train Loss: 0.4639

2026-10-06 18:32:37,753 INFO lasser.utils: [gears_train] done in 4984.8s, peak CUDA memory 0.91 GB
2026-10-06 18:32:37,775 INFO lasser.utils: [evaluate] start
2026-10-06 18:35:38,205 INFO lasser.evaluation: test (eval.py): pearson_delta=0.5745 mse_top20_de=0.1875 nmse_top20_de=1.0387 over 107 perts
2026-10-06 18:35:38,206 INFO lasser.evaluation:   combo_seen0    pearson_delta=0.6465 mse_top20_de=0.1467 (9 perts)
2026-10-06 18:35:38,206 INFO lasser.evaluation:   combo_seen1    pearson_delta=0.6005 mse_top20_de=0.1976 (43 perts)
2026-10-06 18:35:38,207 INFO lasser.evaluation:   combo_seen2    pearson_delta=0.6332 mse_top20_de=0.1849 (19 perts)
2026-10-06 18:35:38,208 INFO lasser.evaluation:   unseen_single  pearson_delta=0.4943 mse_top20_de=0.1871 (36 perts)
2026-10-06 18:35:38,210 INFO lasser.utils: [evaluate] done in 180.4s, peak CUDA memory 1.19 GB
2026-10-06 18:35:38,235 INFO lasser.tracking: appended run 493c3ac6 to /kaggle/working/runs/runs.csv

('/kaggle/working/runs/norman_seed1_gl_20261006-170850',
 {'threshold': 0.2,
  'hit_rate_added': 0.03598640859127045,
  'hit_rate_added_only': 0.03598640859127045,
  'hit_rate_topup': nan,
  'hit_rate_degree_matched_random': 0.0016736617544665933,
  'hit_rate_a0': 0.5806451439857483,
  'hit_rate_removed': 0.75,
  'passes': True},
 {'a0_edges': 6364,
  'removed': 20,
  'added_directed': 38848,
  'topup_directed': 0,
  'refined_edges': 45192,
  'new_weight_mean': 0.24045628309249878,
  'a0_weight_mean': 0.5615240931510925})

In [8]:
# 7. Results: the global run table, and any past run loaded back.
import pandas as pd
pd.set_option("display.max_columns", 200)
runs = pd.read_csv("/kaggle/working/runs/runs.csv")
cols = ["run_id", "seed", "graph_learning", "gsr_init_gene_emb", "graph_num_edges", "graph_isolated_genes",
        "test_pearson_delta", "test_mse_top20_de", "test_nmse_top20_de",
        "test_unseen_single_pearson_delta", "test_combo_seen0_pearson_delta",
        "test_combo_seen1_pearson_delta", "test_combo_seen2_pearson_delta", "run_dir"]
display(runs[[c for c in cols if c in runs.columns]])

r = load_run(gl["run_dir"])
display(r["epoch_log"])
r["test_metrics"]["paper"]["subgroups"]

,run_id,seed,graph_learning,gsr_init_gene_emb,graph_num_edges,graph_isolated_genes,test_pearson_delta,test_mse_top20_de,test_nmse_top20_de,test_unseen_single_pearson_delta,test_combo_seen0_pearson_delta,test_combo_seen1_pearson_delta,test_combo_seen2_pearson_delta,run_dir
0,f71d4a24,1,False,False,6364,4419,0.533766,0.210485,1.428422,0.463590,0.634930,0.558603,0.562602,/kaggle/working/runs/norman_seed1_base_2026100...
1,493c3ac6,1,True,False,45192,0,0.574455,0.187517,1.038668,0.494295,0.646518,0.600508,0.633239,/kaggle/working/runs/norman_seed1_gl_20261006-...

,epoch,train_mse,val_mse,train_mse_de,val_mse_de,train_loss_logged_mean,n_logged_steps,is_best
0,1,0.0032,0.0041,0.1239,0.2875,0.483009,32,True
1,2,0.0040,0.0048,0.1317,0.3456,0.496663,32,False
2,3,0.0024,0.0034,0.0868,0.2366,0.498409,32,True
3,4,0.0024,0.0037,0.0926,0.2610,0.502200,32,False
4,5,0.0023,0.0033,0.0742,0.2097,0.522313,32,True
5,6,0.0021,0.0032,0.0735,0.2126,0.503419,32,False
6,7,0.0022,0.0035,0.0715,0.2334,0.506322,32,False
7,8,0.0021,0.0033,0.0716,0.2269,0.533853,32,False
8,9,0.0022,0.0035,0.0680,0.2194,0.531909,32,False
9,10,0.0020,0.0033,0.0774,0.2231,0.503912,32,False
10,11,0.0022,0.0034,0.0666,0.2297,0.503012,32,False
11,12,0.0022,0.0034,0.0657,0.2210,0.495503,32,False
12,13,0.0021,0.0034,0.0709,0.2253,0.503166,32,False
13,14,0.0021,0.0033,0.0734,0.2256,0.515603,32,False
14,15,0.0021,0.0033,0.0742,0.2244,0.513997,32,False
15,16,0.0021,0.0033,0.0702,0.2331,0.497244,32,False
16,17,0.0020,0.0032,0.0753,0.2164,0.509191,32,False
17,18,0.0021,0.0033,0.0687,0.2132,0.519219,32,False
18,19,0.0020,0.0032,0.0785,0.2264,0.507969,32,False
19,20,0.0020,0.0033,0.0781,0.2273,0.507119,32,False

{'combo_seen0': {'n_perts': 9,
  'mse': 0.004927011206746101,
  'pearson': 0.9859106227311661,
  'mse_top20_de': 0.14665594427949852,
  'mse_top20_de_noperturb': 0.3686102908104658,
  'nmse_top20_de': 3.4552874007028884,
  'pearson_top20_de': 0.747353105451855,
  'pearson_delta': 0.6465183858281702,
  'pearson_delta_top20_de': 0.6548946607209559,
  'frac_opposite_top20_de': 0.5333333333333334,
  'frac_correct_direction_top20_de': 0.46666666666666656,
  'nmse_top20_de_ratio_of_means': 0.397861774170887},
 'combo_seen1': {'n_perts': 43,
  'mse': 0.00549168914399478,
  'pearson': 0.9845545444806643,
  'mse_top20_de': 0.19756975584815062,
  'mse_top20_de_noperturb': 0.48487508398762275,
  'nmse_top20_de': 0.9438417085966495,
  'pearson_top20_de': 0.8624252416685393,
  'pearson_delta': 0.6005083183312933,
  'pearson_delta_top20_de': 0.710915503746452,
  'frac_opposite_top20_de': 0.3581395348837209,
  'frac_correct_direction_top20_de': 0.6418604651162791,
  'nmse_top20_de_ratio_of_means': 0.4074652675970331},
 'combo_seen2': {'n_perts': 19,
  'mse': 0.004240183766294075,
  'pearson': 0.9881088931372151,
  'mse_top20_de': 0.18492641750919192,
  'mse_top20_de_noperturb': 0.6160734672295419,
  'nmse_top20_de': 0.38716913896240274,
  'pearson_top20_de': 0.9212246949690757,
  'pearson_delta': 0.6332391801847226,
  'pearson_delta_top20_de': 0.8110884723218189,
  'frac_opposite_top20_de': 0.16052631578947368,
  'frac_correct_direction_top20_de': 0.8394736842105263,
  'nmse_top20_de_ratio_of_means': 0.3001694235280067},
 'unseen_single': {'n_perts': 36,
  'mse': 0.003021450610605017,
  'pearson': 0.9912110021528202,
  'mse_top20_de': 0.18709062285617822,
  'mse_top20_de_noperturb': 0.3019400484085458,
  'nmse_top20_de': 0.8916235040647444,
  'pearson_top20_de': 0.87830941885054,
  'pearson_delta': 0.49429503766725247,
  'pearson_delta_top20_de': 0.6116920825559872,
  'frac_opposite_top20_de': 0.375,
  'frac_correct_direction_top20_de': 0.625,
  'nmse_top20_de_ratio_of_means': 0.6196283793497696}}